### ISSUE TITLE
leaflet-gpxgroup.js not working when gpx files contain waypoints

### ISSUE THREAD

**Issue by hupe13** [Raruto/leaflet-elevation#101]
Followup from https://github.com/Raruto/leaflet-elevation/issues/99#issuecomment-817273173

> The second problem: I mean, leaflet-gpxgroup.js does not show the elevation profile for every gpx file. But leaflet-elevation.js does the job right with all gpx files. Should I prepare an example?

Solved. The gpx files that do not work contain one or more waypoints before the track, like:

```html
...
</metadata>
<wpt lat="...." lon="...">
<ele>....</ele>
<time>2011-06-29T08:13:54Z</time>
<name>Mittelstation</name>
<sym>Startflagge</sym>
</wpt>
<trk>
<name>W55</name>
...
```

I changed in leaflet-gpx-group.js:
```sh
bash-4.2$ diff leaflet-gpxgroup.js  leaflet-elevation-1.6.7/libs/leaflet-gpxgroup.js 
207c207,208
<       polyline_options: line_style
---
>       polyline_options: line_style,
>       gpx_options: this.options.gpx_options,
```

and in the opts:
```js
var opts = {
    points: {
      ....
    },
    elevation: {
     ....
    },
    markers: {
      ....
    },
    gpx_options: {
	parseElements: ['track','route'],
    }
  };
```
Now it works (for me).

**Comment by Raruto** [comment]
It would seem a problem more related to: https://github.com/mpetazzoni/leaflet-gpx/issues/107
It seems that the latest version (1.5.2) should contain the fix.

_Have a nice day,
Raruto_

**Comment by hupe13** [comment]
Hi Raruto,

sorry for the late reply. I have tested it and everything is okay.
Thank you very much!

**Comment by Raruto** [comment]
Ok, good to know 👍.
