### ISSUE TITLE
Elevation Profile for Routing

### ISSUE THREAD

**Issue by webmap2015** [Raruto/leaflet-elevation#103]
Hi,

I want to make elevation profile for routing.

I can export the route between the waypoints as geojson.

```js
{
    "name": "demo.geojson",
    "type": "FeatureCollection",
    "features": [{
            "type": "Feature",
            "geometry": {
                "type": "LineString",
                "coordinates": [[..., ...], [..., ...]]
            },
            "properties": null
        }
    ]
}
```

But height value is missing and I want to add it.

Is there any elevation service with supporting LineString geometries?

Thanks.

**Comment by Raruto** [comment]
Hi webmap,

I can't say much about this, if it can help your try to take a look at the following:

- https://parcours.scasb.org/
- https://framagit.org/gegeweb/scasb-calcul-itineraires-velo

_Have a nice day,
Raruto_

**Comment by webmap2015** [comment]
Thanks.
