### ISSUE TITLE
Elevation profile height has changed

### ISSUE THREAD

**Issue by skirridsystems** [Raruto/leaflet-elevation#104]
Previously I was using 1.3.7 and a profile looked something like this:
![profile-new-height](https://user-images.githubusercontent.com/5455596/117042642-23fa1b00-ad04-11eb-82e3-e52054efbdf2.jpg)

Now that I've upgraded to 1.6.7 the profile (different map) looks like this:
![profile-new-height](https://user-images.githubusercontent.com/5455596/117042456-ebf2d800-ad03-11eb-9e02-90115e02dc04.jpg)

OK, these are different maps with different overall heights, but on the old version the profile occupied about 95% of the available height. On the new version it's been crushed down to maybe 55% with a lot of blank canvas top and bottom. I can't see anything in the CSS which would cause this. Is this an intentional change? Is there an option I need to set to reclaim the full height expansion?

https://skirridsystems.co.uk/wordpress-plugins/os-datahub-maps/
Sorry, you'll have to scroll down to find the one with the elevation profile.

**Comment by Raruto** [comment]
Hi Simon,

in version 1.6.x things have changed a bit (in particular regarding the resizing of the chart), ref. https://github.com/Raruto/leaflet-elevation/issues/97 and https://github.com/Raruto/leaflet-elevation/issues/98#issuecomment-808712298

If I'm not mistaken, graph height is calculated at the following lines:

https://github.com/Raruto/leaflet-elevation/blob/a9f2c2a6230d8bfb55bbe12d7eae3a45845cfaa4/src/components.js#L414

https://github.com/Raruto/leaflet-elevation/blob/a9f2c2a6230d8bfb55bbe12d7eae3a45845cfaa4/src/components.js#L499

The chart object is instanced at the following line:

https://github.com/Raruto/leaflet-elevation/blob/a9f2c2a6230d8bfb55bbe12d7eae3a45845cfaa4/src/chart.js#L42

Overall it could be a problem related to:

- too high value of the **margins** option
- too high value of the **yTicks** option
- bug related to the **legend: false** option

As usual, any additional help is welcome...

**Comment by skirridsystems** [comment]
Maybe this?
https://github.com/Raruto/leaflet-elevation/blob/a9f2c2a6230d8bfb55bbe12d7eae3a45845cfaa4/src/chart.js#L611
```js
		let marginB = 60 + (xAxesB * 2);
		let marginR = n * 30;

		// Adjust chart right margins
		if (n && this.options.margins.right != marginR) {
			this.options.margins.right  = marginR;
			this.fire('margins_updated');
		}

		// Adjust chart bottom margins
		if(xAxesB && this.options.margins.bottom != marginB) {
			this.options.margins.bottom = marginB;
			this.fire('margins_updated');
		}

```

**Comment by Raruto** [comment]
It might be possible (sorry, but I don't have much time to devote to this at the moment), if you are interested you can investigate the differences of that portion from the previous version: https://github.com/Raruto/leaflet-elevation/commit/7c0262cf1f6fce0a46cbbf345c5a09745b282903#diff-53aa5b852a2ae4fc1256622d467574e40ceea689796466f62dfa9cd6c0d66e34L915-L1014

_Have a nice day,
Raruto_

**Comment by skirridsystems** [comment]
That section of code has been completely re-written so the changes don't reveal much.

But I can confirm that the lines I highlighted which override the bottom margin are indeed the problem. If I change the 60 to 30 then it is pretty similar to what it was before.

However, I don't understand what the code there is doing and I don't think just changing that number is the right thing to do.

```js
        var xAxesB = this._axis.selectAll('.x.axis.bottom').nodes().length;
        var marginB = 60 + xAxesB * 2;
```
On my elevation plots, xAxesB always has a value of 1, so I'm guessing it's a count of something. But adding 2 pixels per count doesn't seem to make much sense, so I'm guessing the expression may be wrong? Sorry, my JS is not too hot.

If it's make sure there's enough space for labels or annotations then maybe the test should be "if the margin is smaller than I need, make it as big as I need", rather than always overriding the user margin values.

The top margin has also changed, but that's because the height annotation is now above the chart instead of on the left of the chart. I can change that one using the margins in Options.

**Comment by Raruto** [comment]
That calculation was first introduced in this commit: https://github.com/Raruto/leaflet-elevation/commit/87f8290d18dda16da824b44cacb8b3cdf0268b5c

The basic idea was to dynamically adapt / increase the right and bottom margins on the basis of the number of "stacked" axes (the same goes for the legend control). For overall simplicity, the new value is substituted within the "margin" option (making it perhaps currently impossible to provide a custom value).

If I'm not mistaken, d3js doesn't provide a ready-to-use feature.

If you find a simpler solution, I'll be happy to merge it.

_Have a nice day,
Raruto_
