### ISSUE TITLE
stuttering on Safari ( 14.0.3 )

### ISSUE THREAD

**Issue by hansgohr** [Raruto/leaflet-elevation#108]
Hi there,

I'm experiencing some extreme stuttering when using Safari (also with the demos, I tried the .gpx and .geojson examples )
Currently tried it with Safari Version 14.0.3 

Do you have any idea how to fix it?
cheers & thank you :)

**Comment by Raruto** [comment]
Hi hansgohr, it could be a gpx file size issue or a lack of available hardware resources (e.g. on mobile phones), however please note that I am unable to verify it. 

If it can help you, you can start by trying to monitor with the browser [performance tool](https://developer.apple.com/safari/tools/) while the map is running.

_Have a nice day,
Raruto_

**Comment by skirridsystems** [comment]
I have also had users report issues with Safari on 1.6.7. The particular issue reported here is that the position marker and elevation details popup only appear when the cursor is over the shaded part of the profile, not when over the background. I'm also told that even the profile part is not entirely reliable. This was working on 1.5.4

I don't own any Apple devices but I have verified this by getting an account with BrowserStack, which you can get for free if you have an open source project. It's not great (quite laggy compared with a real local machine) but it does show the problem.

**Comment by Raruto** [comment]
Hi Simon,

from version 1.6.x mouse interactions ( hover / drag ) are handled through the core [d3-brush](https://github.com/d3/d3-brush) control.

https://github.com/Raruto/leaflet-elevation/blob/a9f2c2a6230d8bfb55bbe12d7eae3a45845cfaa4/src/chart.js#L171-L204

The problem you report it could be somehow related to a different beahviour of the z-index [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) on this browser.

![overlay](https://user-images.githubusercontent.com/9614886/119313964-729c3480-bc74-11eb-875d-fbb97146a3c2.png)

Thanks for BrowserStack's advice, but (honestly) I leave this task to anyone who is keenly interested in fixing this issue ..

_Have a nice day,
Raruto_

**Comment by vhyza** [comment]
Hi @hansgohr and @Raruto,

I'm not sure why, but when I disable `pointer-events` for `foreignobject` located in `g.area` the stuttering is gone.

So I just added

```
svg g.area foreignObject {
  pointer-events: none;
}
```

into my CSS. Maybe it helps you too...

**Comment by Raruto** [comment]
Hi Vojtěch,
thanks for reporting.

It could be a bug related to safari: https://stackoverflow.com/questions/63799631/svg-foreignobject-render-issue-in-chrome-and-safari

I think there should be no problem even using the `prefercanvas: true` option (as pointer events are all tracked through the `g.brush> overlay`).

_Have a nice day,
Raruto_

**Comment by vhyza** [comment]
Hi @Raruto,

thank you for the clarification.
