### ISSUE TITLE
Margin for legend is calculated despite opts legend: false

### ISSUE THREAD

**Issue by panotom** [Raruto/leaflet-elevation#109]
Hi Raruto,
great component you have created there!
I'm on the way to program a new Web Frontend for opentopomap.org and plan to use your leaflet-elevation. I encountered that the bottom space for the legend is calculated despite I set legend to false in the opts. Before I do an ugly workaround I wanted kindly to ask you if a timely fix is possible. Testwise I just skipped the _updateLegend function in charts.js when legend == false and everything works perfectly for me.
Thanks in advance
Thomas

**Comment by Raruto** [comment]
Hi panotom,

this issue is related to the following https://github.com/Raruto/leaflet-elevation/issues/104

As a temporary solution you can do such a thing:

```js
// insert the following before instantiating the elevation control

var _updateLegendProto = L.Control.Elevation.Chart.prototype._updateLegend;

L.Control.Elevation.Chart.include({
  _updateLegend: function() {
    if (this.options.legend == false) return;
    _updateLegendProto.call(this);
  }
});
```

In future releases it will be fixed anyway.

_Happy Monday,
Raruto_

**Comment by panotom** [comment]
Thanks so much for reply, Looking forward to next release. Happy Monday too. Thomas.
