### ISSUE TITLE
Button to reset the profile selected area

### ISSUE THREAD

**Issue by ghtmtt** [Raruto/leaflet-elevation#11]
Currently it seems that when a piece of area is selected in the elevation profile there is not possible to reset the view to the initial map. Would it be possible to add this feature?

**Comment by Raruto** [comment]
there is an internal function that deals with this:
https://github.com/Raruto/leaflet-elevation/blob/6cb2b177f3be651c477224025a2c5d31aa336c8e/leaflet-elevation.js#L945
however, from version 0.3.1 the rectangle is removed after each single click or scroll made on the map / chart.

**Comment by ghtmtt** [comment]
awesome, thanks!
