### ISSUE TITLE
Waypoints disappear in elevation profile after zooming

### ISSUE THREAD

**Issue by s-bl** [Raruto/leaflet-elevation#112]
Hey,

first of all, thanks for the really nice plugin.

Just one issue: In every other than the default zoom level, the waypoints disappear in the elevation graph. If I zoom back to the default (lowest) zoom level, they appear again.

Is this a known problem? And if so, is there a fix for it?

I'm using version 1.6.7 of the plugin.

Thanks for your help.

Best,
Sebastian

**Comment by Raruto** [comment]
Hi sebastian,
there may be an error in javscript code.
This [example](https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation.html) uses version 1.6.7, do you experience the same problem you are reporting? Otherwise, can you provide a fiddle?

_Have nice day,
Raruto_

**Comment by s-bl** [comment]
Hey @Raruto,

many thanks for your feedback. 
At least on my system, I experience the same behaviour with your example.

I'm using Chromium Version 90.0.4430.212 (Official Build) Arch Linux (64-bit).

For you, your example works fine?

Best,
Sebastian

**Comment by Raruto** [comment]
Maybe I misunderstood, by chance you mean the `shift + zoom` functionality above the elevation chart?
In this latter case, I can confirm that this is the expected behavior (ie. re-positioning of chart markers is not implemented).

As usual, resolutive pull requests are welcome.

_Happy coding,
Raruto_

**Comment by s-bl** [comment]
I see. Thanks for the clarification.

I might take a look at it if I find some time.

Best,
Sebastian
