### ISSUE TITLE
SVG order different between servers

### ISSUE THREAD

**Issue by tak-tok** [Raruto/leaflet-elevation#116]
Hello,
And thanks for all your work.

i am facing a problem with the display of some svg groups.
The same app depolyed on 2 differents servers has different behaviour :
- on my local it is fine
- on my vps the labels displayed behind the area (but the html presents the same order...)

![image](https://user-images.githubusercontent.com/6114041/121221249-ab97f400-c885-11eb-8d86-2549d4c9e443.png)

I don't know anymore which direction i should explore to debug....
Any idea ?

Thanks a lot

**Comment by Raruto** [comment]
Hi tak-tok,
it could be a problem related to:
- different browsers behavior (ie. the "stacking context", see: https://github.com/Raruto/leaflet-elevation/issues/108#issuecomment-846864817)
- malformed html structure (check with: https://validator.w3.org/) or a javascript error (check your browser console for this)

_Have a nice day,
Raruto_
