### ISSUE TITLE
Parameter summary and ruler

### ISSUE THREAD

**Issue by hupe13** [Raruto/leaflet-elevation#118]
Hi Raruto,

is there a typo in your [README.md](https://github.com/Raruto/leaflet-elevation/blob/8701a1e917a3cac711cc0862e2fb334015355898/README.md)? It should be:

```js
// Summary track info style: "inline" || "multiline" || false
```

[`downloadLink`](https://github.com/Raruto/leaflet-elevation/blob/8701a1e917a3cac711cc0862e2fb334015355898/src/options.js#L17) is not documented.

I have tested almost all parameters. What does **`ruler`** mean? Do you have an example for this parameter with true and false for the same map?

Thank you very much.

**Comment by hupe13** [comment]
I tested it. If I set slope, speed and acceleration to display not the chart, ruler disappears. But if I set one of these to display the chart, I can't disable the ruler. Setting ruler to false has no effect.

**Comment by Raruto** [comment]
Hi hupe13,

> is there a typo in your [README.md](https://github.com/Raruto/leaflet-elevation/blob/8701a1e917a3cac711cc0862e2fb334015355898/README.md)? It should be:
>
> ```js
> // Summary track info style: "inline" || "multiline" || false
> ```

Yes, you are right.

---

> [`downloadLink`](https://github.com/Raruto/leaflet-elevation/blob/8701a1e917a3cac711cc0862e2fb334015355898/src/options.js#L17) is not documented.

You're right, here you can find some little information about it https://github.com/Raruto/leaflet-elevation/issues/86#issuecomment-735274347

> What does **`ruler`** mean?

That option allows you to enable / show the following horizontal "ruler" line:

![immagine](https://user-images.githubusercontent.com/9614886/127474030-08fbd024-e4fd-4f80-bc32-75cd9591909e.png)

> Do you have an example for this parameter with true and false for the same map?

No, but if you want to create one it's welcome.

> I can't disable the ruler. Setting ruler to false has no effect.

Ok got it, the solution to the bug it could be among these lines:

https://github.com/Raruto/leaflet-elevation/search?q=ruler

https://github.com/Raruto/leaflet-elevation/blob/8701a1e917a3cac711cc0862e2fb334015355898/src/chart.js#L42
https://github.com/Raruto/leaflet-elevation/blob/8701a1e917a3cac711cc0862e2fb334015355898/src/chart.js#L298
https://github.com/Raruto/leaflet-elevation/blob/8701a1e917a3cac711cc0862e2fb334015355898/src/components.js#L430

Additional help and pull requests are always welcome.

_Have a nice day,
Raruto_

**Comment by hupe13** [comment]
Hi Raruto,

>> Do you have an example for this parameter with true and false for the same map?

> No, but if you want to create one it's welcome.

I have some examples with your plugin: https://leafext.de/en/doku/elevation/
But these are for WordPress using WordPress plugins Leaflet Map and Extensions for Leaflet Map.
The ruler parameter isn't installed yet. I will wait for your solution, this seems too complicated for me.

Thank you very much.
hupe13

**Comment by hupe13** [comment]
Thank you for documentation in [#86 (comment)](https://github.com/Raruto/leaflet-elevation/issues/86#issuecomment-735274347).
