### ISSUE TITLE
Waypoints on gpx and geojson on smartphone

### ISSUE THREAD

**Issue by hupe13** [Raruto/leaflet-elevation#119]
Hi Raruto,

your examples leaflet-elevation.html, leaflet-elevation_gpx-waypoints.html and leaflet-elevation_geojson-waypoints.html do not work on smartphone. Both the tooltip and the popup are displayed.

Can you fix this? Thank you very much.

**Comment by Raruto** [comment]
Hi hupe13,
It might be somewhat related to the [leaflet-ui](https://github.com/Raruto/leaflet-ui/) library (as it can lazy-load the leaflet.css file when missing).

You can try to check by doing this way:

```html
<!-- ADD leaflet.css before leaflet-ui.js -->
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css" />

<!-- leaflet-ui -->
<script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"></script>
<script src="https://unpkg.com/leaflet-ui@0.5.0/dist/leaflet-ui.js"></script>
```

_Have a nice day,
Raruto_

**Comment by hupe13** [comment]
I found the solution here: https://gis.stackexchange.com/questions/311557/hiding-leaflet-tooltip-on-mobile-device
```
@media (hover: none) {
  .leaflet-tooltip-pane { display: none; }
}
```
