### ISSUE TITLE
How to suppress waypoints

### ISSUE THREAD

**Issue by skirridsystems** [Raruto/leaflet-elevation#120]
Waypoint markers are being added to the map both by the GPX plugin (leaflet-gpx) and by leaflet-elevation so there are two markers on the map for each waypoint. It's good to see the waypoints showing on the elevation profile but is it possible to prevent the pushpin icon being added to the map?

**Comment by Raruto** [comment]
Hi Simon,
currently there is no js option for this (although not optimal, if you use svg panes you can do it via css), I recommend you read the following thread for more info about it: https://github.com/Raruto/leaflet-elevation/issues/100

In particular, you can also write a function like this yourself for more specific behaviors:

https://github.com/Raruto/leaflet-elevation/blob/22463a371b0d0af8b71688c0fc3004aeb1d8463b/src/utils.js#L67-L156

As always, pull requests are welcome.

_Have a nice day,
Raruto_

**Comment by Raruto** [comment]
Added in version **1.7.0**:

```js
// Display track waypoints: (true || false)
waypoints: false,
```
