### ISSUE TITLE
Changing the default summary on a collapsed elevation profile

### ISSUE THREAD

**Issue by patrickgray227** [Raruto/leaflet-elevation#125]
At the moment the default summary when the elevation control is not detached and is collapsed, which is my preferred setting, is
**Total Length: 12.05km  Max Elevation:  509.00m  Min Elevation: 90.00m**

Is there a way to change this to give, for example, just  **Total Length: 12.05km  Total Ascent:  509.00m**

or, even better, just  **Distance: 12.1km  Ascent:  509m** where the names are simplified and the values given to 0 or 1 decimal places ?

**Comment by Raruto** [comment]
Hi patrick,
for decimal precision and other custom labels I suggest you look at the source code of the following examples:

- [leaflet-elevation_custom-summary.html](https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_custom-summary.html)
- [leaflet-elevation_speed-chart.html](https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_speed-chart.html)
- [leaflet-elevation_slope-chart.html](https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_slope-chart.html)
- [leaflet-elevation_i18n-strings.html](https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_i18n-strings.html)

_Have a nice day,
Raruto_

**Comment by patrickgray227** [comment]
Hi Raruto
Many thanks for your swift reply.
I have in fact already looked at the source code for all your updated examples and explored all of them.
By trial and error (I'm only a beginner at Javascript) I've successfully made changes to many so as to show my tracks here in Ireland and their elevations. I found no real difficulty in implementing what I want by way of a custom summary but only with a detached elevation at the screen bottom.

However I can find no examples of a custom summary for a popup collapsed non-detached elevation profile accessed by clicking on an icon in a corner of the screen. I suspect that to do this would involve some coding which is beyond me - maybe you or one of the other contributors might consider implementing this facility at some time ?

I should say that your leaflet-ui and leaflet-elevation are both wonderful additions to Leaflet. Keep up the good work !

All the best,
Patrick

**Comment by Raruto** [comment]
Maybe there is some bug in code, but this [jsfiddle](https://jsfiddle.net/r1gp72hd/) should help you.

_Still waiting for extra help,
Raruto_

**Comment by patrickgray227** [comment]
Thanks for that, Raruto.
Now I see it can be done but I must confess that I'm really out of my depth here - I can understand some of the coding but my knowledge of Javascript is very, very basic.
I've been able to experiment with one of your updated examples - leaflet-elevation/examples/leaflet-elevation_close-button.html  and one of your original examples - leaflet-elevation_upload-gpx to achieve what I want except for the custom summary.

If you could find the time to make the necessary changes in either of these examples of yours so that the summary is, for example           Distance: 52.3 km  -  Ascent: 914 m        Download
- I'd like to include a downloadLink - then I 'm reasonably happy that I could take it from there.

If you were able to do this then I dare say others would welcome the result being included in your update examples.

I greatly appreciate your response so far and I realise this is asking a lot but I live in hope.

Many thanks again
Patrick

**Comment by Raruto** [comment]
Hi patrick,
you can take a look at original [_updateSummary](https://github.com/Raruto/leaflet-elevation/blob/8701a1e917a3cac711cc0862e2fb334015355898/src/control.js#L936-L949) function for inspiration.

Here, for example, how you could do if you have the original url of the file:

```js
let track_url = "https://example.com/track.gpx"
...
controlElevation.load(track_url);
controlElevation.on('eledata_loaded', function(e) {
  q('.elevation-summary').innerHTML = '<span class="download"><a href="' + track_url + '">Download</a></span>';
});
```

Instead, for dynamically generated download files, take a look at [source code](https://framagit.org/gegeweb/scasb-calcul-itineraires-velo/) of the following project: [parcours.scasb.org](https://parcours.scasb.org/).

Please, for further support on js / leaflet, make use of [stackoverflow.com](https://stackoverflow.com/search?q=leaflet-elevation) and [gis.stackexchange.com](https://gis.stackexchange.com/search?q=leaflet-elevation).

_Have a nice day,
Raruto_
