### ISSUE TITLE
distance true / "summary" and altitude

### ISSUE THREAD

**Issue by hupe13** [Raruto/leaflet-elevation#126]
Hi Raruto,

> // Display distance info: true || "summary"

if distance is set to true, all is okay. But if distance is set to "summary", the distance information on the x-axis disappears. Is this expected? If yes, then "summary" should be called false or "disabled". If not, then it is an error.

> // Display altitude info: true || "summary"

This should be

> // Display altitude info: true || "disabled"

**Comment by Raruto** [comment]
Hi hupe,
can you upload screenshots with relevant portions of code?

_Raruto_

**Comment by hupe13** [comment]
You can see this at https://leafext.de/en/doku/elevation/liste/?testing=distance

**Comment by Raruto** [comment]
Generally,

- **`disabled`** refers to the initial state of the elevation profile (i.e. legend filter visible but disabled)
- **`summary`** hides the related axis and shows the calculation of related statistics (eg total distance) on summary div

if I'm not mistaken, the basic idea was to allow more advanced visualizations (or custom presets), eg:

```js
distance: "summary"
time: true,
```

_Raruto_

**Comment by hupe13** [comment]
> - **`summary`** hides the related axis and shows the calculation of related statistics (eg total distance) on summary div

Ok. Then  **`summary:`** must not be 0.
Thank you for explanation.
