### ISSUE TITLE
Possible bug:  ruler not shown when loading data after page ready.

### ISSUE THREAD

**Issue by vutle** [Raruto/leaflet-elevation#153]
When adding data and control after webpage is loaded,  the ruler is not shown.  
Until we resize the browser then the ruler becomes visible.

**Comment by Raruto** [comment]
Hi vulte,
can you produce a working example? (otherwise it's hard to tell if it's a bug)

Anyway, you can use the following function to force resizing:

https://github.com/Raruto/leaflet-elevation/blob/9b21b254068027bb6f3cd4bafcd47e7e248e11fe/src/control.js#L353-L358

_Regards,
Raruto_
