### ISSUE TITLE
waypoints in gpxgroup

### ISSUE THREAD

**Issue by hupe13** [Raruto/leaflet-elevation#155]
Hi Raruto,

if I create a map like in the [example](https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_hoverable-tracks.html), then the waypoints in gpx files are to much, they should not be displayed:

```
> diff leaflet-gpxgroup.js leaflet-gpxgroup.js.orig
140,142d139
<     },
<     gpx_options: {
<       parseElements: ["track", "route"],
210,211c207
<       polyline_options: line_style,
<       gpx_options: this.options.gpx_options,
---
>       polyline_options: line_style
```

Can you adjust the code, please?
Thank you very much.

**Comment by Raruto** [comment]
Hi hupe,
please create a pull request about it, in this way your request is more likely to be accepted / understood ...

_I can't always develop all that is asked myself,
Raruto_

**Comment by hupe13** [comment]
Done.
