### ISSUE TITLE
name in gpxgroup

### ISSUE THREAD

**Issue by hupe13** [Raruto/leaflet-elevation#159]
Hi Raruto,

can you provide please an option for the  geojson.name  - either the basename of the file or the track name in the file?
You can program this much better than me. ;-)

Thank you very much.

**Comment by Raruto** [comment]
Hi Hupe,

> can you provide please an option for the geojson.name - either the basename of the file or the track name in the file?

hasn't it already been done in here? https://github.com/Raruto/leaflet-elevation/commit/2e836885f0ee4ca18de95a12f0e2badadae0a503

>  You can program this much better than me. ;-)

Please note that I currently use very little of this library and do all this in my spare time...

_Sincerely,
Raruto_

**Comment by hupe13** [comment]
Created a [pull request](https://github.com/Raruto/leaflet-elevation/pull/160#issue-1071540453).
