### ISSUE TITLE
Custom L.GpxGroup colors

### ISSUE THREAD

**Issue by Zinnoxid** [Raruto/leaflet-elevation#16]
Good Morning,

for my project to visualize hiking routes in my home region (~70 routes) I plan to implement elevation charts.

I played around with your plug in and the example hoverable .gpx tracks. I do not fully understand what's going on, because I am still a beginner in programming. I just worked with your example and changed the GPS tracks and points for my needs. It worked so far but when I switch to version 0.4.9 it won't work. So I switched back to 0.3.9. It is not important which version I use.

Further question is, how can I give each route its defined colour on map and legend?

**Comment by Raruto** [comment]
Hi zinnoxid,

For the issue with 0.4.9 you can **Open Developer Tools:** `ctrl` +` shift` + `i` on it and you should be able to see if the console reports some errors (if you could provide an online example it would be nice to see it).

Below a starting point on how to **manually** set track **colors**:

```js
 // Override default "L.GpxGroup" class behaviour.
  L.GpxGroup.include({

  /**
    * Edit the following function as you fit.
    *
    * @param count    index of ".gpx" track within tracks array
    * @return colors  array of strings up to ("hex" colors) that given index
    */
  _uniqueColors: function(count) {

    // CURRENT behaviour

    // if (count === 0) return [];
    // if (count === 1) return ['#0000ff'];
    // var increment = 1 / count;
    // var colors = [];
    // for (var i = 0; i < count; ++i) {
    //  var hue = i * increment;
    //  var rgb = this._hsvToRgb(hue, 1, 0.7);
    //  var hex = '#' + this._rgbToHex(rgb[0], rgb[1], rgb[2]);
    //  colors.push(hex);
    // }

    // CUSTOM behaviour
    var colors = ['#0000ff', '#00ff00', '#ff0000', /* etc. etc. */];

    return colors;
  },

});
```
**NB** that code snippet must be added **before** the following line:
```js
var routes = L.gpxGroup(tracks, { ... });
```

_Have a nice day,
Raruto_

**Comment by Raruto** [comment]
**Update:** 

there was a bug introduced in version **0.4.6** related to missing Javascript Promises (aka. lazy loader) when required libraries (d3.js / leaflet-gpx.js) are already included; version **0.5.0** shouldn't be affected anymore.

**Comment by Zinnoxid** [comment]
Thank you for the messages!  I will work with your suggestions, but it will take a (short) while :)
You can get a link to my project sure. I prefer a private channel

**Comment by Zinnoxid** [comment]
Just another thing, is it right that a gpx-file must have only one segment? Unfortunately almost all of my gpx-tracks are segmentated got different directions and gaps.
