### ISSUE TITLE
The names of the points on the elevation plot

### ISSUE THREAD

**Issue by wpysz** [Raruto/leaflet-elevation#162]
How can I turn off the display of points on the elevation plot? Or removing WPT names. 

When I was using leaflet-elevation version 1.5.6 - it wasn't on the WPT chart and that suited me: https://ciekawe.tematy.net/testy/le/example-1.5.6.html
Now I'm trying to use version 1.7.3: https://ciekawe.tematy.net/testy/le/example-1.7.3.html

I would like to use version 1.7.3 (it has interesting new features) and be able to exclude WPT from the chart. 

![screen02](https://user-images.githubusercontent.com/70205437/147487201-d80b7b63-0306-4e41-b76e-c877409ee935.jpg)

**Comment by wpysz** [comment]
I looked through the script leaflet-elevation.js and found no way to disable the waypoints in the height plot. Maybe I was looking poorly :-)
I propose to introduce two new values to the Option variable into the script: 
```
  wptOnChart: true,
  wptNameOnChart: true,
```
And make a small change starting with line 210, instead of: 
```
control._registerCheckPoint({
  latlng: latlng,
  label: name
}, true);
```
enter the code like this: 
```
if (control.options.wptOnChart){
  if (!control.options.wptNameOnChart) name='';
  control._registerCheckPoint({
    latlng: latlng,
    label: name
  }, true);
}
```
The user will then be able to manage the display of points and their names by using these options in their script. 
```
  elevationControl: {
    options: {
      ....
      wptOnChart: false,
      wptNameOnChart: false,
      ....
```
Sorry if my idea is primitive but I'm not an experienced developer. 

Wojtek Pysz

**Comment by Raruto** [comment]
Hi Wojtek,
I'd solve this even more simply:

```css
.elevation-control .point text {
  display: none;
}
```

_Raruto_

**Comment by wpysz** [comment]
Indeed, hiding names with CSS style is simpler and faster. Thanks for the hint.

But if the options mentioned by me were introduced in a future version, the visibility of points or just subtitles could be controlled with the option. There are already a lot of them and they allow for a good personalization of the map and graph. I always use many of them. Probably other users too. It would then be possible to set everything up in one place without messing about with CSS.

**Comment by Raruto** [comment]
Added in version **1.7.4**

```js
    // Display track waypoints: true || "markers" || "dots" || false
    waypoints: true,

    // Toggle custom waypoint icons: true || { associative array of <sym> tags } || false
    wptIcons: {
      '': L.divIcon({
        className: 'elevation-waypoint-marker',
        html: '<i class="elevation-waypoint-icon"></i>',
        iconSize: [30, 30],
        iconAnchor: [8, 30],
      }),
    },

    // Toggle waypoint labels
    wptLabels: true,
```

**Comment by wpysz** [comment]
```
         if (!wptLabels) {
            name = '';
            desc = '';
          } // Handle chart waypoints (dots)
```
Thanks for including my idea in the script! I have made initial tests of the introduced changes.
The above code snippet (contrary to the comment) disables displaying the name of the point not only in the graph ("dots"), but also disables displaying the name and desc for markers on the map. 

Wojtek Pysz

**Comment by Raruto** [comment]
Ok, check out version **1.7.5**

```js
// Toggle waypoint labels: true || "markers" || "dots" || false
wptLabels: true,
```

https://github.com/Raruto/leaflet-elevation/commit/0abcc390158877452e2d04290f6208cd4046ba42
