### ISSUE TITLE
Toggle waypoint tooltip and popup content visibility

### ISSUE THREAD

**Issue by bknt011** [Raruto/leaflet-elevation#165]
Another question:
In my GPX file there is a <name> field and a <desc> field with a link to a website.
With the current script I get a tooltip with <name> and <desc> and also in the popup.
I only want the <name> in the popup and both in the popup.
Can I set this anywhere?

**Comment by Raruto** [comment]
Hi bktn011,
just use a css selector like the following:

```css
.elevation-tooltip a {
  display: none;
}
```

**Reference:** [leaflet-elevation_gpx-waypoints.html](https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_gpx-waypoints.html)
