### ISSUE TITLE
Zoomlevel Openstreetmap

### ISSUE THREAD

**Issue by bknt011** [Raruto/leaflet-elevation#166]
I want to increase the zoom level of the Openstreetmap.
But if I go over zoom = 16, the street map is switched to satellite.
Can I adjust that somehow?

Here is the code at the point:

var opts = {
map: {
center: [48.7, 9.0], // needs value to initialize
                        zoom: 16, // needs value to initialize
                        mapTypeId: 'streets',
                        mapTypeIds: ['streets', 'satellite', 'topo'],

**Comment by Raruto** [comment]
Hi bktn011,
you're probably referring to this other plugin [leaflet-ui](https://github.com/Raruto/leaflet-ui), please open there related issues or pull requests.

_Regards,
Raruto_
