### ISSUE TITLE
Append custom labels inside chart tooltip

### ISSUE THREAD

**Issue by velocat** [Raruto/leaflet-elevation#168]
Hello Raruto.
I haven't asked questions for a long time, but now I have a couple of questions:

1. How to add labels for height and distance values? For others, I could, but got confused about it. 
It begs to make an option: "display labels" :)
![ele-labels](https://user-images.githubusercontent.com/534853/148625405-1ae0742f-31c6-491f-9b4d-cc629ee41e71.png)

2. I really liked the timeline, but my users would like to see this data also in a pop-up window on mouse hover, and not just as a timeline. Can you tell me where to look for me to implement this?

**Comment by Raruto** [comment]
Hi velocat,

> 1. How to add labels for height and distance values? For others, I could, but got confused about it.
It begs to make an option: "display labels" :)

Please also show me the code you already use to prepend those other labels.

> 2. I really liked the timeline, but my users would like to see this data also in a pop-up window on mouse hover, and not just as a timeline. Can you tell me where to look for me to implement this?

This should be the code responsible for adding the **timeline** axis (total time duration):

https://github.com/Raruto/leaflet-elevation/blob/ac803fd023718e097a71f5121501a6a5043946d2/src/time.js#L38-L62

and this the code responsible for adding the single **timestamp** entry inside the chart tooltip:

https://github.com/Raruto/leaflet-elevation/blob/ac803fd023718e097a71f5121501a6a5043946d2/src/time.js#L105-L108

Feel free to submit a proposal pull request if you will be able to produce some useful code for others.

_Have a nice day,
Raruto_

**Comment by velocat** [comment]
Create Pull: https://github.com/Raruto/leaflet-elevation/pull/169
:smiley:
