### ISSUE TITLE
Reversed coordinates in _addGeoJSONData

### ISSUE THREAD

**Issue by jibeetz** [Raruto/leaflet-elevation#17]
Hi,

It might be related to my data and customisations but in `leaflet-elevation.js`, line `357`, I had to change

` this._addPoint(coords[i][1], coords[i][0], coords[i][2]);`

to

`this._addPoint(coords[i][0], coords[i][1], coords[i][2]);`

I can fork and make a PR if you want, but as I saw that the project evolved in the past few days I thought it would be faster to tell you.

Best, thanks for the plugin,

**Comment by Raruto** [comment]
In version **0.6.1** i've added the **reverseCoords** option, does it work well?

_Have a nice day,
Raruto_

**Comment by jibeetz** [comment]
I just tried with the new version, it works well.
Thank you,
