### ISSUE TITLE
Stop propagation for mousewheel

### ISSUE THREAD

**Issue by velocat** [Raruto/leaflet-elevation#175]
If you hold down CTRL and rotate the mouse wheel, for example, to zoom the chart, then when the extreme values, maximum or minimum are reached, the event is transmitted to the map itself.  (This is when the options detached: false)
We need to stop Propagation events on map. 

This is especially noticeable if, for example, a rotation is attached to the map:
![Propagation](https://user-images.githubusercontent.com/534853/152696204-df6dbd9d-9ba6-40c9-978e-1d42f058c520.gif)

My Hook:

```js
Elevation.addInitHook(function () {
	this.on("elechart_init", function () {
              this.on(this._container, 'wheel', function(e){L.DomEvent.stop(e)});
        });
});
```

**Comment by Raruto** [comment]
Hi velocat,

maybe you are working on a previous version of the library, in latest versions that behavior it has been replaced by the `shift+scroll` (has you suggested some time ago... 😄)

_Raruto_

**Comment by velocat** [comment]
Oh, of course, I just misspelled, of course `Shift `
:smiley:

**Comment by velocat** [comment]
I won't open a separate request, but I'll just tell you here that I've been looking for a long time why I didn't display a line on the graph, and I realized that the "tooltip" class is quite popular and used by different frameworks. 
For example, bootstrap overlapped it for me, and it was always invisible.  
I propose to replace it with a more original one, I made a "tooltip-ele" for myself :smile: 

https://github.com/Raruto/leaflet-elevation/blob/3f7f4383248befd5fbec053c2883148435b89664/src/components.js#L440

**Comment by Raruto** [comment]
I understand that there can be unexpected collisions, but I would prefer to maintain a certain readability of the code (other classes would also need a prefix and everything would inevitably become heavier), considering also that the encountered problem can be easily solved as follows:

```css
.elevation-control .tooltip {
  opacity: 1;
}
```

I just wouldn't go crazy looking for the perfect "namespace"

_Greetings,
Raruto_

**Comment by velocat** [comment]
I understand what you're suggesting, but in this case, with empty data, it will be displayed like this: 
![Снимок55](https://user-images.githubusercontent.com/534853/153056795-ae6c1e1c-46d6-4503-b91d-b45e32f9c317.JPG)
It's not critical, but it's not very nice either.

**Comment by Raruto** [comment]
you just need a little imagination:

```css
.elevation-control .tooltip {
  opacity: 1;
}

.elevation-control .mouse-focus-line[x1="0"],
.elevation-control .mouse-focus-line[x1="0"] ~ * {
  display: none;
}
```

**Comment by velocat** [comment]
This would solve this issue wonderfully, but unfortunately, the selection on the diagram does not work with such css.

**Comment by Raruto** [comment]
Could you provide a demo? (the "brush" is on another svg group, maybe there is some other rule that cause this conflict)
