### ISSUE TITLE
Weird lazyload logic

### ISSUE THREAD

**Issue by dordnung** [Raruto/leaflet-elevation#177]
### Subject of the issue
In **control.js** you skip lazy load, for example D3 https://github.com/Raruto/leaflet-elevation/blob/master/src/control.js#L29, if it's already loaded OR lazyLoadJS is ENABLED (but should be disabled).

But also the lazy load function itself is weird as it skips when the skip parameter is false...: https://github.com/Raruto/leaflet-elevation/blob/master/src/utils.js#L265

And when loading geometryutil you check if L.GeometryUtil is a function, but it is an object...:
https://github.com/Raruto/leaflet-elevation/blob/master/src/control.js#L1057

### Your environment
* leaflet-elevation: 1.7.3
* leaflet: 1.7.1>

**Comment by Raruto** [comment]
Hi david,

maybe something went wrong during some code refactoring? 🤷
Anyway do not hesitate to make a pull request (I accept them very gladly).

_Have a nice day,
Raruto_

**Comment by Raruto** [comment]
Version should **1.8.0** handle this in a more predictable and readable way, eg:

https://github.com/Raruto/leaflet-elevation/blob/7955321b69810b57d8e7b29838594b45f239add2/src/control.js#L25-L35

_Raruto_

**Comment by dordnung** [comment]
Great, thank you 👍
