### ISSUE TITLE
Override Bootstrap theme styles

### ISSUE THREAD

**Issue by wpysz** [Raruto/leaflet-elevation#179]
### leaflet-elevation and Bootstrap

When moving the mouse on the height graph, a black, vertical line and a black rectangle with the y: (height) and x: (distance) coordinates are moving following the cursor: https://ciekawe.tematy.net/testy/raruto/blackbox/blackbox.jpg

In the example below, you can see it in a real running script: https://ciekawe.tematy.net/testy/raruto/blackbox/bootstrap-no.html

If I apply the same script on the page where I am using Bootstrap, the rectangle with height and distance does not appear:
https://ciekawe.tematy.net/testy/raruto/blackbox/bootstrap.html

This phenomenon also occurs when we do not use any Bootstrap elements, but only load the bootstrap.min.css file in the <head> section

**Comment by velocat** [comment]
https://github.com/Raruto/leaflet-elevation/issues/175#issuecomment-1032732655
