### ISSUE TITLE
Start and End Icon ?

### ISSUE THREAD

**Issue by jfdemeyre** [Raruto/leaflet-elevation#18]
Hi,

This is not really an issue, but do you know how I can add a Start and End Icon on the map using your plugin ? On a map based on [this example](https://raruto.github.io/examples/leaflet-elevation/leaflet-elevation.html) 

Thanks for your awesome job !

JF

**Comment by Raruto** [comment]
Basically you can do something like this:
```js
var controlElevation = L.control.elevation({

  // leaflet-elevation.js options (ver. 0.6.2)

  theme: "lightblue-theme",
  detached: true,
  collapsed: false,

  // leaflet-gpx.js options (ver. 1.4.0)

  gpxOptions: {
    marker_options: {
        startIconUrl: 'pin-icon-start.png',
        endIconUrl: 'pin-icon-end.png',
        shadowUrl: 'pin-shadow.png'
    }
  }

});
```

**Further info and details:**

- leaflet-gpx: [marker icons](https://github.com/mpetazzoni/leaflet-gpx#about-marker-icons)
- Leaflet: [L.icon](https://leafletjs.com/reference.html#icon)
- Leaflet: [L.divIcon](https://leafletjs.com/reference.html#divicon)
- MrMufflon: [gpx example](http://mrmufflon.github.io/Leaflet.Elevation/example/example_gpx.html)
- Raruto: [waypoint icons](https://raruto.github.io/examples/leaflet-elevation/leaflet-elevation_gpx-waypoints.html)

**Comment by jfdemeyre** [comment]
Thanks it works with the latest version of your work. 
But the summary is not working in the same way.
Do you have a summary with elevation gain, loss and if possible time and speed ?

**Comment by Raruto** [comment]
> the summary is not working in the same way.

Have you tried setting the following option?
```js
summary: 'inline',  // Available values: "inline" || "multiline" || false.
```

> do you have a summary with elevation gain, loss and if possible time and speed ?

Currently no, but you can still build your custom one:

```js
map.on('eledata_loaded', function(e) {
   var q = document.querySelector.bind(document);
   var track = e.track_info;
   var layer = e.layer;

   // Default summary info
   q('.totlen .summaryvalue').innerHTML = track.distance.toFixed(2) + " km";
   q('.maxele .summaryvalue').innerHTML = track.elevation_max.toFixed(2) + " m";
   q('.minele .summaryvalue').innerHTML = track.elevation_min.toFixed(2) + " m";

  // Advanced summary info
  // layer.get_elevation_gain() 
  // layer.get_elevation_loss() 
  // layer.get_total_time();
  // layer.get_total_speed();

});
```
Or can you also try submitting a pull request with all desired changes...

**Further info and details:**
- leaflet-gpx: [available functions](https://github.com/mpetazzoni/leaflet-gpx#available-functions)
- MPettazoni: [gpx example](http://mpetazzoni.github.io/leaflet-gpx/)
- Raruto: [custom summary](https://raruto.github.io/examples/leaflet-elevation/leaflet-elevation.html)

**Comment by jfdemeyre** [comment]
OK. Thanks, I'll have a look. For now, I add an another summary with desired data from my sql database.

**Comment by cesar2** [comment]
Hi @Raruto , first of all, thank you very much for your work.

I tried to add the marker startIconUrl but I get exceptions. I am using leaflet-gpx 1.5.0. Here is my code:
```
var elevation_options = {
      theme: "lightblue-theme",
      detached: true,
      collapsed: false,
      gpxOptions: {
        marker_options: {
        startIconUrl: '../../../../assets/pin-icon-start.png'
        }
      },
    };

    var map = L.map('map', {
        center: [39.73, -104.99],
        zoom: 10,
	resizerControl: true,
        layers: []
    });

    var controlElevation = L.control.elevation(elevation_options).addTo(map);

    this.post$.subscribe( post => {
      controlElevation.load(post.gpxPost);
    });

    L.control.zoom();
```

The exception I am getting:
![image](https://user-images.githubusercontent.com/5868552/99913981-fc396c80-2cfa-11eb-9ff6-1d5374b14283.png)


If I comment the startIconUrl, it works fine:
![image](https://user-images.githubusercontent.com/5868552/99913918-96e57b80-2cfa-11eb-8d3e-6e8ae350c1dc.png)


Here is the file:
![image](https://user-images.githubusercontent.com/5868552/99914019-1f641c00-2cfb-11eb-8fa4-9a1a9f639cd5.png)

**Comment by Raruto** [comment]
Hi Cèsar,
perhaps i think it would be better to open a new issue...

If you are loading a gpx file, the `waypoint_added` event is fired here:

https://github.com/Raruto/leaflet-elevation/blob/4a0364c6deadb056266c84aacf6cd266995a8c02/src/utils.js#L136

otherwise, with a geojson file, here:

https://github.com/Raruto/leaflet-elevation/blob/4a0364c6deadb056266c84aacf6cd266995a8c02/src/utils.js#L101

**PS** If you could also provide a simple minimal demo showing your problem you would do me a favor...

_Happy days,
Raruto_

**Comment by cesar2** [comment]
Here there is an example with [one of your example codes](https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation.html) @Raruto :

```
<!DOCTYPE html>
<html>

<head>
	<title>leaflet-elevation.js</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
	<style>
		html,
		body,
		.leaflet-map,
		.elevation-div {
			height: 100%;
			width: 100%;
			padding: 0px;
			margin: 0px;
		}

		.leaflet-map {
			height: 55%;
			max-height: 100vh;
		}

		.elevation-div {
			height: 25%;
			font: 12px/1.5 "Helvetica Neue", Arial, Helvetica, sans-serif;
		}
	</style>

	<!-- leaflet-ui -->
	<script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"></script>
	<script src="https://unpkg.com/leaflet-ui@0.4.6/dist/leaflet-ui.js"></script>

	<!-- leaflet-elevation -->
	<link rel="stylesheet" href="https://unpkg.com/@raruto/leaflet-elevation@1.4.0/dist/leaflet-elevation.min.css" />
	<script src="https://unpkg.com/@raruto/leaflet-elevation@1.4.0/dist/leaflet-elevation.min.js"></script>

</head>

<body>

	<div id="map" class="leaflet-map"></div>

	<script>
		var map = L.map('map', opts.map);

		var controlElevation = L.control.elevation({
		  // leaflet-elevation.js options (ver. 0.6.2)

		  theme: "lightblue-theme",
		  detached: true,
		  collapsed: false,

		  // leaflet-gpx.js options (ver. 1.4.0)

		  gpxOptions: {
			marker_options: {
				startIconUrl: 'pin-icon-start.png',
				endIconUrl: 'pin-icon-end.png',
				shadowUrl: 'pin-shadow.png'
			}
		  }

		});
		var controlLayer = L.control.layers(null, null, opts.layersControl.options);

		controlElevation.addTo(map);
		controlLayer.addTo(map);

		controlElevation.on('eledata_loaded', function(e) {
			controlLayer.addOverlay(e.layer, e.name);
		});

		controlElevation.load(opts.elevationControl.url);
	</script>

	<a href="https://github.com/Raruto/leaflet-elevation" class="view-on-github" style="position: fixed;bottom: 30px;left: calc(50% - 81px);z-index: 9999;"> <img alt="View on Github" src="https://raruto.github.io/img/view-on-github.png" title="View on Github"
		 width="163"> </a>

</body>

</html>

```

I place the  icons on the same folder where the .html is. And I got the exception:
![image](https://user-images.githubusercontent.com/5868552/100152678-583ef500-2ea3-11eb-987f-27bb1e35fb32.png)

**Comment by Raruto** [comment]
Hi Cèsar,
take a try with latest release **[1.5.0](https://www.npmjs.com/package/@raruto/leaflet-elevation/v/1.5.0)**

_Happy thoughts,
Raruto_

**Comment by cesar2** [comment]
It's working now. Thanks a million @Raruto
