### ISSUE TITLE
Max BPM in stats shows actually minimum heart rate

### ISSUE THREAD

**Issue by mainzelM** [Raruto/leaflet-elevation#185]
### Subject of the issue
First of all, thanks a lot for the new version. Within a couple of minutes, I was able to add custom support for power (W). While doing so, I ran across a small issue:

The display of the maximum heart rate in the stats section is wrong: it shows the minimum value instead of the maximum

### Your environment
* leaflet-elevation: 2.1

### Steps to reproduce
Check the stats section in https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_extended-ui.html: Max BPM is 112, which is identical to Min BPM but far below Avg BPM.

The reason is that in 
https://github.com/Raruto/leaflet-elevation/blob/2bbaa3dd271087e77685dc018730bf7769f6514b/examples/leaflet-elevation_extended-ui.html#L88

but also in

https://github.com/Raruto/leaflet-elevation/blob/2bbaa3dd271087e77685dc018730bf7769f6514b/src/handlers/heart.js#L43

heart_**min** instead of heart_**max** is used as the source of the Max BPM value

**Comment by Raruto** [comment]
Hi mainzeIM,

> First of all, thanks a lot for the new version. Within a couple of minutes, I was able to add custom support for power (W). 

If you think it might be useful to others too, don't worry about submitting it among the default ones 😉

https://github.com/Raruto/leaflet-elevation/blob/2bbaa3dd271087e77685dc018730bf7769f6514b/src/handlers/

> The reason is that heart**_min** instead of heart**_max** is used as the source of the Max BPM value

You are right, can you send a pull request that solves this?

_Thank you,
Raruto_
