### ISSUE TITLE
`import.meta` is undefined within Vue.js application

### ISSUE THREAD

**Issue by isuke01** [Raruto/leaflet-elevation#204]
### Subject of the issue
Hi, not really an issue, more like help wanted.
I'm trying to import the script into my VUE 3 app. 
I'm doing 
`import * as elevation from '@raruto/leaflet-elevation';`

I'm not even doing any callbacks nor nothing to the element; 
But it produce the error:
```js
control.js:10 Uncaught TypeError: Cannot read properties of undefined (reading 'split')
    at control.js:10:110
```

### Your environment
* leaflet-elevation: 2.2.0
* leaflet: 1.8.0
* VUE 3 + Vite
* browser: Chrome
* operating system: Desktop (OSX)

Thanks for any hint how to import correctly the script :)

**Comment by Raruto** [comment]
Hi Lukasz,
the offending line should be the following: https://github.com/Raruto/leaflet-elevation/blob/37372a5dcf0a68b9d520b1195a488fbd1f140869/src/control.js#L9-L10

I don't know if there are any support utilities for vue, but take a look at [mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import.meta) documentation to understand what it is for.

_Have a nice day,
Raruto_

**Comment by Raruto** [comment]
I close it here because it seems to be simply an issue related to how to use "Vite": https://github.com/vitejs/vite/issues/7287#issuecomment-1066054251

_If not let me know,
Raruto_
