### ISSUE TITLE
Feature Request - Temperature

### ISSUE THREAD

**Issue by sjdellis** [Raruto/leaflet-elevation#205]
Hi there

Great project! Would it be possible to add Temperature ?  My GPX looks like this.

`<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="GPS Track Editor" xmlns="http://www.topografix.com/GPX/1/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:gte="http://www.gpstrackeditor.com/xmlschemas/General/1" xmlns:gpxtpx="http://www.garmin.com/xmlschemas/TrackPointExtension/v1" xmlns:gpxx="http://www.garmin.com/xmlschemas/GpxExtensions/v3" targetNamespace="http://www.topografix.com/GPX/1/1" elementFormDefault="qualified" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
<metadata>
	<name>name</name>
</metadata>
<trk>
	<name>Day 1</name>
	<trkseg>
		<trkpt lat="40.703080" lon="-74.053719">
			<ele>2.52</ele>
			<time>2018-08-01T16:05:00Z</time>
			<extensions>
				<gpxtpx:TrackPointExtension>
					<gpxtpx:atemp>24.6</gpxtpx:atemp>
				</gpxtpx:TrackPointExtension>
			</extensions>
		</trkpt>`....

Thanks

**Comment by Raruto** [comment]
Hi simi.d,

I think so, try to take a look at the source code of [leaflet-elevation_extended-ui.html](https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_extended-ui.html) example to understand how to proceed.
If you need some inspiration, here you can see how the other default handlers of this library actually work: [src/handlers](https://github.com/Raruto/leaflet-elevation/blob/3ee745d71ed172979b7bfe0ff52f7c63214d3c04/src/handlers)

As usual, pull requests are always welcome.

_Have a nice day,
Raruto_

**Comment by sjdellis** [comment]
Thank you Raruto. Those a fantastic examples. I'm not really a developer but I've managed to get the temperature to work. I'm not familiar with git/github - that is next on the list of things to learn :) 

Attached is my temperature handler if it is any use to you. One thing I cannot figure out is how to get the average to ignore null data. It seems to set it to 0. The chart also draws a line at 0 when there is null data. I'll keep digging unless you can point me in a direction.

[temperature.zip](https://github.com/Raruto/leaflet-elevation/files/9156967/temperature.zip)
