### ISSUE TITLE
No more elevation icon

### ISSUE THREAD

**Issue by chaosad2802** [Raruto/leaflet-elevation#209]
### Subject of the issue
Describe your issue here.

### Your environment
* leaflet-elevation: version 2.2.6
* browser: all
* operating system: all
* link to your project: https://trackserver.mymaps.fr/

I can't see no more elevation icon (bottom left), just the square.
I can't find why.
Does anybody met this problem ?

**Comment by hupe13** [comment]
Provide the icon at this [url](https://trackserver.mymaps.fr/images/elevation.svg). Take this and maybe others from [here](https://github.com/Raruto/leaflet-elevation/tree/master/images).

**Comment by chaosad2802** [comment]
Thanks you for your answer.
Well, this file (elevation.svg) seems to have a problem, I can't download it :  _Unable to render code block_.
No problem with other files.

**Comment by hupe13** [comment]
The elevation.svg under your [url](https://trackserver.mymaps.fr/images/elevation.svg) isn't the same as [elevation.svg](https://raw.githubusercontent.com/Raruto/leaflet-elevation/master/images/elevation.svg).

**Comment by chaosad2802** [comment]
Yes, I know, I just tested with another svg file, cause I can't download original on this page : https://github.com/Raruto/leaflet-elevation/blob/master/images/elevation.svg
Now, it's done with your last link (I copied / pasted the code).
Thanksfor your help.
