### ISSUE TITLE
Fixed height for detached elevation chart

### ISSUE THREAD

**Issue by tomyv65** [Raruto/leaflet-elevation#212]
Hi,
I am using elevation-leaflet with the option 'detached' for the elevation chart container. The container has a variable height and adjusts itself depending on the screen which can cause problems on mobile devices and besides that bedides that I do not like that. Anyway I would like to assign a fixed height for the elevation chart. How can I achieve that: CSS or elevation_options or ...?!?

http://bike-the-world.net/Daytrips-Training-2022.329.0.html?btwreports%5Bmode%5D=6&btwreports%5BshowUid%5D=47

Thanks for your help,

**Comment by tomyv65** [comment]
[http://localhost:81/Daytrips-Training-2022.329.0.html?btwreports%5Bmode%5D=6&btwreports%5BshowUid%5D=36](url)

**Comment by hupe13** [comment]
There is an undocumented option height, e.g.:

```
elevationControl: {
   url: "https://.....gpx",
   options: {
      ....
      detached: true,
      height: 300,
      ...
```

**Comment by tomyv65** [comment]
Thnaks a lot, just discovered in [options.js](https://github.com/Raruto/leaflet-elevation/blob/master/src/options.js)
