### ISSUE TITLE
Translate legend item labels (small legend switcher)

### ISSUE THREAD

**Issue by hupe13** [Raruto/leaflet-elevation#213]
Version 2.2.6

Hi Raruto,

I translated all strings. But I can't change this one: ![grafik](https://user-images.githubusercontent.com/73023225/191258056-10f150d3-216b-4757-a0ea-98a7ccfc06fe.png)

![grafik](https://user-images.githubusercontent.com/73023225/191256062-d0734689-66a1-4730-89d7-3df6562057f4.png)
No matter whether Altitude, Slope, Speed  or Acceleration appears.

Can you please fix this? Thank you very much.

**Comment by Raruto** [comment]
Hi hupe,

the problem should be near to these lines:

https://github.com/Raruto/leaflet-elevation/blob/2589a937188792eae88c9822a5627845aed2027d/src/components/d3.js#L271

https://github.com/Raruto/leaflet-elevation/blob/46918ce42f27cc438e969407ae0a85bc56801132/src/components/chart.js#L573-L581

To understand how you can make a string translatable you can take look at: [yohanboniface/Leaflet.i18n](https://github.com/yohanboniface/Leaflet.i18n)

_courtesy of [leaflet-ui](https://github.com/Raruto/leaflet-ui/commit/6224b0999c11f7dddaccde947ec9d363fdb72662) >= 0.5.4 😄_

**Comment by hupe13** [comment]
After I found the solution, it's very simple:
```php
label.text(items.length ? L._((items[idx][0].toUpperCase() + items[idx].slice(1))) : '');
```
