### ISSUE TITLE
Animated GPS track polyline

### ISSUE THREAD

**Issue by bard0x** [Raruto/leaflet-elevation#215]
Hi @Raruto ,

sorry for this fake issue but I don't found any refer to contact you privately.

First of all your libraries, especially leaflet-elevation, ROCKS! 

I'm here because I have a question for you: do you have ever developed any kind of leaflet plugin in order to provide the ability to replay GPS tracks along a marker and eventualy a polyline on map?

**Comment by Raruto** [comment]
Hi @bard0x,

> do you have ever developed any kind of leaflet plugin in order to provide the ability to replay GPS tracks along a marker and eventualy a polyline on map?

No, but you can try to integrate it with this other library.

_Have a nice day,
Raruto_
