### ISSUE TITLE
Custom GPS file format

### ISSUE THREAD

**Issue by kb6ooc** [Raruto/leaflet-elevation#217]
Greetings,

I don't suppose there is a way to read a custom GPS file format?

Thanks!

**Comment by Raruto** [comment]
Hi @kb6ooc,

currently this plugin relays on the [tmcw/togeojson](https://github.com/placemark/togeojson) library is used for file parsing.

Below, you can find some information on how to read your own "gpx extensions":

- https://github.com/Raruto/leaflet-elevation/issues/205
- https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_extended-ui.html

_Have a nice day,
Raruto_
