### ISSUE TITLE
Prevent map center change when hovering elevation chart profile

### ISSUE THREAD

**Issue by arverne63** [Raruto/leaflet-elevation#22]
Hello,
I use leaflet-elevation-gpx waypoint icons for the following [example](http://testrandos.free.fr/Raturo/leaflet-elevation_gpx-waypoints.php).
What I would like to do, if possible, is when you hover the cursor over the graph, the point moves over the plot and the map stays stationary.

_Thank you for your help.
Jean Marc_

**Comment by Raruto** [comment]
Have you tried setting `followMarker: false`? (within control elevation options)

**Comment by arverne63** [comment]
Bonsoir,
Rajouter followMarker: false n'a pas d'effet.
`elevationControl: {
				url: "traces/corboeuf.gpx",
				options: {
					theme: "lime-theme",
					collapsed: false,
					detached: true,
					useLeafletMarker: false,
					summary: 'multiline',
					followMarker: false,`
[http://testrandos.free.fr/Raturo/leaflet-elevation_gpx-waypoints.php](url)

**Comment by arverne63** [comment]
Good evening,
the addition of followMarker: false has no effect on the center change of the card.
`elevationControl: {
				url: "traces/corboeuf.gpx",
				options: {
					theme: "lime-theme",
					collapsed: false,
					detached: true,
					useLeafletMarker: false,
					summary: 'multiline',
					followMarker: false,
`                                      . . . . . } }
[http://testrandos.free.fr/Raturo/leaflet-elevation_gpx-waypoints.php](url)

**Comment by Raruto** [comment]
You're probably using an older version of this library, `followPositionMarker: false` should do the job.

**Comment by arverne63** [comment]
Hello,
this works well with followPositionMarker: false
Thank you.
