### ISSUE TITLE
How to load geojson tracks in `L.GpxGroup` library?

### ISSUE THREAD

**Issue by brigghius** [Raruto/leaflet-elevation#225]
### Your environment
* leaflet-elevation: 1.9.6
* leaflet: 1.9.2
* angular: 14
* browser:chrome

hi, I'm developing a multi track map and I'm using the example [here](https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_hoverable-tracks.html) because it's very nice and does what I want.

To load the tracks we use an array of strings pointing to files. How can I make it work on an object present in my ts file?

```ts
track: any = {
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {
                "type": "MultiLineString",
                "coordinates": [
                    [
                        [
                            18.8793834,
                            47.5757454,
                            336.399
                        ],
                        [
                            18.879521,
                            47.5757001,
                            336.243
                        ],
                        [
                            18.879616,
                            47.575628,
                            336.476
                        ],
                        [
                            18.8798517,
                            47.5755253,
                            338.85
                        ],
                        [
                            18.8801746,
                            47.5753281,
                            337.622
                        ],
                        [
                            18.8803667,
                            47.5751841,
                            335.793
                        ],
                        [
                            18.8806468,
                            47.5750652,
                            334.178
                        ]
                    ]
                ]
            },
            "properties": {
                "name": "2013/10/06 - Bronz-barlang, Karády-lak, festékföld égető kemencék",
                "number": 1
            }
        }
    ]
}
```

thanks

**Comment by brigghius** [comment]
@Raruto can u help me?

**Comment by hupe13** [comment]
As I understand it, each track must be in one file. Geojson should be fine. And you must provide the starting points.
But I don't know angular.

**Comment by brigghius** [comment]
> As I understand it, each track must be in one file. Geojson should be fine. And you must provide the starting points. But I don't know angular.

exactly. To load the traces as an array of objects and not as an array of strings pointing to files, I had to put the library locally and modify it like this:

![image](https://user-images.githubusercontent.com/49524691/206221467-7b404e11-1eaf-4d1a-b2e5-9ef252a890e0.png)

Is it possible to dynamically load a new point on a track?

**Comment by Raruto** [comment]
@brigghius it should look something like the following https://github.com/Raruto/leaflet-elevation/pull/228, please test more thoroughly than me (eg. the geojson name) and then let me know if we need to make any changes.

_Have a nice day,
Raruto_

**Comment by brigghius** [comment]
> @brigghius it should look something like the following #228, please test more thoroughly than me (eg. the geojson name) and then let me know if we need to make any changes.
> 
> _Have a nice day, Raruto_

thanks, now works fine. 
I had bypassed the check on the object, but the solution is excellent.
