### ISSUE TITLE
Elevation profile gets cut off at first gpx point that is missing elevation data

### ISSUE THREAD

**Issue by thomas-oderud** [Raruto/leaflet-elevation#227]
### Subject of the issue
Having used this on our site for a long time, an update broke one off the elevation vizualisations.  

### Your environment
* leaflet-elevation: 3.2.2
* leaflet: 3.0.5 (Wordpress Leaflet Map)
* browser: Chrome
* operating system: Windows 11 / Android

https://www.krsultra.no/mizuno-krsultra-60/
using this gpx: https://www.krsultra.no/wp-content/uploads/gpx/KRSUltra_60_2022_v3.gpx

**Comment by hupe13** [comment]
Delete line 1829 of the gpx file, then it should work.
The question would be better addressed in the [support forum](https://wordpress.org/support/plugin/extensions-leaflet-map/).

**Comment by Raruto** [comment]
@thomas-oderud thanks for the report, although:

> - leaflet-elevation: 3.2.2
> - leaflet: 3.0.5

there is no version of either of those libraries yet...

**BTW**, i think this pull request https://github.com/Raruto/leaflet-elevation/pull/219 should also come back to handle the problem in case of malformed gpx file (i.e. on missing altitude data). If I'm not mistaken it should be related to the refactoring done in version 2.x

_Greetings,
Raruto_
