### ISSUE TITLE
elevation graph buggy not properly color filled sometimes 

### ISSUE THREAD

**Issue by flo-schn** [Raruto/leaflet-elevation#237]
### elevation graph buggy not properly color filled sometimes 

please see screenshot:
![Screenshot from 2023-03-23 23-36-18](https://user-images.githubusercontent.com/79014934/227708486-c1f042cb-b69a-4b05-b82c-27b698e9fecc.png)

### Your environment
* leaflet-elevation: 2.2.8
* leaflet: 1.9.3
* browser: Firefox 110.0.1 (64-bit)
* operating system: Ubuntu 22.04.2 LTS
* link to your project: see screenshot above and code below: 

### Steps to reproduce
```html
<head>
<style> html, body, #map, #elevation-div { height: 100%; width: 100%; padding: 0; margin: 0; } #map { height: 500px; } #elevation-div {	height: 25%; font: 12px/1.5 "Helvetica Neue", Arial, Helvetica, sans-serif; } </style>

<link rel="stylesheet" href="https://unpkg.com/@raruto/leaflet-elevation/dist/leaflet-elevation.css" />
<script src="https://unpkg.com/@raruto/leaflet-elevation/dist/leaflet-elevation.js"></script>

<script src='https://api.mapbox.com/mapbox.js/plugins/leaflet-fullscreen/v1.0.1/Leaflet.fullscreen.min.js'></script>
<link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-fullscreen/v1.0.1/leaflet.fullscreen.css' rel='stylesheet' />

</head>
<body>
        <div  id="binder"></div>
</body>
````
```js

var elevation_options = {

    // Default chart colors: theme lime-theme, magenta-theme, ...
    theme: "lightblue-theme",

    // Chart container outside/inside map container
    detached: true,

    // if (detached), the elevation chart container
    elevationDiv: "#elevation-div",

    // if (!detached) autohide chart profile on chart mouseleave
    autohide: false,

    // if (!detached) initial state of chart profile control
    collapsed: false,
    
    // if (!detached) control position on one of map corners
    position: "bottomright",
    
    // Toggle close icon visibility
    closeBtn: true,

    // Autoupdate map center on chart mouseover.
    followMarker: true,

    // Autoupdate map bounds on chart update.
    autofitBounds: true,

    // Chart distance/elevation units.
    imperial: false,

    // [Lat, Long] vs [Long, Lat] points. (leaflet default: [Lat, Long])
    reverseCoords: false,

    // Acceleration chart profile: true || "summary" || "disabled" || false
    acceleration: false,

    // Slope chart profile: true || "summary" || "disabled" || false
    slope: false,

    // Speed chart profile: true || "summary" || "disabled" || false
    speed: false,

    // Altitude chart profile: true || "summary" || "disabled" || false
    altitude: true,

    // Display time info: true || "summary" || false
    time: false,

    // Display distance info: true || "summary" || false
    distance: true,

    // Summary track info style: "inline" || "multiline" || false
    summary: 'inline',

    // Download link: "link" || false || "modal"
    downloadLink: false,

    // Toggle chart ruler filter
    ruler: true,

    // Toggle chart legend filter
    legend: true,

    // Toggle "leaflet-almostover" integration
    almostOver: true,

    // Toggle "leaflet-distance-markers" integration
    distanceMarkers: false,
    
    // Toggle "leaflet-hotline" integration
    hotline: true,

    // Display track datetimes: true || false
    timestamps: false,

    // Display track waypoints: true || "markers" || "dots" || false
    waypoints: true,

    // Toggle custom waypoint icons: true || { associative array of <sym> tags } || false
    wptIcons: {
      '': L.divIcon({
        className: 'elevation-waypoint-marker',
        html: '<i class="elevation-waypoint-icon"></i>',
        iconSize: [20, 20],
        iconAnchor: [8, 20],
      }),
    },

    // Toggle waypoint labels: true || "markers" || "dots" || false
    wptLabels: "markers",

    // Render chart profiles as Canvas or SVG Paths
    preferCanvas: true,

  };

    var binder = window.leafletMap = L.map(binder).setView([51.505, -0.09], 2);
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: 'Map data &copy; <a href="http://www.osm.org">OpenStreetMap</a>'
    }).addTo(binder);
    L.control.scale().addTo(binder);
    new L.Control.Fullscreen().addTo(binder);
    var controlElevation = L.control.elevation(elevation_options).addTo(binder);
    controlElevation.load(gpx_file);
```

### Expected behaviour
a fully filled with color elevation graph, like this:
![Screenshot from 2023-03-25 10-37-41](https://user-images.githubusercontent.com/79014934/227709406-80ebe162-aac7-4357-976f-37c21799b023.png)

### Actual behaviour
see attached screenshot. looks buggy, and is a not fully filled with color elevation graph. happens about 1/3 in page loads

**Comment by flo-schn** [comment]
is there some kind of size limit for the gpx files? not sure but, but it seems to be correlating with larger gpx files 10k track points plus.

**Comment by flo-schn** [comment]
fair enough. I used github to deploy a fully working example:

- result: https://flo-schn.github.io/reproducing-issue-for-leaflet-elevation/
- code: https://github.com/flo-schn/reproducing-issue-for-leaflet-elevation

the example illustrates both issues, this one and #238 
regarding #237, sometimes it works perfectly and all is properly color filled, then a refresh of the page usually helps to display buggy not properly color filled. 

here's a screenshot, just in case:
![Screenshot from 2023-03-29 10-41-58](https://user-images.githubusercontent.com/79014934/228477793-ada60f87-1a9a-4afb-8f70-48978254c4e0.png)



hope that helps, flo

**Comment by hupe13** [comment]
I can confirm it in my environment.

**Comment by Raruto** [comment]
Have you tried applying this suggestion? https://github.com/Raruto/leaflet-elevation/issues/176#issuecomment-1032763314

**Comment by hupe13** [comment]
https://github.com/Raruto/leaflet-elevation/issues/176#issuecomment-1032763314 works.

**Comment by flo-schn** [comment]
just applied https://github.com/Raruto/leaflet-elevation/issues/176#issuecomment-1032763314 and updated my working example:


- updated result: https://flo-schn.github.io/reproducing-issue-for-leaflet-elevation/
- updated code: https://github.com/flo-schn/reproducing-issue-for-leaflet-elevation

and **yes**, it solves this issue, thus displaying the elevation graph properly color filled.

but unfortunately, it does not solve https://github.com/Raruto/leaflet-elevation/issues/238 reducing the height of the elevation graph when multiple maps and elevation-divs are displayed on one page.  see screenshot:

![image](https://user-images.githubusercontent.com/79014934/228791628-7b502ac7-7d29-4517-a45c-4ad02f7ab2d0.png)
best, flo

**Comment by flo-schn** [comment]
Hi, just did:
https://github.com/flo-schn/reproducing-issue-for-leaflet-elevation/blob/c121d29ea4bec6ad8fa31e0530961a96ef9ff4e6/map-builder.js#L96

if u check the again updated result: https://flo-schn.github.io/reproducing-issue-for-leaflet-elevation/

or see the screenshot:
![image](https://user-images.githubusercontent.com/79014934/228815915-5b52c9d4-3b0f-4795-a3c3-506b01601de8.png)

i guess it somehow works by resizing the graph to a size that is readable again. however, there is still this rather large unused empty space at the bottom of the elevation-div container. and the summary statistics usually just below the elevation-div container have disappeared.

**Comment by FabianSchmick** [comment]
Another solution for me was to hide the specific mask-element, like:

```css
.elevation-control .area mask {
    display: none;
}
```
