### ISSUE TITLE
Wrong gpx track profile length

### ISSUE THREAD

**Issue by rahan34** [Raruto/leaflet-elevation#24]
Hi Raruto,
Thanks for your great work!
I would like to ask you a question about an issue I have when I import this [GPX file](https://leprincedesaintgilles.com/GPS/GPX/tracedetrail_52179.gpx):

It is a loop of **49km**, you can verify it with several tools:

![visugpx](https://leprincedesaintgilles.com/GPS/GPX/visugpx.jpg)

But when I import this file into leaflet-elevation using your [example here](https://raruto.github.io/examples/leaflet-elevation/leaflet-elevation_upload-gpx.html) I obtain a **77km** track.

![elevation](https://leprincedesaintgilles.com/GPS/GPX/elevation.jpg)

It looks like there is a little problem...

_Thanks for your help_

**Comment by Raruto** [comment]
There is a problem with your [GPX file](https://leprincedesaintgilles.com/GPS/GPX/tracedetrail_52179.gpx) (ie. missing elevation data for many track points).

While waiting for the next release, you can solve by **adding missing elevation data** through this [online tool](https://www.gpsvisualizer.com/elevation).

_Regards,
Raruto_

**Comment by rahan34** [comment]
Got it, thanks. It means that all the tools I have used with this file include a correction script that adds elevation to waypoints.
This is what you plan to do with the next version or should I ask users to check their files before uploader?

Cheers

**Comment by Raruto** [comment]
> It means that all the tools I have used with this file include a correction script that adds elevation to waypoints?

In order to calculate the route length no elevation data is required.
The calc made through this plugin is incorrect because it omits all this invalid the points (ie. those with no elevation data associated).

> should I ask users to check their files before uploading?

No, from version **0.7.8** this should be now fixed.
