### ISSUE TITLE
Toggle with a button the gpxGroup legend

### ISSUE THREAD

**Issue by haldo98** [Raruto/leaflet-elevation#243]
Hi

is there a way to toggle with a button the legend (true/false) in the gpxGroup  ?

**Comment by Raruto** [comment]
If you are referring to this library:

https://github.com/Raruto/leaflet-elevation/blob/868179234d8e9b8f7beaea57d0e34d8bd79a2622/libs/leaflet-gpxgroup.js#L1-L341

I don't think out of the box (but I don't know, it's code that I don't read every day...), but with some custom JS you can do just about anything.

👋 Raruto

**Comment by haldo98** [comment]
I found that setting to true the collapsed option pretty much solved my problem.

I have a page with 117 tracks and the list of the track was covering much of the space

```
     legend_options: { 
       position: "topright", 
       collapsed: false, 
```

Thank You
