### ISSUE TITLE
Arrows on track always shows "right" (90°), not track direction

### ISSUE THREAD

**Issue by chaosad2802** [Raruto/leaflet-elevation#244]
Hi,
Arrows on track always shows "right" (90°), not track direction.
I really don't understnd why.
Have a look here for example : https://mymaps.fr/les-rives-de-saint-agnan-et-la-vallee-du-serein/
Thanks !

**Comment by hupe13** [comment]
I see, you are using [Extensions for Leaflet Map](https://wordpress.org/plugins/extensions-leaflet-map/). Should I provide this option?

**Comment by chaosad2802** [comment]
Raruto : Thanks for your answer. But I'm not sure to know how to do this on my website.
So, Hupe13 (I really love your plugin !), it would be really cool to provide this option !

**Comment by hupe13** [comment]
@chaosad2802 : If you can't wait, you can test the [Github version](https://github.com/hupe13/extensions-leaflet-map-github).

**Comment by chaosad2802** [comment]
Hupe13,
Great!
I would like to test it, but I'm not sure to understand :
"If you install the Github version, you have 2 versions installed. If you delete any version, all settings will be lost. Delete the unused version, if you wish, in other ways, e.g. with sftp or ssh..."

**Comment by Raruto** [comment]
> "If you install the Github version, you have 2 versions installed. If you delete any version, all settings will be lost. Delete the unused version, if you wish, in other ways, e.g. with sftp or ssh..."

I guess he means that you don't have to use the wordpress interface to disable that plugin (otherwise it will trigger a hook which deletes your settings within the WP database). Instead if you work via ftp you should be safe enough (uploading the new plugin into the wp-plugins folder and renaming the old folder into something else to replace the whole code base)

👋 Raruto

**Comment by chaosad2802** [comment]
OK!
Thank you. Let's go! 😁

**Comment by hupe13** [comment]
You are too fast. ;-)
Here is the [documentation](https://leafext.de/en/doku/about/versions/).

**Comment by hupe13** [comment]
I'm sorry, I was assuming knowledge that you can not have. Please download from [here](https://github.com/hupe13/extensions-leaflet-map-github/tags) or [here](https://github.com/hupe13/extensions-leaflet-map-github/archive/refs/heads/main.zip).

**Comment by chaosad2802** [comment]
Perfect !
I uploaded v3.4.1, I thought it was the "latest release" on Github page.
Now, it's perfect with v3.4.2 ! ;-)
Thank you very much !
Have a look here : [updated page](https://mymaps.fr/les-rives-de-saint-agnan-et-la-vallee-du-serein/)

**Comment by Raruto** [comment]
> Have a look here : [updated page](https://mymaps.fr/les-rives-de-saint-agnan-et-la-vallee-du-serein/)

Nice, but to be perfect you are missing the `almostOver` integration ⛏️

**Comment by hupe13** [comment]
To do.

**Comment by hupe13** [comment]
Version 3.4.2 released.

**Comment by chaosad2802** [comment]
Updated !
Thanks for your job !
