### ISSUE TITLE
How to show `direction` arrows on track without `distance` markers?

### ISSUE THREAD

**Issue by hupe13** [Raruto/leaflet-elevation#245]
(https://github.com/Raruto/leaflet-elevation/issues/244) The arrows on the track are really nice. Is it possible to show them without distanceMarkers?

Thank you very much.

**Comment by Raruto** [comment]
Hi @hupe13,

if i'm not mistaken, these should be the useful options:

https://github.com/Raruto/leaflet-elevation/blob/868179234d8e9b8f7beaea57d0e34d8bd79a2622/libs/leaflet-distance-marker.js#L125-L126

👋 Raruto

**Comment by hupe13** [comment]
Hi Raruto,
thank you very much. It works!
