### ISSUE TITLE
`track.get_name`  is not a function within `"selection_changed"` event (ref: leaflet-gpxgroup.js)

### ISSUE THREAD

**Issue by haldo98** [Raruto/leaflet-elevation#247]
I tried to implement #54 

```js
routes.on('selection_changed', function(e) {
  var q = document.querySelector.bind(document);
  var track = this.getSelection(); // <-- retrieve current gpx layer

  q('.download > a').href = 'data:application/gpx+xml;charset=utf-8,' + encodeURIComponent(track._gpx);
  q('.download > a').download = track.get_name() + ".gpx"; // fileName
});
```

but throws error

 `track.get_name is not a function`
 

am I missing something?

**Comment by Raruto** [comment]
Hi @haldo98,

please also provide a public example showing everyone the bug (a [jsfiddle](https://jsfiddle.net/) or similar so that anyone might try to replicate it in the near future).

Maybe the solution to this issue is quite simple, but the time others can spend building a demo similar to your situation is somewhat limited..

👋 Raruto

**Comment by haldo98** [comment]
https://www.tadini.it/gpx/lombardia_e.html


here is the example page

**Comment by Raruto** [comment]
At some point in the past the [leaflet-gpx](https://github.com/mpetazzoni/leaflet-gpx) dependency it was replaced with the [togeojson](https://github.com/tmcw/togeojson) library.


So, taking a quick look at the following rows:

https://github.com/Raruto/leaflet-elevation/blob/868179234d8e9b8f7beaea57d0e34d8bd79a2622/libs/leaflet-gpxgroup.js#L183-L189

I think it that now should be something like this:

```js
q('.download > a').download = track.options.name + ".gpx"; // fileName
```

👋 Raruto

**Comment by haldo98** [comment]
right!!

Thank You
