### ISSUE TITLE
Map automatically moves after clicking on markers when `rotate: true`

### ISSUE THREAD

**Issue by hupe13** [Raruto/leaflet-elevation#250]
Hi Raruto,

I don't know, if this is an issue for leaflet-elevation or leaflet-rotate. But it works in your examples, so I think, it may be an option to set or to code.
See at my [example](https://leafext.de/wordpress/popuprotate/) (actual WordPress Version): If you click on a marker, the map moves. 
I have already corrected some things, but the effect only [disappears](https://leafext.de/develop/popuprotate/) if I comment out the function `panInside` in [leaflet-rotate](https://github.com/Raruto/leaflet-rotate/blob/c6d90d2c02a1b21145af868cbb71f36d751ba0de/dist/leaflet-rotate-src.js#L981-L1011).

How do I make it work? Thank you very much.

**Comment by Raruto** [comment]
Hi @hupe13,

> I have already corrected some things, but the effect only [disappears](https://leafext.de/develop/popuprotate/) if I comment out the function panInside in [leaflet-rotate](https://github.com/Raruto/leaflet-rotate/blob/c6d90d2c02a1b21145af868cbb71f36d751ba0de/dist/leaflet-rotate-src.js#L981-L1011).

From what I aware that issue should appear starting from leaflet **v1.9.x**

In the comment above the [`L.Map::panInside()`](https://github.com/Raruto/leaflet-rotate/blob/c6d90d2c02a1b21145af868cbb71f36d751ba0de/dist/leaflet-rotate-src.js#L968-L1011) function there is also a link that explains this situation in detail:

```js
/**
 * Pans the map the minimum amount to make the `latlng` visible. Use
 * padding options to fit the display to more restricted bounds.
 * If `latlng` is already within the (optionally padded) display bounds,
 * the map will not be panned.
 * 
 * @see https://github.com/Raruto/leaflet-rotate/issues/18
 * 
 * @param {L.LatLng} latlng coordinates
 * @param {Object} [options={}] padding options
 * 
 * @returns {L.Map} current map instance
 */
panInside(latlng, options) {

...
```

I thought I found patch for this bug, but as you can see right now there is still another open issue about it: https://github.com/Raruto/leaflet-rotate/issues/28

I wouldn't like recommend it, but if you set [`autoPanOnFocus: false`](https://leafletjs.com/reference.html#marker-autopanonfocus) the bug should never show up (this is the new accessibility feature added by leaflet **v1.9.x** that generates tis bug).

The recommended way, would be to start approaching and fixing some of these bugs would be through writing some automated tests (maintaining all that code through manual testing is starting to get quite hard to manage..).

**FYI**, in the future, if you want to do some visual tests within the map, you can also include this debug utility:

```html
<!-- Leaflet-Rotate -->
<script src="https://unpkg.com/leaflet-rotate@0.2.6/dist/leaflet-rotate-src.js"></script>

<!-- include some miscellaneous -->
<script src="https://unpkg.com/leaflet-rotate@0.2.6/misc/route.js"></script>
<script src="https://unpkg.com/leaflet-rotate@0.2.6/misc/places.js"></script>
<script src="https://unpkg.com/leaflet-rotate@0.2.6/misc/loremIpsum.js"></script>
<script src="https://unpkg.com/leaflet-rotate@0.2.6/lib/debug.js"></script>
```

```js
// Initialize map
const map = L.map(...);

// Display some debug info
L.Rotate.debug(map);
```

Although it's a quite rudimentary testing utility.

As you can see, as for this library, in here I've started to code some [`*.spec.js`](https://github.com/search?q=repo%3ARaruto%2Fleaflet-elevation+spec.js&type=code) file, although I don't know how effective they can be..

👋 Raruto

**Comment by hupe13** [comment]
I will leave the lines commented out as a solution for me. I only want the direction arrows on the path. For fixing I do not have the knowledge.

Thank you very much.

**Comment by Raruto** [comment]
> I will leave the lines commented out as a solution for me.

We could probably place the following check at the beginning of that function, but as I said then it's all a matter of writing some tests..


```js
panInside(latlng, options) {

  if (!this._rotate || Math.abs(this._bearing).toFixed(1) < 0.1) {
    return mapProto.panInside.apply(this, arguments);
  }

  ...

```

**Comment by Raruto** [comment]
**leaflet-rotate@v0.2.7** should take care of this https://github.com/Raruto/leaflet-elevation/issues/250#issuecomment-1522841095 (so you shouldn't need keep your patched version)

**Comment by hupe13** [comment]
It works, thank you very much.
