### ISSUE TITLE
Displaying km distance markers on the GPX path

### ISSUE THREAD

**Issue by rahan34** [Raruto/leaflet-elevation#26]
Hi Raruto,
In your nice [example](https://raruto.github.io/examples/leaflet-elevation/leaflet-elevation_toggable-charts.html), I've tried to find out which parameter allow me to display the distance milestones on the stroke. I've tried the following but without success:
```js
// options

...

  hoverNumber: { 
    decimalsX: 3, //decimals on distance (always in km)
    decimalsY: 0, //deciamls on height (always in m)
  },

...
```
_Thanks for your help,
Paul_

**Comment by rahan34** [comment]
I think I've found the option **distanceMarkers: true**
but there's still an error in the console : 
__TypeError: L.GeometryUtil is undefinedleaflet-distance-marker.min.js:1:346
    initialize https://unpkg.com/@raruto/leaflet-elevation@0.3.9/libs/leaflet-distance-marker.min.js:1
    e https://unpkg.com/leaflet@1.3.4/dist/leaflet.js:5
    onAdd https://unpkg.com/@raruto/leaflet-elevation@0.3.9/libs/leaflet-distance-marker.min.js:5
    _layerAdd https://unpkg.com/leaflet@1.3.4/dist/leaflet.js:5
    whenReady https://unpkg.com/leaflet@1.3.4/dist/leaflet.js:5
    addLayer https://unpkg.com/leaflet@1.3.4/dist/leaflet.js:5
    addLayer https://unpkg.com/leaflet@1.3.4/dist/leaflet.js:5
    addLayer https://unpkg.com/leaflet@1.3.4/dist/leaflet.js:5_

**Comment by Raruto** [comment]
Hi Paul,
it seems that the following [library](https://unpkg.com/leaflet-geometryutil@0.9.1/src/leaflet.geometryutil.js) is not properly loaded by your code, can you confirm it?
Otherwise, can you also provide a sample code snippet?

_Greetings,
Raruto_

**Comment by rahan34** [comment]
Hi Raruto,
Indeed, the leaflet.geometryutils.js was not loaded correctly. It works like a charm now. köszönöm! :-)
Now, the last trick that could save my day would be to also display in the legend of the elevation chart the total elevation gain for a given GPX track. This information is capital for trail runners, maybe more important than the distance itself.
Have a nice day 
Paul

**Comment by Raruto** [comment]
> Now, the last trick that could save my day would be to also display in the legend of the elevation chart the total elevation gain for a given GPX track. This information is capital for trail runners, maybe more important than the distance itself.

Try to take a look at the following issue: https://github.com/Raruto/leaflet-elevation/issues/18#issuecomment-536332704
