### ISSUE TITLE
Skip distance in chart between multiple tracks 

### ISSUE THREAD

**Issue by FabianSchmick** [Raruto/leaflet-elevation#267]
### Skip the distance in graph between multiple tracks and segments
I have one big gpx file with multiple tracks (multiple `<trk>` and/or `<trkseg>` elements). The end position of the first track (lat, lon) is not always the start position of the second track. So there is a distance between those two. It's divided by some kilometers. The graph visualizes these extra kilometers, but I would like to skip those.

### Your environment
* leaflet-elevation: ^2.5.0
* leaflet: ^1.9.4

### Steps to reproduce
* See the Fiddle: https://jsfiddle.net/erjqhgc1/1/ 
* The gpx file: https://gist.github.com/FabianSchmick/fda433f8cca1d5ea9a79355c903ad983

### Desired behaviour
Like the graph on https://opentopomap.org which concatenate the tracks without any distance

<img width="759" alt="Bildschirmfoto 2023-08-16 um 14 19 09" src="https://github.com/Raruto/leaflet-elevation/assets/17527958/8b17b079-926d-4369-9df4-b974eed6844a">

### Actual behaviour
The graph of leaflet-eleveation adds the distance between the tracks

<img width="804" alt="Bildschirmfoto 2023-08-16 um 14 17 52" src="https://github.com/Raruto/leaflet-elevation/assets/17527958/cec80863-aa5b-48f1-afd3-c69cedadb07c">

I have also seen https://github.com/Raruto/leaflet-elevation/issues/56#issuecomment-1051028310 but this seems not to solve my problem

**Comment by Raruto** [comment]
Hi @FabianSchmick, in [here](https://user-images.githubusercontent.com/17527958/261005489-cec80863-aa5b-48f1-afd3-c69cedadb07c.png) you should actually see some gap between in chart area (ref: https://jsfiddle.net/erjqhgc1/1/).

---

BTW, I recommend you start by doing some testing by implementing a your own custom handler.

In particular, you can start investigating the following:

https://github.com/Raruto/leaflet-elevation/blob/ea155564475c44941cb81a9df3eaf8d633ed90fc/src/handlers/distance.js#L1-L46

---

## Related resources

- https://github.com/Raruto/leaflet-elevation/issues/56#issuecomment-1051028310
- https://github.com/Raruto/leaflet-elevation/issues/251#issuecomment-1525595669

---

> Currently all additional chart area definitions (**altitude**, **speed**, **acceleration**, ...) are lazy-loaded from the [`src/handlers`](https://github.com/Raruto/leaflet-elevation/tree/master/src/handlers).
>
> So I think a good way to achieve this could be to create a custom definition for this type of graph as well.
>
> It sure won't work out of the box, but maybe with a little tweaking of the "loading" logic it might even turn out to be something more useful.
>
> Below some notable functions:
>
> ## • [L.Control.Elevation::options.handlers](https://github.com/Raruto/leaflet-elevation/blob/b0006d635a048ec3d1db519819ad3a9813e7ffc6/examples/leaflet-elevation_extended-ui.html#L255-L271)
>
> https://github.com/Raruto/leaflet-elevation/blob/b0006d635a048ec3d1db519819ad3a9813e7ffc6/examples/leaflet-elevation_extended-ui.html#L255-L271
>
> ## • [L.Control.Elevation::_registerHandler](https://github.com/Raruto/leaflet-elevation/blob/b0006d635a048ec3d1db519819ad3a9813e7ffc6/src/control.js#L1080-L1147)
>
> https://github.com/Raruto/leaflet-elevation/blob/b0006d635a048ec3d1db519819ad3a9813e7ffc6/src/control.js#L1080-L1147
>
> ## • [L.Control.Elevation::_registerDataAttribute](https://github.com/Raruto/leaflet-elevation/blob/b0006d635a048ec3d1db519819ad3a9813e7ffc6/src/control.js#L1003-L1078)
>
> https://github.com/Raruto/leaflet-elevation/blob/b0006d635a048ec3d1db519819ad3a9813e7ffc6/src/control.js#L1003-L1078

👋 Raruto

**Comment by FabianSchmick** [comment]
@Raruto thank you for your reply. The hint with investigating the [src/handlers/distance.js](https://github.com/Raruto/leaflet-elevation/blob/ea155564475c44941cb81a9df3eaf8d633ed90fc/src/handlers/distance.js#L1-L46) handler helped a lot. I understand the project more from day to day.

I also could fix my issue: 🎉 

<img width="943" alt="Bildschirmfoto 2023-08-18 um 11 14 44" src="https://github.com/Raruto/leaflet-elevation/assets/17527958/980690a3-5c77-4938-ad73-b511d5a37e61">

---

But I am not 100% happy with my solution:

1. Override `_addGeoJSONData` and `_addPoint`:
```js
L.Control.Elevation.include({

    _addPoint: function (x, y, z, isFirstPoint = false) {
        ...

        this._data.push({
            x: x,
            y: y,
            z: z,
            latlng: L.latLng(x, y, z),
            isFirstPoint: isFirstPoint
        });

        ...
    },

    _addGeoJSONData: function (coords, properties, nestingLevel) {

       ...

        coords.forEach((point, i) => {

            ...

            this._addPoint(
                point.lat ?? point[1],
                point.lng ?? point[0],
                point.alt ?? point.meta.ele ?? point[2],
                i === 0
            );

            ...
        });

        ...
    }

})
```

2. Create my own handler:
```js
export function Distance() {

	... // I have copied the full file only to add a few lines of code :/

	return {
		...
                pointToAttr: (point, i) => {
                    let currentPointDistance = (i > 0 ? this._data[i - 1].dist : 0);
        
                    if (this._data[i].isFirstPoint) {
                        return currentPointDistance;
                    }
        
                    return currentPointDistance + (this._data[i].latlng.distanceTo(this._data[i > 0 ? i - 1 : i].latlng) * opts.distanceFactor) / 1000;
                },
		...
	};
}
```

As you can see, everytime I write `...` I copied the lines from the library. I have to admit, that I am not an experienced JS-Developer, but I don't like to copy so much code. Do you think the new information `isFirstPoint` on the `this._data`object should live in the source code, maybe this can help others, too? Also, I would like to ask if you know a way to extend the existing `handler` and override only the `pointToAttr` function-body of it (so I don't have to copy the full content of the `src/handlers/distance.js`).

**Comment by Raruto** [comment]
> maybe this can help others, too?

It's definitely something that others might be interested in as well, perhaps through a dedicated option.

To be carefully evaluated through a reasonable PR.

> I don't like to copy so much code

Handlers files are there to allow a certain degree of flexibility to other developers (custom extensions or hotfixes) looking forward to an official release.

Not much has changed in here, but if you don't override the whole handler file in the future it could be a little more difficult to keep your local changes aligned (monkey patching is leaner, but it's also a dangerous technique).

> Do you think the new information isFirstPoint on the this._dataobject should live in the source code?

Alternatively, why not consider the following listener?

https://github.com/Raruto/leaflet-elevation/blob/ea155564475c44941cb81a9df3eaf8d633ed90fc/src/control.js#L368

If I'm not mistaken it's used for a similar purpose:

https://github.com/Raruto/leaflet-elevation/blob/ea155564475c44941cb81a9df3eaf8d633ed90fc/src/components/chart.js#L67-L72

👋 Raruto

**Comment by FabianSchmick** [comment]
I assume the `eletrack_added` event is unfortunately too late.

I tried the following:
```js
controlElevation.on('eletrack_added', ({index}) => {
    controlElevation._data[index]['isLastPoint'] = true;
});
```
In the handler
```js
pointToAttr: (point, i) => {
    ...

    if (this._data[i].isLastPoint === true) {
        console.log("test");
        return currentPointDistance;
    }

    ...
},
```
I think the `pointToAttr` code [is executed before](https://github.com/Raruto/leaflet-elevation/blob/master/src/control.js#L1023-L1030) my flag is added. So the `if`-statement never becomes `true` in the first run.

But if it would work, I could omit the monkey patching.

**Comment by Raruto** [comment]
> I think the pointToAttr code [is executed before](https://github.com/Raruto/leaflet-elevation/blob/master/src/control.js#L1023-L1030) my flag is added.

Listening to both events (in sequence) you should somehow achieve that goal:

https://github.com/Raruto/leaflet-elevation/blob/ea155564475c44941cb81a9df3eaf8d633ed90fc/src/control.js#L363

https://github.com/Raruto/leaflet-elevation/blob/ea155564475c44941cb81a9df3eaf8d633ed90fc/src/control.js#L368

I didn't elaborate, maybe you need some other support flag..

👋 Raruto

**Comment by Raruto** [comment]
However, you probably need to try adding all of your event listeners before all the various handlers are registered:

https://github.com/Raruto/leaflet-elevation/blob/ea155564475c44941cb81a9df3eaf8d633ed90fc/src/control.js#L243-L263

When monkey pathching, in order To avoid duplicating too much code, if you just want to run some code (before or after) that function, you can invoke `oldProto.onAdd.call()` on the old function reference.

Here it is a similar situation: https://github.com/Raruto/leaflet-ui/blob/31b300a69f0ae70b1d0c767686ca1c25c541f03a/src/leaflet-ui.js#L572-L592
