### ISSUE TITLE
How to add the Download button to a gpxGroup map

### ISSUE THREAD

**Issue by marcoA152** [Raruto/leaflet-elevation#269]
Hallo. I'm sorry to bother you but I struggling with this (my) issue: I'm trying to add a Download button to a multiple .gpx tracks map from your examples.
On single gpx file map the button is shown but on multiple gpx map is not present. There is a way to add it?

Thanks in advance

**Comment by Raruto** [comment]
Hi Marco,

probably when using the `L.GpxGroup` class the following variable is not setted:

```js
this._downloadURL = url; // see: leaflet-elevation/src/control.js#741
```

Take a look at this other https://github.com/Raruto/leaflet-elevation/pull/160#issuecomment-1002209215 to start monkey patching that class as you wish (aka [L.Class.include()](https://leafletjs.com/examples/extending/extending-1-classes.html#lclassinclude)).

👋 Raruto

---


## leaflet-gpxgroup.js

https://github.com/Raruto/leaflet-elevation/blob/ea155564475c44941cb81a9df3eaf8d633ed90fc/libs/leaflet-gpxgroup.js#L172-L177

## leaflet-elevation.js

https://github.com/Raruto/leaflet-elevation/blob/ea155564475c44941cb81a9df3eaf8d633ed90fc/src/control.js#L1300-L1312

https://github.com/Raruto/leaflet-elevation/blob/ea155564475c44941cb81a9df3eaf8d633ed90fc/src/control.js#L737-L745

**Comment by marcoA152** [comment]
Thank you i will try the way you have suggested, but but probably the fastest (and dirt) thing to do is to put a direct anchor to the gpx file under the  "elevation-div"

Thanks for your work and for this amazing plugin!
