### ISSUE TITLE
GPX FileLayer data loaded event

### ISSUE THREAD

**Issue by rahan34** [Raruto/leaflet-elevation#28]
Hey Raruto, here is a strange behavior I've noticed and tried to solve without success:

In [this URL](http://193.70.42.160/test/view.php) I load a static GPX file from an URL and I calculate the elevation gain. Everything goes fine, you can see in the chart summary, it is displayed after the Total.

```js
var GPXurl = "http://193.70.42.160/test/jeudimatin.gpx";

var controlElevation2 = L.control.elevation(opts.elevationControl2.options);
controlElevation2.addTo(map);
controlElevation2.load(GPXurl);

map.on('eledata_loaded', function(e) {
  var q     = document.querySelector.bind(document);
  var track = e.track_info;
  var layer = e.layer;
   		
  // Advanced summary info
  gain =  layer.get_elevation_gain() ;
  loss =  layer.get_elevation_loss() ;
  // layer.get_total_time();
  // layer.get_total_speed();

  map.fitBounds(e.target.getBounds());
  //alert(gain);
  //document.getElementById("dplus").innerHTML = gain.toFixed(2) + " m";
  q('.gain .summaryvalue').innerHTML = gain.toFixed(0) + " m";

});
```
Now, in [this other URL](http://193.70.42.160/test/), I have used your GPX local file loader at topright position to select the same [GPX file](http://193.70.42.160/test/jeudimatin.gpx) which has correct elevation data inside. I then try to calculate the same elevation gain like this below in the **data:loaded** function. Nothing happens and the elevation chart does not display, 

```js
fileLayer.loader.on('data:loaded', function(e) {
  if (layer) layer.remove();
    layer = e.layer;
    //gpx_layer = e.target.getLayers()[0];
    gain =  e.layer.get_elevation_gain() ;
    if (!controlElevation._map) controlElevation.addTo(map);
    else controlElevation.redraw(); 
    map.locate({setView: false, maxZoom: 17, watch:true});
    q('.gain .summaryvalue').innerHTML = gain.toFixed(0) + " m";
});
```
If I comment this line: `gain =  e.layer.get_elevation_gain();`
then the chart loads but of course no gain is reported. As if the **get_elevation_gain** function has not been defined for the layer when using the `var fileLayer = L.Control.fileLayerLoad`. But I have no error in the console.

_Many thanks for your help,
Paul_

**Comment by Raruto** [comment]
Hi Paul,

- in your [first example](http://193.70.42.160/test/view.php) you should do a little code change (to fix CORS error):
`var GPXurl = "http://193.70.42.160/test/jeudimatin.gpx";`
- in your [second example](http://193.70.42.160/test/) I think that the **get_elevation_gain** function is not defined because you are refering to the `layer` in a wrong variable context (ie. **data:loaded** IS NOT **data_loaded**).

Anyway, here is a proof of solution (I haven't tested it):
```js
fileLayer.loader.on('data:loaded', function(e) {
  if (layer) layer.remove();

  // layer = e.layer;
  
  if (!controlElevation._map) controlElevation.addTo(map);
  else controlElevation.redraw(); 
});

map.on('eledata_loaded', function(e) {
  var q     = document.querySelector.bind(document);
  var layer = e.layer;
   		
  gain =  layer.get_elevation_gain() ;

  q('.gain .summaryvalue').innerHTML = gain.toFixed(0) + " m";
});
```

_Regards,
Raruto_

**Comment by rahan34** [comment]
Hi Raruto,
Thanks for your quick reply, you're a pro!

I've corrected [my first example.](http://193.70.42.160/test/view.php) The elevation is fine below the chart.
In [the second example](http://193.70.42.160/test/), I have replaced with your code, but it nevers enter the `map.on('eledata_loaded', function(e)`
To text that, I've put 2 alerts : one in `fileLayer.loader.on('data:loaded', function(e) {`
and another in `map.on('eledata_loaded', function(e)`
Once the GPX is loaded, only the first one is called. You can try to upload my GPX file on the second example.
Thanks again,
Paul

**Comment by Raruto** [comment]
Since your are using the following function to load elevation data:
```js
var fileLayer = L.Control.fileLayerLoad({
 ...

  onEachFeature: function(d, layer) {
    controlElevation.addData(d, layer); // It fires "eledata_loaded" event
  },

 ...
});
```
you can instead try to listen to the following:
```js
// NB. potentially invoked multiple times per gpx file (ie. "onEachFeature")
map.on('eledata_added', function(e) {
  var q     = document.querySelector.bind(document);
  var layer = e.layer;
   		
  gain =  layer.get_elevation_gain() ;

  q('.gain .summaryvalue').innerHTML = gain.toFixed(0) + " m";
});
```

**Comment by rahan34** [comment]
Sorry Raruto but if I remove `fileLayer.loader.on('data:loaded', function(e) {`
it never goes into `map.on('eledata_added', function(e) {`
In actual code, the GPX loads fine but no elevation chart is visible which is strange as I have added to your code the next 2 lines :  
` if (!controlElevation._map) controlElevation.addTo(map);
  else controlElevation.redraw();`

**Comment by Raruto** [comment]
Your previous code was almost right, you just had to replace the string `'eledata_loaded'` with `'eledata_added'` (see [previous comment](https://github.com/Raruto/leaflet-elevation/issues/28#issuecomment-564216021))

**Comment by Raruto** [comment]
Based on my [previous comment](https://github.com/Raruto/leaflet-elevation/issues/28#issuecomment-564216021).

Here it is a fixed version:
```js
var fileLayer = L.Control.fileLayerLoad({
 ...

  onEachFeature: function(d, layer) {
    controlElevation.addData(d, layer); // It fires "eledata_added" event
  },

 ...
});
```

```js
fileLayer.loader.on('data:loaded', function(e) {
  if (layer) layer.remove();

  // layer = e.layer;
  
  if (!controlElevation._map) controlElevation.addTo(map);
  else controlElevation.redraw(); 
 });
```

```js
// WRONG
// NB. not firing because it is called before executing: "controlElevation.addTo(map)"
// map.on('eledata_added', function(e) { ... }

// FIXED
controlElevation.on('eledata_added', function(e) {
  var q     = document.querySelector.bind(document);
  var layer = e.layer;
   		
  gain =  layer.get_elevation_gain() ;

  q('.gain .summaryvalue').innerHTML = gain.toFixed(0) + " m";
});
```

**Comment by rahan34** [comment]
Mea culpa. But it still doesn't calculate any gain. 
It never goes into 'eledata_added' function.
I'm sure I'm really closed and you are already there !

**Comment by rahan34** [comment]
I perfectly understand the logic behind. 
Unfortunately, with `controlElevation.on('eledata_added', function(e) {`
nothing happens, no error in the console.
Many thanks for your help !

**Comment by Raruto** [comment]
> nothing happens, no error in the console.

This is how javascript works (stop code execution if error occurs within calback functions)

```js
controlElevation.on('eledata_added', function(e) {
  
  console.log(e); // OK ( log to browser console ? )

  var q     = document.querySelector.bind(document);
  var layer = e.layer;
   		
  gain =  layer.get_elevation_gain() ; // KO ( get_elevation_gain is undefined ? )

  q('.gain .summaryvalue').innerHTML = gain.toFixed(0) + " m";

  console.log(e); // KO ( log to browser console ? )
});
```
from what i understood, `layer.get_elevation_gain()` is undefined because the **layer** object is not an instace of the [L.GPX](https://github.com/mpetazzoni/leaflet-gpx) class.

---

**leaflet-filelayer.js**:
- [GPX layer](https://github.com/makinacorpus/Leaflet.FileLayer/blob/47e981238a58563ed14621f73328a9c9c1e1799c/src/leaflet.filelayer.js#L56) (`data:loaded` context --> returns a **L.geoJSON layer**)

**leaflet-elevation.js**:
- [addData()](https://github.com/Raruto/leaflet-elevation/blob/447201b70a50bacf432da2e21ab74c9083d34bbb/leaflet-elevation.js#L127) (`eledata_added` context --> returns a **L.geoJSON layer**)
- [loadGPX()](https://github.com/Raruto/leaflet-elevation/blob/447201b70a50bacf432da2e21ab74c9083d34bbb/leaflet-elevation.js#L340) (`eledata_loaded` context --> returns a **L.GPX layer**)

**Comment by rahan34** [comment]
I see, We have 2 different objects here and only the L.GPX layer can give the layer.get_elevation_gain();
Then, why not trying to set another object with loadGPX() with data from the L.geoJSON layer object.

Something like not loading an url but directly the content through my master variable :
```
var master;
fileLayer.loader.on('data:loaded', function(e) {
  if (layer) layer.remove();
	master = e.result;
    if (!controlElevation._map) controlElevation.addTo(map);
  else controlElevation.redraw(); 
 });

var controlElevation2 = L.control.elevation(opts.elevationControl2.options);
		controlElevation2.addTo(map);
		controlElevation2.load(master);

		map.on('eledata_loaded', function(e) {
   		var q = document.querySelector.bind(document);
   		var layer = e.layer;
  		gain =  layer.get_elevation_gain() ;
		map.fitBounds(e.target.getBounds());
   		q('.gain .summaryvalue').innerHTML = gain.toFixed(0) + " m";
		});
```

**Comment by Raruto** [comment]
Here it is an alternative solution.

```js
controlElevation.on('eledata_added', function(e) {

// Calculate elevation gain/loss (based on: https://github.com/mpetazzoni/leaflet-gpx/blob/3a8940cc4e5cd084c6ddab41a4e1f3573c893a73/gpx.js#L485)

var gain = 0.0;
var loss = 0.0;
var data = controlElevation._data;

var curr, prev, t;

for (var i = 0; i < data.length; i++) {

  curr = data[i];

  if(prev != null) {
    t = curr.z - prev.z;
    if (t > 0) { gain += t; }
    else { loss += Math.abs(t); }
  }

  prev = curr;

}

}
```

**Comment by rahan34** [comment]
Raruto, your solution works like a charm.
I send you a virtual coffee or beer !
Paul
