### ISSUE TITLE
Disable built-in lazy loader (dynamic imports) and load all dependencies statically

### ISSUE THREAD

**Issue by Tomek-Z** [Raruto/leaflet-elevation#280]
### Subject of the issue
Problem with running demo from README

### Your environment
* leaflet-elevation: 2.51
* leaflet: 1.9.4
* browser: Chromium
* operating system: Linux 
* link to your project: -

### Steps to reproduce
I am trying to use leaflet-elevation in my application. I install it like so:

```
npm i @raruto/leaflet-elevation
```

```js
import { AfterViewInit, Component } from "@angular/core";
import * as L from "leaflet";
import { Control } from "leaflet";
import "@raruto/leaflet-elevation";

declare module "leaflet" {
  namespace control {
    export function elevation(options: any): Control.Elevation;
  }
  namespace Control {
    export class Elevation extends Control {
      constructor(options: any);

      options: any;

      on(action: string, fun: any): void;

      load(url: string): void;
    }
  }
}


@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.scss"]
})
export class AppComponent implements AfterViewInit {

  ngAfterViewInit(): void {
    // Full list options at "leaflet-elevation.js"
    const elevOptions = {

// Default chart colors: theme lime-theme, magenta-theme, ...
      theme: "lightblue-theme",

// Chart container outside/inside map container
      detached: true,

// if (detached), the elevation chart container
      elevationDiv: "#elevation-div",

// if (!detached) autohide chart profile on chart mouseleave
      autohide: false,

// if (!detached) initial state of chart profile control
      collapsed: false,

// if (!detached) control position on one of map corners
      position: "topright",

// Toggle close icon visibility
      closeBtn: true,

// Autoupdate map center on chart mouseover.
      followMarker: true,

// Autoupdate map bounds on chart update.
      autofitBounds: true,

// Chart distance/elevation units.
      imperial: false,

// [Lat, Long] vs [Long, Lat] points. (leaflet default: [Lat, Long])
      reverseCoords: false,

// Acceleration chart profile: true || "summary" || "disabled" || false
      acceleration: false,

// Slope chart profile: true || "summary" || "disabled" || false
      slope: false,

// Speed chart profile: true || "summary" || "disabled" || false
      speed: false,

// Altitude chart profile: true || "summary" || "disabled" || false
      altitude: true,

// Display time info: true || "summary" || false
      time: true,

// Display distance info: true || "summary" || false
      distance: true,

// Summary track info style: "inline" || "multiline" || false
      summary: "multiline",

// Download link: "link" || false || "modal"
      downloadLink: "link",

// Toggle chart ruler filter
      ruler: true,

// Toggle chart legend filter
      legend: true,

// Toggle "leaflet-almostover" integration
      almostOver: true,

// Toggle "leaflet-distance-markers" integration
      distanceMarkers: false,

// Toggle "leaflet-edgescale" integration
      edgeScale: false,

// Toggle "leaflet-hotline" integration
      hotline: true,

// Display track datetimes: true || false
      timestamps: false,

// Display track waypoints: true || "markers" || "dots" || false
      waypoints: true,

// Toggle custom waypoint icons: true || { associative array of <sym> tags } || false
      wptIcons: {
        "": L.divIcon({
          className: "elevation-waypoint-marker",
          html: "<i class=\"elevation-waypoint-icon\"></i>",
          iconSize: [30, 30],
          iconAnchor: [8, 30],
        }),
      },

      // Toggle waypoint labels: true || "markers" || "dots" || false
      wptLabels: true,

      // Render chart profiles as Canvas or SVG Paths
      preferCanvas: true,

    };

    // Instantiate map (leaflet-ui).
    const map = L.map("map", {center: [41.4583, 12.7059], zoom: 5});

    // Instantiate elevation control.
    const controlElevation = L.control.elevation(elevOptions).addTo(map);

    const tiles = L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
      maxZoom: 18,
      minZoom: 3,
      attribution: "&copy; <a href=\"http://www.openstreetmap.org/copyright\">OpenStreetMap</a>"
    });

    tiles.addTo(map);

    // Load track from url (allowed data types: "*.geojson", "*.gpx", "*.tcx")
    controlElevation.load("https://raruto.github.io/leaflet-elevation/examples/via-emilia.gpx");
  }
}
```

### Actual behaviour
and I get the following errors:
![image](https://github.com/Raruto/leaflet-elevation/assets/151588332/b60246d0-900f-40b7-8eef-a2c1276e74e5)

### Expected behaviour
I hope leaflet-elevation could work with angular. Any help appreciated :)

**Comment by Raruto** [comment]
Hi @Tomek-Z,

please also search among closed issues.. 👉 https://github.com/Raruto/leaflet-elevation/issues/229

Within README there is also a section dedicated to js bundlers: https://github.com/Raruto/leaflet-elevation/blob/bd9316bd1b7e7784b3bf3d812960eaa808ad94d6/README.md?plain=1#L265-L290

BTW, I couldn't tell you about the missing file from unpkg.com.

👋 Raruto

**Comment by Tomek-Z** [comment]
Hi,

Thanks for your answer. I found out that version 1.9.6 works for me. However I think that newer versions also introduce some attractive features I want to use hence I have a question.

 Is there a possibility to disable dynamic imports in leaflet-elevation and loads everything statically like it was loaded before 2.0.0? 

I've been looking on it since a few days and still have no idea how to merge dynamic imports with Angular and finally make it works..

**Comment by Raruto** [comment]
Hi @Tomek-Z,

in order to disable built-in lazy loader you should just statically import the dependencies of this library and expose them globally (ie. onto the [`window`](https://developer.mozilla.org/en-US/docs/Web/API/Window/window) or [`globalThis`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) object).

https://github.com/Raruto/leaflet-elevation/blob/bd9316bd1b7e7784b3bf3d812960eaa808ad94d6/src/control.js#L213-L230

https://github.com/Raruto/leaflet-elevation/blob/bd9316bd1b7e7784b3bf3d812960eaa808ad94d6/src/control.js#L747-L764

So to be clear, something like the following:

```js
// external dependencies

import { d3 }        from "src/assets/d3.js";
import { togeojson } from "src/assets/togeojson.js";

globalThis.d3        = d3;
globalThis.togeojson = togeojson;
```

```js
// chart handlers

import { Distance } from "src/handlers/distance.js";
import { Altitude } from "src/handlers/altitude.js";

globalThis.L.Control.Elevation.Distance = Distance;
globalThis.L.Control.Elevation.Altitude = Altitude;

// or even just like that:
// const controlElevation = L.control.elevation({
//  handlers: [
//    Distance,
//    Altitude,
//  ],
//  ...
// }).addTo(map);
```

If needed, take a look at this too: https://github.com/Raruto/leaflet-elevation/issues/266

👋 Raruto

**Comment by Tomek-Z** [comment]
Thanks a lot @Raruto! Code from #266 works for me. Tomorrow I will explore all the features of leaflet-elevation with the newest version! : )

One thing left - I don't know if it's a problem, during compilation I see this:
./node_modules/@raruto/leaflet-elevation/dist/leaflet-elevation.js:629:35-82 - Warning: Critical dependency: the request of a dependency is an expression

**Comment by Raruto** [comment]
@Tomek-Z please also attach your final code to help others who come after you.

> Warning: Critical dependency: the request of a dependency is an expression

It's a bundler related issue, search on the net for more info about it.

👋 Raruto

**Comment by Tomek-Z** [comment]
Hi, 

I hope you're doing well.

One thing still not-working for me.  
![image](https://github.com/Raruto/leaflet-elevation/assets/151588332/4e7a55e6-3d4d-4d97-8b21-830bfebac300)

When I'm following the route on the map I can't see a tooltip in the bottom chart. No error nor warning happened. 
Do you have any idea what I have to check or where to start investigation? 

Kind regards

**Comment by Tomek-Z** [comment]
After long debugging I found out that leaflet tooltip is conflicting with bootstrap tooltip. 

In file node_modules/bootstrap/scss/bootstrap.scss I commented line:  //@import "tooltip"; and leaflet tooltip works.

@Raruto Consider changing class naming.. I don't know : ) 

With this I close this thread.
All the best.
