### ISSUE TITLE
Elevation profile for drawn line using Leaflet Drawn polyline

### ISSUE THREAD

**Issue by lordsalomon** [Raruto/leaflet-elevation#285]
### Elevation profile for drawn line using Leaflet Drawn polyline
Hello, is it possible to have elevation profile of Drawn polyline using the Leaflet Drawn polygon (https://leaflet.github.io/Leaflet.draw/docs/leaflet-draw-latest.html). That would be great. Thanks

**Comment by Raruto** [comment]
Hi @lordsalomon,

>  is it possible to have elevation profile of Drawn polyline using the Leaflet Drawn polygon ?

It's the developer's job know how to integrate them into their apps..

👋 Raruto

**Comment by lordsalomon** [comment]
Thanks @Raruto . I am quite new to leaflet but I will figure out a way to do it. Thanks for the great plugin.
