### ISSUE TITLE
[How to] get a callback when file gpx is loaded?

### ISSUE THREAD

**Issue by FranGhe** [Raruto/leaflet-elevation#289]
I would like to have a callback when the my Gpx file is loaded, so track and graph are ready because I need to get the zoom level.

My code is this:

```js
var elevationFileGPX="https://....file.gpx";
var elevationViewer = L.control.elevation(options).addTo(mymap);
elevationViewer.load(elevationFileGPX);
```

I thought to use this... but don't work for me

```js
elevationViewer.on('eledata_added eledata_loaded', function(){
    console.log("loaded");
}); 
```

I found on old issues but without success... any suggestion?

**Comment by hupe13** [comment]
There is an event eledata_loaded:
https://github.com/Raruto/leaflet-elevation/blob/bd9316bd1b7e7784b3bf3d812960eaa808ad94d6/examples/leaflet-elevation.html#L78

I use [this](https://github.com/hupe13/extensions-leaflet-map-github/blob/1a3b5deb4b3a5d9adaa0d3a115213ac357fcf067/js/zoomhome.js#L232) in a WordPress plugin.

**Comment by Raruto** [comment]
Just a clarification:

1. in [here](https://github.com/hupe13/extensions-leaflet-map-github/blob/1a3b5deb4b3a5d9adaa0d3a115213ac357fcf067/js/zoomhome.js#L232) hupe listens for the `eledata_loaded` event on the `L.Map` object.
2. the listener must be attached before invoking the `elevationViewer.load()` function

👋 Raruto

**Comment by FranGhe** [comment]
My was solution was :

`elevationViewer.on('eledata_loaded', function(**{layer, name}**){
    console.log("loaded");
}); 
`
Thanks
