### ISSUE TITLE
CORS header 'Access-Control-Allow-Origin' missing

### ISSUE THREAD

**Issue by hencheck94** [Raruto/leaflet-elevation#29]
Sorry if this an improper way to contact you. I didn't find another way. I found your amazing solution for displaying GPX files with an altitude graph after looking for exactly that. 
I am trying to implement this with very very basic knowledge about how to into a wordpress blog to display trails+elevation data. Unfortunately the map doesn't get displayed. 
It leads to:

```js
Error: Bounds are not valid.
       fitBounds            (leaflet.js:5:31707)
       _resetView           (leaflet-elevation.js:1183)
       fire                 (leaflet.js:5:16833)
       (anonymous function) (leaflet.js:5:43183)
       (anonymous function)
```

I would be very happy if you could give me some hints how to implement this into a wordpress blog! 
Thank you!

**Comment by Raruto** [comment]
Hello to you,

it is very likely that the gpx file you try to use is not correctly loaded (does it reside on your own server?)

_Raruto_

**Comment by hencheck94** [comment]
Hi,
thank you for your fast reply. Placing the gpx file on the same server indeed resolved the error. Thank you! 
Problem is: I still do not manage to get the map displayed. 
I drag&droped your example code [https://raruto.github.io/examples/leaflet-elevation/leaflet-elevation_gpx-waypoints.html](url) to test it on wordpress with the theme i use. 
Most likely something in my stylesheet is preventing it to be displayed correctly. 
Do you have a clue how to fix it or a tip where i should start looking?
http://gr20.jan-unterwegs.de/2019/12/15/test/

-Jan

**Comment by Raruto** [comment]
```html
<style>
  .leaflet-map-container {
    min-height: 500px; /* .leaflet-map height will fit this value*/
  }
</style>

<div class="leaflet-map-container">
  <div id="map" class="leaflet-map"></div>
</div>
```

See: [why doesnt leaflet fill the height of its parent container?](https://gis.stackexchange.com/questions/245814/why-doesnt-leaflet-fill-the-height-of-its-parent-container)
