### ISSUE TITLE
Incorrect time shown in y-axis

### ISSUE THREAD

**Issue by HAmamiya** [Raruto/leaflet-elevation#292]
Hi Raruto,

First of all thanks for your project which is really useful ^^.

### Subject of the issue
Incorrect time shown in y-axis

### Your environment
* leaflet-elevation: https://unpkg.com/@raruto/leaflet-elevation@2.5.1/dist/leaflet-elevation.min.js
* leaflet: https://unpkg.com/leaflet@1.9.4/dist/leaflet.js
* leaflet-ui: https://unpkg.com/leaflet-ui@0.6.0/dist/leaflet-ui.js
* browser: Firefox 126.0.1 AMD 64bit 
* operating system: Windows 10
* link to your project: https://fgtracker.us.to/modules/fgtracker/?FUNCT=FLIGHT&FLIGHTID=7675089
*  link to your project: https://fgtracker.us.to/modules/fgtracker/?FUNCT=FLIGHT&FLIGHTID=7675154

### Steps to reproduce
Use template https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_speed-chart.html with the following GeoJSON files:
https://fgtracker.us.to/modules/fgtracker/interface.php?action=geojson&flightid=7675089
https://fgtracker.us.to/modules/fgtracker/interface.php?action=geojson&flightid=7675154

### Expected behaviour
Time t on y-axis matches the actual time logged in GeoJSON file.

### Actual behaviour
![Screenshot 2024-06-08 173259](https://github.com/Raruto/leaflet-elevation/assets/48651467/f0bb855e-2c51-4b04-802b-09744d6ebb14)

### Further questions
Please allow me to ask some question here:
1) When` imperial: true,` the y-axis is in miles. Is it possible, like speed, to change miles to nautical miles?
2) label on x-axis (elevation) may become too large to feed in the graph.
![Screenshot_20240608_174021_Firefox](https://github.com/Raruto/leaflet-elevation/assets/48651467/c311d925-558c-48f4-8907-4f4b184698da)

Any possible fix or workaround?

Thanks in advance,
Hazuki

**Comment by Raruto** [comment]
> Incorrect time shown in axis

Duplicate of: https://github.com/Raruto/leaflet-elevation/issues/170

https://github.com/Raruto/leaflet-elevation/blob/bd9316bd1b7e7784b3bf3d812960eaa808ad94d6/src/handlers/speed.js#L8

> Is it possible, like speed, to change miles to nautical miles?

Here's the relevant code:

https://github.com/Raruto/leaflet-elevation/blob/bd9316bd1b7e7784b3bf3d812960eaa808ad94d6/src/handlers/speed.js#L18-L22

https://github.com/Raruto/leaflet-elevation/blob/bd9316bd1b7e7784b3bf3d812960eaa808ad94d6/src/handlers/distance.js#L8

https://github.com/Raruto/leaflet-elevation/blob/bd9316bd1b7e7784b3bf3d812960eaa808ad94d6/src/handlers/distance.js#L17

👋 Raruto

**Comment by HAmamiya** [comment]
Thanks for the hints!
So for aviation, the required options are:
```speed: true,
speedLabel: 'knts',
xLabel: 'nm', //distanceLabel, will be ignored if imperial: true
distanceFactor: 0.539956803455724, //For km to nm. distanceFactor will be ignored if imperial: true
yLabel: 'ft',
altitude: true,
altitudeFactor: 3.281,
imperial: false,
```

And looks like the titled problem requires code fix and duplicated with https://github.com/Raruto/leaflet-elevation/issues/170, I shall mark this as closed as duplicate.
