### ISSUE TITLE
How to use this plugin with MapboxGL in Ionic v3 Project?

### ISSUE THREAD

**Issue by LucaTrip** [Raruto/leaflet-elevation#33]

**Comment by Raruto** [comment]
Hi Luca,
I don't use Ionic, but here are some links you might start looking at:

- https://forum.ionicframework.com/search?q=mapbox
- https://blog.mapbox.com/using-leaflet-plugins-with-mapbox-js-a-showcase-ad60146044e1
- https://codepen.io/elmor34/pen/QyMYNj
- https://www.youtube.com/watch?v=i0uJWDXag7Y

_Have a nice year,
Raruto_
