### ISSUE TITLE
Prevent re-centering map on enter/exit fullscreen

### ISSUE THREAD

**Issue by ajlaker** [Raruto/leaflet-elevation#36]
Hello! I love this plugin, but I'm wondering if there is a way to disable the zooming and re-centering of the map that occurs when a user enters or exits fullscreen mode?

For example, a user might be zoomed in on a particular portion of a gpx route. Upon entering fullscreen mode, the map zooms out and re-centers to show the complete gpx route. This might make for a poor user experience if someone is tracking their hiking route in real time with GPS location control.

Thanks!

**Comment by Raruto** [comment]
Now from **version 0.8.0** it checks for the following variable `map._isFullscreen` (see: [brunob/leaflet.fullscreen](https://github.com/brunob/leaflet.fullscreen) or [leaflet/leaflet.fullscreen](https://github.com/leaflet/leaflet.fullscreen) for more info)

_Raruto_

**Comment by ajlaker** [comment]
That was fast! Thank you so much -- it works great!
