### ISSUE TITLE
Loading gpx from local directory

### ISSUE THREAD

**Issue by ghtmtt** [Raruto/leaflet-elevation#4]
I have some trouble when loading gpx tracks on a local file (I see that in your example your gpx track is located on a *real* url).

The following image is on a local machine (and it's doing the job perfectly): 

![image](https://user-images.githubusercontent.com/2884884/56768377-7d8eed00-67ae-11e9-98ea-359b50b88940.png)

while this following image is the result when I load the exact same `html` file but on a server (I'd so say in production):

![image](https://user-images.githubusercontent.com/2884884/56768491-d5c5ef00-67ae-11e9-90d9-13e5ae548a85.png)

So it seems that the issue is when I upload the track on the server. I get this error from firefox console:

```
XML Parsing Error: mismatched tag. Expected: </link>.
Location: http://...................................../maps/track.gpx
Line Number 26, Column 15:
```

Do you have any suggestion to solve this problem? Many thanks!

**Comment by Raruto** [comment]
Maybe you can try:
- validating your gpx file (eg. [here](https://codebeautify.org/xmlvalidator) through the "Load From Url" button)
- using a minimized version of your gpx file (eg. from [here](https://codebeautify.org/xmlviewer/))
- using a different gpx file (eg. uploading [via-emilia.gpx](https://raruto.github.io/examples/leaflet-elevation/via-emilia.gpx) to your own server)

**Comment by ghtmtt** [comment]
Perfect, thanks! After digging more in depth I discover I had a problem (my website) blocking the uploading of gpx file (no messages if the operation was made via ssh).

Thanks for the support

**Comment by ghtmtt** [comment]
I have some ideas to include your work in QGIS. If you are interested, can we get in touch?

**Comment by Raruto** [comment]
For now, I have created a dedicated issue #5.

Keep me informed if you need further plugin's “knowledge” about this library ...
