### ISSUE TITLE
Translation options

### ISSUE THREAD

**Issue by ZhukDmitry** [Raruto/leaflet-elevation#40]
Hi.
I'm very appreciate you for development and support new features.
Your plugin is running on the last leaflet versions.
I have a few issues and improvement request.

First of it:
- it is good idea to have options for translation, I mean to have option node to pass translation for tags, for example 

**`Total Length`**`: 264.69 km `**`Max Elevation`**`: 84.90 m `**`Min Elevation`**`: 6.60 m`

- have parameter to disable change polyline style. Lets to tell a little about.
-- I use your plugin in part to display only chart, I mean I parse my GPX/KML files by myself and pass only polyline data as call **addData** method. But in it you do 
```js
if (layer._path) {
  L.DomUtil.addClass(layer._path, 'elevation-polyline ' + this.options.theme);
}
```
and in this case I need to do rollback action

```js
L.DomUtil.removeClass(fv_path._path, 'elevation-polyline');
L.DomUtil.removeClass(fv_path._path, 'lightblue-theme');
````
it is in case **lightblue** theme ;)

It is because in my file I have a few track segments with different color. And after this code I have all track in one color (theme color). I need to manage how to do with it.
It is good idea not change current line color to current theme color.
 
Cheers,
I'll post the other issues/improvements ;)
Dmitry

**Comment by Raruto** [comment]
Hi Dmitry,

> it is good idea to have options for translation

This is a common problem of all leaflet plugins, some time ago I found this project [Leaflet.i18n](https://github.com/yohanboniface/Leaflet.i18n), but I never had time to think of a good solution about it.

Alternatively, you can also use this option:

```js
// Summary track info style: "line" || "multiline" || false
summary: false,
```

and then create / use your own summary:

```js
map.on('eledata_loaded', function(e) {
  var q = document.querySelector.bind(document);

  var layer = e.layer;
  var dist =  layer.get_distance() ;
  var max =  layer.get_elevation_min() ;
  var min =  layer.get_elevation_min() ;

  map.fitBounds(e.target.getBounds());

  q('.gain .summarylabel').innerHTML = "Total Length: ";
  q('.gain .summaryvalue').innerHTML = dist.toFixed(0) + " m";

  // etc.
});
```

> have parameter to disable change polyline style.

You can always use your own CSS Rules to override colors as you like.

Otherwise take a look at this [example](https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_custom-theme.html) for more info about this option:

```js
theme: "custom-theme", // CHANGE: your custom-theme name
```

**Comment by ZhukDmitry** [comment]
As for translation.
In options you have
		xLabel: "km",
		yLabel: "m",
I didn't check when I set imperial to true.

But you can add options like
translation: {
 distance: "Total length",
 min_elevation: "Min Elevation",
 max_elevation: "Max Elevation"}

in this case I can override it.

As for color - just add new parameter like
use_theme_color: true

And I can easy set it to false to not apply your classes

**Comment by Raruto** [comment]
```js
  translation: {
    distance: "Total length",
    min_elevation: "Min Elevation",
    max_elevation: "Max Elevation",
  }
```
That is exactly the kind of solution I want to avoid.

For the moment, if you really want to use the default summary, I recommend using this quicky solution:

```js
var q = document.querySelector.bind(document);
q('.totlen .summarylabel').innerHTML = "Total Length: ";
q('.maxele .summarylabel').innerHTML = "Max Elevation ";
q('.minele .summarylabel').innerHTML = "Min Elevation ";
```

```js
 use_theme_color: true
```
I don't quite understand what you want to achieve, but have you tried to do something like the following?

```
  theme: "",
```

**PS** CSS classes are added just to facilitate in overwriting them...

**Comment by ZhukDmitry** [comment]
As for translation. I have extension, which supports different languages on the fly. And I want to dynamically change text, on summary too. I know I can rewrite this section at all, but I think it should be flexible to have it in initialization.
If you don't - I'll be like you write ;)

For themes - the same, I can have access to it and can doo it.

It was only suggestions ;)
Thanks for your work and support

**Comment by Raruto** [comment]
> I think it should be flexible to have it in initialization.

I would prefer to implement a more reusable solution, since our applications can use many different plugins, it would be much better to use just a single [i18n](https://github.com/yohanboniface/Leaflet.i18n) object.

> If you don't - I'll do like you write ;)

Before this I should better reorganize the current npm project...

**Comment by ZhukDmitry** [comment]
OK. Lets close.

**Comment by Raruto** [comment]
Hi Dmitry,
take a look at the [i18n](https://github.com/Raruto/leaflet-elevation/tree/i18n) branch (I'm not sure if this will be version 1.0.0), here's how it should work:

```js
var mylocale = {
  "Total Length: ": "Distanza: ",
  "Max Elevation: ": "Altezza Max: ",
  "Min Elevation: ": "Altezza Min: ",
};

L.registerLocale('it', mylocale);
L.setLocale('it');

var controlElevation = L.control.elevation(opts.elevationControl.options);
controlElevation.load(opts.elevationControl.url);
```

Complete example: [leaflet-elevation_i18n-strings.html](https://github.com/Raruto/leaflet-elevation/blob/i18n/examples/leaflet-elevation_i18n-strings.html)
