### ISSUE TITLE
Drop value in diagram

### ISSUE THREAD

**Issue by ZhukDmitry** [Raruto/leaflet-elevation#41]
Hi.
Thanks again for your work. It's me again.

Here my diagram
![2020-03-02_22-15-35](https://user-images.githubusercontent.com/18059939/75709455-c1f2ef80-5cd3-11ea-965d-1d9aae9e9a21.png)

In my data there is no empty ele tags, but I have break to low value

I can give you my GPX file

![2020-03-02_22-21-49](https://user-images.githubusercontent.com/18059939/75709737-4cd3ea00-5cd4-11ea-8c44-1e0685869ea6.png)

In addition to this as you can see yAxis have the wrong padding with value more than 1000

;)
Dmitry

**Comment by Raruto** [comment]
> In my data there is no empty ele tags, but I have break to low value

Probably a value results as an infinite value.

If you are interested in understanding better, the following function is responsible for calculating the addition of a new point:

https://github.com/Raruto/leaflet-elevation/blob/13154800917497155b63a91d0049864523e963f4/leaflet-elevation.js#L545

**Comment by ZhukDmitry** [comment]
OK. I found, it was a wrong value in file. Closed.

**Comment by Raruto** [comment]
> OK. I found, it was a wrong value in file.

Could you let me have the offending piece of code?
Already `null` values are already discarded, is it something else that we can fix?

**Comment by ZhukDmitry** [comment]
No. It was wrong value in file. I don't know how it was, but all your code is fine.

<trkpt lat="38.894764222204685" lon="1.218488495796919">
        <ele>-5.15</ele>
        <time>2018-03-26T13:54:58Z</time>
      </trkpt>
      <trkpt lat="38.894764976575971" lon="1.218519257381558">
        <ele>-1500</ele>
        <time>2018-03-26T13:55:04Z</time>
      </trkpt>
      <trkpt lat="38.894730359315872" lon="1.218582037836313">
        <ele>-3.23</ele>
        <time>2018-03-26T13:55:20Z</time>
      </trkpt>

I step by step remove values and found. I think it was device error to create records.

Thanks for your help..

**Comment by Raruto** [comment]
OK thanks.

This is a common problem for **tunnels** too, it would be nice to have a setting to try to mitigate these types of problems.

**Comment by ZhukDmitry** [comment]
For example if current elevation and previous differs more than 20-30% then take average. But tunnel can be long ;)
