### ISSUE TITLE
Problem with mouse and touch with release 0.8

### ISSUE THREAD

**Issue by ZhukDmitry** [Raruto/leaflet-elevation#42]
Hi.
It is me again.
I get error of behaviour.
When I enable 0.8.0 or current release - I got correct diagram, but if I click on it, it is removed, only axis. Click again - shown. But you can select range on it. Only click event.

If I click on mobile browser - the same

I check, in your example there is 0.6.8, and it gives correct behaviour.

Cheers,
Dmitry

**Comment by Raruto** [comment]
I think you are referring to this line:

https://github.com/Raruto/leaflet-elevation/blob/13154800917497155b63a91d0049864523e963f4/leaflet-elevation.js#L966

Basically I tried to set some sort of "click on chart" to toggle on / off the elevation profile.

In version 0.8 this option should also have been added:

```js
  legend: true,
```

In fact, the initial idea was to fire that only after clicking on the legend (but I have not yet had the time to implement it..)

**Comment by ZhukDmitry** [comment]
In my case I set 
`
legend: false
`
because I don't need it. And now I haven't legend, but clicking on chart do toggle.

**Comment by Raruto** [comment]
Pull requests are welcome..
