### ISSUE TITLE
How to load this library in v1.0.0?

### ISSUE THREAD

**Issue by starwash** [Raruto/leaflet-elevation#44]
I used 

```
https://unpkg.com/@raruto/leaflet-elevation@1.0.0/leaflet-elevation.js
```

But this file is gone now. 

When I use 

```
https://github.com/Raruto/leaflet-elevation/blob/master/src/leaflet-elevation.js
```

I have an error

```js
TypeError: controlElevation.loadChart is not a function
```

Thanks a lot for the work!

**Comment by Raruto** [comment]
It really depends a lot on how you use this library...

BTW, you can always try the following url to find the correct one:

https://unpkg.com/@raruto/leaflet-elevation

**Comment by fgebhart** [comment]
I found the same behavior. Usually I have something like
```html
<!-- leaflet-elevation -->
<link rel="stylesheet" href="https://unpkg.com/@raruto/leaflet-elevation@latest/leaflet-elevation.css"/>
<script src="https://unpkg.com/@raruto/leaflet-elevation@latest/leaflet-elevation.js"></script>
```
and
```js
var control = L.control.elevation(elevation_options);
```
which gives me (maybe since the new version?):
```
The resource from “https://unpkg.com/@raruto/leaflet-elevation@1.0.1/leaflet-elevation.css” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).
TypeError: L.control.elevation is not a function
```
I think I did not change anything specific. Are you able to reproduce this?

**Comment by Raruto** [comment]
Hi Fabian,

those files have been moved within the `dist` folder:

```html
<!-- leaflet-elevation -->
<link rel="stylesheet" href="https://unpkg.com/@raruto/leaflet-elevation@latest/dist/leaflet-elevation.css"/>
<script src="https://unpkg.com/@raruto/leaflet-elevation@latest/dist/leaflet-elevation.js"></script>
```

Here it is a working example: [leaflet-elevation_i18n-strings.html](https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_i18n-strings.html)

---

If you would use [**npm**](https://www.npmjs.com/) as **network package manager**, the correct ones are those within the `src` folder (see: [package.json](https://unpkg.com/@raruto/leaflet-elevation/package.json) for more info)
