### ISSUE TITLE
Uncaught ReferenceError: d3 is not defined

### ISSUE THREAD

**Issue by fabiodisconzi** [Raruto/leaflet-elevation#45]
In Chrome console appears:

```js
Uncaught ReferenceError: d3 is not defined
    at i._applyData (leaflet-elevation.js:939)
    at i.addData (leaflet-elevation.js:134)
    at i.<anonymous> (leaflet-elevation.js:402)
    at i.fire (leaflet.js:5)
    at i._parse_trkseg (gpx.min.js:1)
    at i._parse_gpx_data (gpx.min.js:1)
    at o (gpx.min.js:1)
    at gpx.min.js:1
```

Many thanks for the valuable work.

**Comment by Raruto** [comment]
Hi Fabio,
the following line is responsible for the lazy loading of that javascript dependency:
https://github.com/Raruto/leaflet-elevation/blob/c56ed4363e9bd0410f7511a11f8f29b503800c02/src/leaflet-elevation.js#L509

If you are working from localhost (i.e. gpx file resides on the same local server) I think there may be problems related to much short gpx download latency.

However, you can always solve by manually including that libraries:

```html
<!-- Leaflet -->
<script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet-src.js"></script>

<!-- D3 -->
<script src="https://unpkg.com/d3@5.15.0/dist/d3.min.js"></script>

<!-- leaflet-gpx -->
<script src="https://unpkg.com/leaflet-gpx@1.5.0/gpx.js"></script>

<!-- leaflet-elevation -->
<link rel="stylesheet" href="https://unpkg.com/@raruto/leaflet-elevation@1.0.1/dist/leaflet-elevation.css" />
<script src="https://unpkg.com/@raruto/leaflet-elevation@1.0.1/dist/leaflet-elevation.js"></script>
```

**Comment by fabiodisconzi** [comment]
Thanks, now the error message is disappear.
But there is another issue: lenght, max eand min elevation are not calculated anymore.
Many thanks!
![Clipboard01](https://user-images.githubusercontent.com/15421089/77571990-86140a00-6ece-11ea-85c3-42c46836156d.jpg)

**Comment by Raruto** [comment]
> But there is another issue: lenght, max eand min elevation are not calculated anymore.

Could you provide additional info?

**Comment by fabiodisconzi** [comment]
Sure. Thanks.
I have not idea why lenght and elevation are not calculated. I apply your awesome plugin in pages like this: [https://www.superskibook.com/ita/forcella-rossa.html](url)
Chrome console doesn't provide any error. I try to understand the leaflet-elevation code but it is too complicatedo for me.
Any suggestion? Thanks, Fabio

**Comment by Raruto** [comment]
> I apply your awesome plugin in pages like this: https://www.superskibook.com/ita/forcella-rossa.html

Nice, if you like it you can also take a look at this other helper plugin: [leaflet-ui](https://github.com/Raruto/leaflet-ui)

Now it should be ok.

https://github.com/Raruto/leaflet-elevation/blob/5f3338d2211ca2ea9bdecdbac78cfa879d6d58c9/src/leaflet-elevation.js#L485
