### ISSUE TITLE
t is undefined error when calling clear() method

### ISSUE THREAD

**Issue by britainbybike** [Raruto/leaflet-elevation#46]
If there is existing GeoJSON data in the control and the **`clear()`** method is called, this error appears.

It appears to be triggered by line [1205](https://github.com/Raruto/leaflet-elevation/blob/9f168e36bc714b4d20b979998258f035834ae16f/src/leaflet-elevation.js#L1205) when **`this._focusG`** tries to set a style, but while the **`this._focusG.style`** object exists, the visibility property is undefined.

```js
if (this._focusG) {
  this._focusG.style("visibility", "hidden");
}
```

Commenting out this line fixes the initial crash, but I don't know what it's purpose is so I guess there may be other side effects to doing so?

For now, I've replaced it with:

```js
if (this._focusG.style.visibility)
  this._focusG.style("visibility", "hidden");
}
```

but whether it ever matches I don't know.

**Comment by Raruto** [comment]
> Commenting out this line fixes the initial crash, but I don't know what it's purpose is so I guess there may be other side effects to doing so?

That is the `svg` group (line + label + text) displayed when the mouse hovers the graph.

> If there is existing GeoJSON data in the control and the **`clear()`** method is called, this error appears.

Could you also provide a concrete example? (I found another problem related to dragging, but nothing about what you say)

**Comment by britainbybike** [comment]
Thanks for your prompt reply. I think I've figured it out - it's my own fault because I'm using your excellent control in a more "creative" way. 

The _clearPath method is failing in my instance, because the control is bound to an existing and more complex GeoJSON path layer (bound with addData), not your default path created by the control using one of the methods like loadGeoJSON(). Therefore it appears the control is trying to hide a path that doesn't exist, or is incomplete..

The loop at line 93 It deletes a single layer successfully for the overlay (appears over the path when the chart is hovered over), but then fails on the next layer, which I presume is the path itself?

My workaround solution is to call just the private method _clearData() instead of the public method clear(), so _clearPath (and _clearChart) are never called.

**Comment by Raruto** [comment]
> it's my own fault because I'm using your excellent control in a more "creative" way.

As you can see the **`addData()`** function is already public, there is nothing strange in using it.

> The loop at **line 93** It deletes a single layer successfully for the overlay (appears over the path when the chart is hovered over), but then fails on the next layer, which I presume is the path itself?

Which loop are you referring to?

This [example](https://jsfiddle.net/omsyz05t/) shows more or less the behavior you described.

**Comment by britainbybike** [comment]
Sorry, that should be 983...
_clearPath: function() {
		this._hidePositionMarker();
		for (let id in this._layers) {
			L.DomUtil.removeClass(this._layers[id]._path, this.options.polyline.className);
			L.DomUtil.removeClass(this._layers[id]._path, this.options.theme);
		}
In the debugger it loops twice, crashing on the second iteration.

**Comment by Raruto** [comment]
> In the debugger it loops twice, crashing on the second iteration.

I would not be wrong, but that loop should only run once per geoJSON track.

Basically it should remove these css classes to the map path:

```html
<path class="elevation-polyline lightblue-theme"></path>
```

**Comment by britainbybike** [comment]
Here's my theory for what it's worth!

In the Fiddle the GeoJSON layer has no custom events or styling. The mouseover event triggers an overlay on the line, which you indicated earlier is the layer than clear is trying to remove the class from?

If there is custom events/styling (as in mine), this layer doesn't appear when the mouse is over the path because the default mouseover event has been overridden.  That's fine as It still appears when there is a mouseover on the graph.  but maybe _focusG hasn't been created, or the class not applied? 

Therefore when trying to clean up without checking first that it exists, we get the error. Looks like that's all it needs to do,

**Comment by Raruto** [comment]
Without a concrete example it is difficult to know ...

**Comment by britainbybike** [comment]
True. Not a big deal as far as I am concerned, because the workaround works OK. I just thought it might help someone else who might encounter the same problem.
If you're interested, www.britainbybike.com (not currently complete or 24/7)
