### ISSUE TITLE
Empty GPX track data

### ISSUE THREAD

**Issue by voodoosnares** [Raruto/leaflet-elevation#48]
I have successfully loaded data from gpx and got all required info on website, however, i am trying to get data graph graph to put it as addition info on other place on page with:

```js
map.on('eledata_loaded', function(e) {
  var track = e.track_info;

  console.log(track)
  console.log(track.distance)

  $('.distance').innerHTML = track.distance.toFixed(2) + " km";
  $('.elevation-gain').innerHTML = track.ele.toFixed(0) + " m";
});
```

I receive empty HTML with console log:

```js
{distance: 0, elevation_max: 0, elevation_min: 0, type: "gpx", name: "Test GPX"}
```
I am not sure why it wont detect track_info.

Also, is there possibility to get addition info from track like in original [leaflet-gpx](https://github.com/mpetazzoni/leaflet-gpx) plugin

for example: **Cumulative Elevation Gain and Loss** (not min and max)

Regards

**Comment by Raruto** [comment]
Hi Beverica,

> I have successfully loaded data from gpx and got all required info on website, however, i am trying to get data graph graph to put it as addition info on other place on page with

Can you show a more complete example (or at least a working one)?

> I receive empty HTML with console log:

It is likely that this function is called too early:

https://github.com/Raruto/leaflet-elevation/blob/51b45aa58dc426849fd78fa841352417699bc564/src/leaflet-elevation.js#L399

> Also, is there possibility to get addition info from track like in original [leaflet-gpx](https://github.com/mpetazzoni/leaflet-gpx) plugin

If you load your gpx file in this way, this it should be the correct way to get your data:

```js
var el = new L.Control.Elevation().addTo(map);
var gpx = new L.GPX("./mytrack.gpx", {async: true});
gpx.on("addline", function(e) {
  el.addData(e.line);

  // leaflet-gpx.js
  console.log(gpx.get_elevation_gain());
  console.log(gpx.get_elevation_loss());
  console.log(gpx.get_distance());
  console.log(gpx.get_name());
  console.log(gpx.get_elevation_min());
  console.log(gpx.get_elevation_max());

  // leaflet-elevation.js
  console.log(el.track_info);
});
gpx.addTo(map);
```

> for example: Cumulative Elevation Gain and Loss (not min and max)

If you also want to show them you will have to build your custom "summary" panel (because at the moment this library does not show / calculate them in the default one).

_Have a nice Day,
Raruto_

**Comment by voodoosnares** [comment]
Hi, my js looks like this:
p.s. i am showing map in bootstrap modal.

const raceInfoModal = $("#raceInfo");
const _loaderInner = raceInfoModal.find('.i-load');

function loadMap() {
    const mapOptions = {
        elevationControl: {
            url: gpxFile,
            options: {
                theme: "purple-theme",
                detached: true,
                elevationDiv: "#elevation-div",
                summary: 'line',
                legend: false,
                useLeafletMarker: true,
                polyline_options: {
                    color: '#7366a9',
                    opacity: 0.75,
                    weight: 3,
                    lineCap: 'round'
                },
                gpxOptions: {
                    async: true,
                    marker_options: {
                        startIconUrl: './vue/app-assets/images/leaflet/gpx/pin-icon-start.png',
                        endIconUrl: './vue/app-assets/images/leaflet/gpx/pin-icon-end.png',
                        shadowUrl: './vue/app-assets/images/leaflet/gpx/pin-shadow.png',
                        wptIcons: {
                            '': L.divIcon({
                                className: 'elevation-waypoint-marker',
                                html: '<i class="elevation-waypoint-icon"></i>',
                                iconSize: [30, 30],
                                iconAnchor: [8, 30],
                            })
                        },
                        wptIconUrls: {
                            '': './vue/app-assets/images/leaflet/gpx/pin-icon-wpt.png',
                        }
                    }
                }
            }
        }
    };

    var map = new L.Map('gpxMap', mapOptions.map);
    const controlElevation = L.control.elevation(mapOptions.elevationControl.options);
    controlElevation.load(mapOptions.elevationControl.url);
    controlElevation.addTo(map);

    // Get Track Data
    // map.on('eledata_loaded', function(e) {
    //     var track = e.track_info;
    //
    //     console.log(track)
    //     console.log(track.distance)
    //
    // });

    L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: 'Map &copy; <a href="http://www.osm.org">OSM</a>'
    }).addTo(map);

    const elevationTranslate = {
        "Total Length: ": "Distanca: ",
        "Max Elevation: ": "Max Visinska: ",
        "Min Elevation: ": "Min Visinska: ",
        "Download": "Preuzmi GPX",
    };
    L.registerLocale('rs', elevationTranslate);
    L.setLocale('rs');

    // Refresh map in modal
    map.on('load', function (event) {
        _loaderInner.show();
    });
    raceInfoModal.on("shown.bs.modal", function () {
        setTimeout(() => {
            map.invalidateSize();
        }, 10);
        _loaderInner.hide();
    });
}

$(window).on("load", function () {
    loadMap();
});

**Comment by Raruto** [comment]
1. Did you also try what was said before?

```js
var el = new L.Control.Elevation().addTo(map);
var gpx = new L.GPX("./mytrack.gpx", {async: true});

gpx.on("addline", function(e) {
  // Populate elevation graph
  el.addData(e.line);

  // leaflet-gpx.js
  console.log(gpx.get_elevation_gain());
  console.log(gpx.get_elevation_loss());
  console.log(gpx.get_distance());
  console.log(gpx.get_name());
  console.log(gpx.get_elevation_min());
  console.log(gpx.get_elevation_max());

  // leaflet-elevation.js
  console.log(el.track_info);
});
gpx.addTo(map);
```

---

2. Are there similar problems if you try to load your gpx file [here](https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_upload-gpx.html)?

---

3. Did you try to listen earlier for the `'eledata_loaded'` event?

```js
// Init Control
const controlElevation = L.control.elevation(mapOptions.elevationControl.options);

// Wait for GPX load
controlElevation.on('eledata_loaded', function(e) {
  var track = e.track_info;
  
  console.log(track)
  console.log(track.distance)
});

// Load GPX
controlElevation.load(mapOptions.elevationControl.url);
controlElevation.addTo(map);
```

---

4. Does it work if you try to use this other [sample](https://raruto.github.io/leaflet-elevation/examples/via-emilia.gpx) file?

---

_Happy Coding,
Raruto_

**Comment by voodoosnares** [comment]
I have managed to make it work with your instructions! Problem was early call.

Thanks
