### ISSUE TITLE
QGIS integration

### ISSUE THREAD

**Issue by Raruto** [Raruto/leaflet-elevation#5]
I'm not a QGIS programming expert, but it seems feasible...

**Comment by ghtmtt** [comment]
Hi @Raruto 

> I'm not a QGIS programming expert, but it seems feasible...

well, I am :)

But I'm definitely not a js developer and luckily you are.

What I have in mind is a very simple plugin where the user can choose: 

* vector file (`gpx` or `geojson`)
* different OSM tiles
* some simple customization (like line color, profile color)
* whether to show also some statistics (total length of the path, total elevation)

Finally, one single html file is created with the link to the vector file (we can also choose to export a folder with the `html` file and a copy of the original vector layer). 

Writing a plugin in QGIS is pure python, so basically it is a kind of search & replace text into a template we can ship we the plugin that contains all the user customization.

What do you think?

**Comment by Raruto** [comment]
if I understand correctly this is more or less what you need...

```html
<html>

<body>

	<div id="map"></div>
	<div id="elevation-div" class="leaflet-control elevation"></div>

	<script>
		
		var opts = {{ py_opts }}; // Your QGIS options here...
		
		var map = new L.Map('map', opts.map);

		var baseLayers = {{ py_layers }}; // Your QGIS layers here...		

		// Load all the user selected layers.
		for (var layer in baseLayers) {
			baseLayers[layer] = new L.TileLayer(opts[layer].url, opts[layer].options);
		}

		var controlZoom = new L.Control.Zoom(opts.zoomControl);
		var controlElevation = L.control.elevation(opts.elevationControl.options);
		var controlLayer = L.control.layers(baseLayers, null, opts.layersControl.options);

		controlZoom.addTo(map);
		controlLayer.addTo(map);
		controlElevation.loadGPX(map, opts.elevationControl.url);

		// Activate one of the user selected layer.
		map.addLayer(baseLayers[opts.activeLayer]);

		// Add the gpx layer as “toggable” layer
		controlElevation.gpx.on('loaded', function(e) {
			controlLayer.addOverlay(controlElevation.gpx, controlElevation.gpx.get_name());
		});

		// and so on...
      
	</script>

</body>

</html>
```

based on [this](https://raruto.github.io/examples/leaflet-elevation/leaflet-elevation.html) example.

**Comment by ghtmtt** [comment]
Thanks @Raruto for the template. I'll try to work on the plugin ASAP.

> var baseLayers = {{ py_layers }

well this could be the tricky part. QGIS read all the layers as `QgsVectorLayer` and can return some different objects (`asGml`, `asJson`...). But I'm discovering that the geoJson conversion (from gpx) is not keeping the Z value (QGIS current limitation maybe).

Basically something like that:

![image](https://user-images.githubusercontent.com/2884884/57193744-f0326200-6f3e-11e9-8c46-dcce80c94c4c.png)

**Comment by Raruto** [comment]
from the C++ [QGSI API reference](https://qgis.org/api/classQgsLineString.html#ac810dd82548f50515a59cdf241986efc) (i think that the python API should be similar):
```c++
 QString QgsLineString::asJson( int precision ) const
 {
   QgsPointSequence pts;
   points( pts );
 
   return "{\"type\": \"LineString\", \"coordinates\": " + QgsGeometryUtils::pointsToJSON( pts, precision ) + '}';
 }
```

```c++
 QString QgsGeometryUtils::pointsToJSON( const QgsPointSequence &points, int precision )
 {
   QString json = QStringLiteral( "[ " );
   for ( const QgsPoint &p : points )
   {
     json += '[' + qgsDoubleToString( p.x(), precision ) + QLatin1String( ", " ) + qgsDoubleToString( p.y(), precision ) + QLatin1String( "], " );
   }
   if ( json.endsWith( QLatin1String( ", " ) ) )
   {
     json.chop( 2 ); // Remove last ", "
   }
   json += ']';
   return json;
 }
```
The `p.z()` propriety is never used, maybe, because a valid geojson file doesn't require an elevation value...

**Comment by ghtmtt** [comment]
mmm nope, without the `z` value it seems not working. But nevermind, I'll write a function that will do the job.

**Comment by ghtmtt** [comment]
OK what we are looking for is the `QgsGeometry.asJson` function. This renders a valid (geo)json string with z value (if z value is there, if not we have some other algorithm in QGIS that the final user can use).

Now, before starting to work on the main framework. Most users load shapefiles in QGIS, is your library capable of taking a json string *on the fly* to render? In other words, in your examples (both gpx and geojson) you load directly a remote url:

```
elevationControl: {
        url: "https://raruto.github.io/examples/leaflet-elevation/demo.geojson",
        options: {
```

or a local file.

Would it be possible to pass directly a json string in the url parameter like:

```
for i in vl.getFeatures():
	i.geometry().asJson()
'{"coordinates": [11.8989272,46.7843967,807.0],
....
```

?

We can then think to different options:

1. user has remote url with gpx or geojson
2. user has local gpx or geojson files (in the same folder of the html? Is it possible to specify different locations?)
3. QGIS will directly handle the vector layer geometry (whatever the format is) and write a string in the file in order to ship an unique `html` file

**Comment by Raruto** [comment]
in version [0.2.0](https://github.com/Raruto/leaflet-elevation/tree/8894ee719f9511b77665fb41e2bdbf3031b2c2c5) I have partially rewritten the library to be also able to manage the direct input of data, so this is how your template should look like now:

```html
<html>

<body>

	<div id="map"></div>
	<div id="elevation-div" class="leaflet-control elevation"></div>

	<script>
		
		var opts = {{ py_opts }}; // Your QGIS options here...
		
		var map = new L.Map('map', opts.map);

		var baseLayers = {{ py_layers }}; // Your QGIS layers here...		

		// Load all the user selected layers.
		for (var layer in baseLayers) {
		    baseLayers[layer] = new L.TileLayer(opts[layer].url, opts[layer].options);
		}

		var controlZoom = new L.Control.Zoom(opts.zoomControl);
		var controlElevation = L.control.elevation(opts.elevationControl.options);
		var controlLayer = L.control.layers(baseLayers, null, opts.layersControl.options);

		controlZoom.addTo(map);
		controlLayer.addTo(map);

		// Attach your elevation control to the map
		controlElevation.loadChart(map); 

		// Fetch your gpx/geojson data as "url" or "object"
		controlElevation.loadData(opts.elevationControl.data_url);

		// Activate one of the user selected layer.
		map.addLayer(baseLayers[opts.activeLayer]);

		// Add the gpx/geojson layer as “toggable” layer
		map.on('eledata_loaded', function(e) {
		    controlLayer.addOverlay(e.layer, e.name);
		});

		// and so on...
      
	</script>

</body>

</html>
```

---

> 2. user has local gpx or geojson files (**in the same folder of the html?**)

I haven't tested it, but I think that relative locations (eg "../data/demo.geojson") shouldn't cause problems...

> 2. user has local gpx or geojson files (**Is it possible to specify different locations?**)

if you intend "viewing multiple files at once" there is a [basic example](https://raruto.github.io/examples/leaflet-elevation/leaflet-elevation_multiple-tracks.html)

**Comment by ghtmtt** [comment]
I've started the plugin framework here https://gitlab.com/faunalia/qgis-leaflet-elevation (sorry but we have almost all repo on gitlab, is it a problem for you?).

The plugin works nice within QGIS (using your the geojson template https://raruto.github.io/examples/leaflet-elevation/leaflet-elevation_geojson-data.html) but only if the path is taken from a remote url, if the gejson (or gpx) is on the local disk, then the map appear but with an empty profile (this happens also directly in Qt Designer):

**Local file** (html and geojson in the same dir of the ui file)

![image](https://user-images.githubusercontent.com/2884884/57842323-87fc3f80-77cc-11e9-9a2f-ee744cdf6aaf.png)

**With your remote url**

![image](https://user-images.githubusercontent.com/2884884/57842388-ac581c00-77cc-11e9-9841-fef313550fc9.png)

**Comment by ghtmtt** [comment]
Just for testing, supposing to have a local `html` that load a local `geojson`, this is the python code to create the `QWebView` ready to go (also outside QGIS):

```
from PyQt5.QtWebKit import QWebSettings
from PyQt5.QtWebKitWidgets import *
from PyQt5.QtCore import QUrl


map_view = QWebView()
map_view_settings = map_view.settings()
map_view_settings.setAttribute(QWebSettings.WebGLEnabled, True)
map_view_settings.setAttribute(QWebSettings.DeveloperExtrasEnabled, True)
map_view_settings.setAttribute(QWebSettings.Accelerated2dCanvasEnabled, True)

local_path = '/home/matteo/leaflet-elevation_geojson-data.html'

map_view_url = QUrl.fromLocalFile(local_path)
map_view.load(map_view_url)
map_view.show()

```

**Comment by Raruto** [comment]
I am the same [Raruto](https://gitlab.com/Raruto) also on gitlab.

---

Modern browsers don't allow you to load local files unless you enable that with certain flags (eg. for [chrome / chromium](http://www.chrome-allow-file-access-from-file.com/), but a better solution could perhaps be to use a localhost python web server...)

---

From the official leaflet docs ([#1](https://leafletjs.com/examples/geojson/), and [#2](https://leafletjs.com/examples/choropleth/)), to be sure that the geojson file will be loaded at the same way both locally and from the remote server, they always use the alternative solution of an external .js file containing a global variable with all the necessary geojson data.

**geojson.js**
```javascript
var geojsonFeature = {
    "type": "Feature",
    "properties": {
        "name": "Coors Field",
        "amenity": "Baseball Stadium",
        "popupContent": "This is where the Rockies play!"
    },
    "geometry": {
        "type": "Point",
        "coordinates": [-104.99404, 39.75621]
    }
};
```

And here's how it should be used in version [0.2.2](https://github.com/Raruto/leaflet-elevation/tree/0.2.2)

```javascript
controlElevation.loadData(JSON.stringify(geojsonFeature)); // in the near future I will remove the need of the "stringify" part
```

---

**PS** are you sure to use [here](https://gitlab.com/faunalia/qgis-leaflet-elevation/blob/master/leaflet-elevation_geojson-data.html) the latest version available?

**Comment by ghtmtt** [comment]
> PS are you sure to use here the latest version available?

now yes ;) and it works nice with `gpx` files.

Do you have a working template of the last version with a `geojson` file? So I can try to understand if the `toJson` method of QGIS works or if it needs some tweaks.

Thanks!

**Comment by Raruto** [comment]
> now yes ;) and it works nice with gpx files.

Have you also tried to load a local file with a chrome browser?

---

> Do you have a working template of the last version with a geojson file? So I can try to understand if the toJson method of QGIS works or if it needs some tweaks.

From version 0.2.x you can just use the `controlElevation.loadData(<gpx/geojson>);` to display both types of elevation data.

---

Here is an [example](https://raruto.github.io/examples/leaflet-elevation/leaflet-elevation_string-data.html) which shows how to load data directly from a javascript string (from 0.2.4 it should also work with xml/json objects too).

---

And this should be the updated template:

```html
<html>

<body>

	<div id="map"></div>
	<div id="elevation-div" class="leaflet-control elevation"></div>

	<div id="data-summary" class="data-summary"><span class="totlen"><span class="summarylabel">Total Length: </span><span class="summaryvalue">0</span></span> &mdash; <span class="maxele"><span class="summarylabel">Max Elevation: </span><span class="summaryvalue">0</span></span>
    &mdash; <span class="minele"><span class="summarylabel">Min Elevation: </span><span class="summaryvalue">0</span></span></div>

	<script>
		
		var opts = {{ py_opts }}; // Your QGIS options here...
		
		var map = new L.Map('map', opts.map);

		var baseLayers = {{ py_layers }}; // Your QGIS layers here...		

		// Load all the user selected layers.
		for (var layer in baseLayers) {
		    baseLayers[layer] = new L.TileLayer(opts[layer].url, opts[layer].options);
		}

		var controlZoom = new L.Control.Zoom(opts.zoomControl);
		var controlElevation = L.control.elevation(opts.elevationControl.options);
		var controlLayer = L.control.layers(baseLayers, null, opts.layersControl.options);

		controlZoom.addTo(map);
		controlLayer.addTo(map);

		// Attach your elevation control to the map
		controlElevation.loadChart(map); 

		// Activate one of the user selected layer.
		map.addLayer(baseLayers[opts.activeLayer]);

		// Add the geojson/gpx layer as “toggable” layer and update track statistics
		// NB. it is always better to attach this event before the "loadData" function
		map.on('eledata_loaded', function(e) {
		    var q = document.querySelector.bind(document);
		    var track = e.track_info;

		    controlLayer.addOverlay(e.layer, e.name);

		    q('.totlen .summaryvalue').innerHTML = track.distance.toFixed(2) + " km";
		    q('.maxele .summaryvalue').innerHTML = track.elevation_max.toFixed(2) + " m";
		    q('.minele .summaryvalue').innerHTML = track.elevation_min.toFixed(2) + " m";
		});

		// Fetch your gpx/geojson data as "url", "string" or "object"
		controlElevation.loadData(opts.elevationControl.data);

	</script>

</body>

</html>
```

**Comment by ghtmtt** [comment]
> Have you also tried to load a local file with a chrome browser?

with you last addition that allows to load directly geojson strings no.. QGIS reads all the layers loaded as `QgsVectorLayer`. Therefore it doesn't matter to load local files. I'm writing a function that converts *on the fly* a `QgsVectorLayer` in the correct object

> Here is an example which shows how to load data directly from a javascript string (from 0.2.4 it should also work with xml/json objects too).

that's really really awesome, thanks! The first skeleton of the plugin is ready.

**Comment by ghtmtt** [comment]
First prototype is working nice: https://gitlab.com/faunalia/qgis-leaflet-elevation/tree/master

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2884884/57919364-f8709280-7898-11e9-81c0-e6f3b6108829.gif)

**Comment by Raruto** [comment]
> QGIS reads all the layers loaded as QgsVectorLayer. Therefore it doesn't matter to load local files. I'm writing a function that converts on the fly a QgsVectorLayer in the correct object

Ok, however I think that in the future it might be useful to add an option / button that allows the user to decide how to export the geojson + html files (such as "complete web page" or "single html file").

> First prototype is working nice: https://gitlab.com/faunalia/qgis-leaflet-elevation/tree/master

Good to know.

Perhaps, [here](https://gitlab.com/faunalia/qgis-leaflet-elevation/blob/master/leaflet_elevation_dialog.py#L80) it wouldn't be better to work directly with python obejcts and then inject them into the javascript as json variables (like that `var opts = {{ py_opts }};`, eg. from the [w3schools](https://www.w3schools.com/python/python_json.asp))?

**Comment by ghtmtt** [comment]
> Ok, however I think that in the future it might be useful to add an option / button that allows the user to decide how to export the geojson + html files (such as "complete web page" or "single html file").

so as single html like now and html + geojson (so a folder with 2 files)?

> Perhaps, here it wouldn't be better to work directly with python obejcts and then inject them into the javascript as json variables (like that var opts = {{ py_opts }};, eg. from the w3schools)?

mmm.. I know that the current function is a little bit tricky, but even if I inject the json dump of the returing `asJson` of QGIS, something gets wrong during the parsing of the string. 

Another current limitation if with multipart multilinestrings (working on that to find a way to manage also this geometries).

**Comment by Raruto** [comment]
> so as single html like now and html + geojson (so a folder with 2 files)?

Yes

> mmm.. I know that the current function is a little bit tricky, but even if I inject the json dump of the returing asJson of QGIS, something gets wrong during the parsing of the string.

This is more or less what I thought

```python
import json

# Your QGIS options:

  opts = {
    "map": {
      "center": [41.4583, 12.7059],
      "zoom": 5,
      "markerZoomAnimation": false,
      "zoomControl": false,
    },
    "zoomControl": {
      "position": 'topleft',
    },
    "elevationControl": {
      "data": 'https://raruto.github.io/examples/leaflet-elevation/via-emilia.gpx', # sample data placeholder
      "options": {
        "position": 'topleft',
        "theme": 'lime-theme',
        "useHeightIndicator": true,
        "collapsed": false,
        "detachedView": true,
        "elevationDiv": '#elevation-div',
      },
    },
    "layersControl": {
      "options": {
        "collapsed": false,
      },
    },
  };

...

# Your QGIS geojson data function:

  vlayer = self.layer_combo.currentLayer();

  data = '''{{"name":"{layer}", "type":"FeatureCollection","features": ['''.format(layer=vlayer.name());

  for i in vlayer.getFeatures():
      g = i.geometry().constParts();
      data += '{ "type": "Feature", "properties": { }, "geometry": { "type": "MultiLineString", "coordinates": [ ['
      for part in g:
          for coord in part.vertices():
              data += ' [ {}, {},{} ],'.format(coord.x(), coord.y(), coord.z());

          data = data[:-1];

      data += ']] } },';

  data = data[:-1];
  data += ''']}''';

...

# update geojson data to your QGIS options:

  json_opts["elevationControl"]["data"] = data;

...

# read your html template file

  self.fin = self.leaftemplate
  self.fout = os.path.join(os.path.dirname(__file__), 'template.html')

  with open(self.fin, 'r') as fi:
      lines = fi.readlines()

  for i, j in enumerate(lines):
      if '{{ py_opts }}' in j: # search for '{{ py_opts }}' placeholder
          dataidx = i+1

  json_opts = json.dumps(opts); # convert into JSON String:

  lines[dataidx] = 'var opts = ' + json_opts + ';';

...

```

> Another current limitation if with multipart multilinestrings (working on that to find a way to manage also this geometries).

If I am not mistaken the library doesn't manage too "multi-track" gpses

**Comment by ghtmtt** [comment]
I reworked the code as you suggested (definitely a better approach): https://gitlab.com/faunalia/qgis-leaflet-elevation/commits/master

> If I am not mistaken the library doesn't manage too "multi-track" gpses

I managed a way directly in QGIS, tested with different gpx tracks (with multi linestrings) and it works nice

What is still missing, as I pointed out in the issue on gitlab https://gitlab.com/faunalia/qgis-leaflet-elevation/issues/2 is what could be the best way to made (small) customization (basically line and profile color).

**Comment by Raruto** [comment]
> I managed a way directly in QGIS, tested with different gpx tracks (with multi linestrings) and it works nice

Ok, good to know it.

**Comment by Raruto** [comment]
- **QGIS Plugin:** [track_profile_2_web](http://planet.qgis.org/plugins/track_profile_2_web/) (released on 4 May 2019)
- **Github Code:** [trackprofile2web](https://github.com/faunalia/trackprofile2web)
- **Example Page:** [faunalia.eu](https://www.faunalia.eu/en/dev/trackprofile2web)

for more info: https://github.com/faunalia/trackprofile2web/issues
