### ISSUE TITLE
Add Speed, Heart rate in the graph

### ISSUE THREAD

**Issue by elecoest** [Raruto/leaflet-elevation#51]
Based on : https://fr.wordpress.org/plugins/wp-gpx-maps/

What do you think about the fact to add Speed, Heart rate in the graph (of course if thes informations are available in gpx file)

_Manu_

**Comment by Raruto** [comment]
Hi Emmaunel,

as I mentioned here: https://github.com/Raruto/leaflet-elevation/issues/18#issuecomment-536332704

> do you have a summary with elevation gain, loss and if possible time and speed ?

Currently no, but you can still build your custom one:

```js
map.on('eledata_loaded', function(e) {
   var q = document.querySelector.bind(document);
   var track = e.track_info;
   var layer = e.layer;

   // Default summary info
   q('.totlen .summaryvalue').innerHTML = track.distance.toFixed(2) + " km";
   q('.maxele .summaryvalue').innerHTML = track.elevation_max.toFixed(2) + " m";
   q('.minele .summaryvalue').innerHTML = track.elevation_min.toFixed(2) + " m";

   // Advanced summary info
   layer.get_name(); // name of the GPX track
   layer.get_distance(); // total track distance [meters]
   layer.get_start_time(); // start time [Date object]
   layer.get_end_time(); // end time when the last point was recorded [Date object]
   layer.get_moving_time(); // moving time [milliseconds]
   layer.get_total_time(); // total track time [milliseconds]
   layer.get_moving_pace(); // average moving pace [milliseconds / km]
   layer.get_moving_speed(); // average moving speed [km / hour]
   layer.get_total_speed(); // average total speed [km / hour]
   layer.get_elevation_min(); // lowest elevation [meters]
   layer.get_elevation_max(); // highest elevation [meters]
   layer.get_elevation_gain(); // cumulative elevation gain [meters]
   layer.get_elevation_loss(); // cumulative elevation loss [meters]
   layer.get_average_hr(); // average heart rate (if available)
   layer.get_average_cadence(); // average cadence (if available)
   layer.get_average_temp(); // average of the temperature (if available)


});
```
Or can you also try submitting a pull request with all desired changes...

**Further info and details:**
- leaflet-gpx: [available functions](https://github.com/mpetazzoni/leaflet-gpx#available-functions)
- MPettazoni: [gpx example](http://mpetazzoni.github.io/leaflet-gpx/)
- Raruto: [custom summary](https://raruto.github.io/examples/leaflet-elevation/leaflet-elevation.html)

----

... and here https://github.com/Raruto/leaflet-elevation/issues/43#issuecomment-596156570

> it would be possible to somehow add additional plots for more activity data, e.g. heart rate, pace, speed, temperature ... ?

This is an interesting feature, but it requires a certain level of study and knowledge of this plugin, d3js and the leaflet ecosystem. Nothing too much complicated, but it's something that can take a while before it can be released.

As usual, help and pull requests are welcome.

---

> Based on : https://fr.wordpress.org/plugins/wp-gpx-maps/

**PS** did you know that @bastianonm also provides a [standalone](https://devfarm.it/forums/topic/sample-wrapper/) wrapper?

_Have nice day,
Raruto_
