### ISSUE TITLE
Add Elevation Gain / Loss in the gpxgroup summary

### ISSUE THREAD

**Issue by elecoest** [Raruto/leaflet-elevation#53]
Hello raruto,

I tested your example : 
https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_hoverable-tracks.html

and I setted distanceMarkers to true to display distance. As you can test, the result seems like "unstable" : the track is selected but without any chang on color and distance not be displayed. or display distance, I must click on the track.

```js
var routes = L.gpxGroup(tracks, {
            points: points,
            points_options: opts.points.options,
            elevation: true,
            elevation_options: {
                theme: "lightblue-theme",
                detachedView: true,
                elevationDiv: '#elevation-div',
                followPositionMarker: true,
                zFollow: 15,
            },
            legend: true,
            distanceMarkers: true, // <-- set distanceMarkers to true to display distance
        });

```

**Comment by Raruto** [comment]
Hi Emmanuel,

I tried what you say but I don't seem to find any noteworthy error...

_Greetings,
Raruto_

**Comment by elecoest** [comment]
I'm really sorry, it's a mistake by me. The error is the way to get custom information from gpx file : 

            // Custom Summary info
            //q('.gain .summaryvalue').innerHTML = "+" + layer.get_elevation_gain().toFixed(2) + " m";

it's not layer because, in this case it's a track. but how can e retrieve this information ?

**Comment by Raruto** [comment]
I think you might need such a thing

```js
routes.on('selection_changed', function(e) {
  var q = document.querySelector.bind(document);
  var track = this.getSelection(); // <-- retrieve current gpx layer

  // Custom Summary info
  q('.totlen .summaryvalue').innerHTML = track.get_distance().toFixed(2) + " km";
  q('.maxele .summaryvalue').innerHTML = track.get_elevation_max().toFixed(2) + " m";
  q('.minele .summaryvalue').innerHTML = track.get_elevation_min().toFixed(2) + " m";
  q('.gain .summaryvalue').innerHTML = track.get_elevation_gain().toFixed(2) + " m";
  q('.loss .summaryvalue').innerHTML = track.get_elevation_loss().toFixed(2) + " m";
});
```

Search for the [**L.Mixin.Selection**](https://github.com/Raruto/leaflet-elevation/blob/cbc8cdae15973c9f50cd8407afc05edde5c0daa9/libs/leaflet-gpxgroup.js#L42) for more info about the [**selection_changed**](https://github.com/Raruto/leaflet-elevation/blob/cbc8cdae15973c9f50cd8407afc05edde5c0daa9/libs/leaflet-gpxgroup.js#L177) event.

**Comment by elecoest** [comment]
many thanks.
