### ISSUE TITLE
Add downloadLink in the gpxgroup summary

### ISSUE THREAD

**Issue by elecoest** [Raruto/leaflet-elevation#54]
Hi raruto,

It's possible to display your downloadLink in the GpxGroup "mode" ?

I tried to set **`downloadLink: true`** but it's not work :)

Thanks.

**Comment by Raruto** [comment]
Hi Emmanuel,

based on [this](https://github.com/Raruto/leaflet-elevation/issues/52#issuecomment-632360023) and [this](https://github.com/Raruto/leaflet-elevation/issues/53#issuecomment-634558973), there is literally nothing you can't actually build by yourself :)

```html
<div id="gpx-summary" class="gpx-summary">

 <span class="download"><a href="#">Download</a></span>

</div> <!-- .gpx-summary -->
```

```js
routes.on('selection_changed', function(e) {
  var q = document.querySelector.bind(document);
  var track = this.getSelection(); // <-- retrieve current gpx layer

  q('.download > a').href = 'data:application/gpx+xml;charset=utf-8,' + encodeURIComponent(track._gpx);
  q('.download > a').download = track.get_name() + ".gpx"; // fileName
});
```

_Greetings,
Raruto_

**Comment by elecoest** [comment]
very well, you're the best on this :)
