### ISSUE TITLE
Integration with Angular 8+

### ISSUE THREAD

**Issue by vishalprajapati7072** [Raruto/leaflet-elevation#57]
Not an issue but just wanted to know that is there any way to integrate the leaflet-elevation plugin in angular 8 project.

Or any plans on integration in angular 8+.

Highly appreciated if you help me on this.

**Comment by Raruto** [comment]
I don't use angular, but I recommend you take a look at these startup guides:

- https://asymmetrik.com/ngx-leaflet-and-leaflet-plugins/
- https://github.com/Asymmetrik/ngx-leaflet/#getting-help
