### ISSUE TITLE
TypeError: layer.getElement is not a function

### ISSUE THREAD

**Issue by gegeweb** [Raruto/leaflet-elevation#65]
As discuted in #64, i've now this error:
`TypeError: i.getElement is not a function` at `control.js:517:22`

I do that, with data and an existing layer (`FeatureGroup`) already on the map,

first I add the control to the map, and hide it, at this time no data, no layers.
```js
elevationControl.addTo(map).hide();
```
And when the data is ready, and the layer added on the map:
```js
.on('routeselected', function(e) {
	elevationControl.clear();
	elevationControl.addData(L.GeoJSON.asFeature(e.route.coordinates), controlRouting.getLine());
```

This is caused by the call of the function called at `onAdd`:
```js
	_initLayer: function() {
		this._layers
			.on('layeradd layerremove', (e) => {
				let layer = e.layer
				let toggleClass = e.type == 'layeradd' ? _.addClass : _.removeClass;
				let toggleEvt = layer[e.type == 'layeradd' ? "on" : "off"].bind(layer);
				toggleClass(layer.getElement(), this.options.polyline.className + ' ' + this.options.theme);
				toggleEvt("mousemove", this._mousemoveLayerHandler, this)
				toggleEvt("mouseout", this._mouseoutHandler, this);
			});
	},
```

I'll try to add and remove the control to the map when needed, after updating data and binding with the layer…

**Comment by gegeweb** [comment]
If I do
```js
	.on('routeselected', function(e) {
				if (elevationControl._map) elevationControl.clear();
				//elevationControl.addData(L.GeoJSON.asFeature(e.route.coordinates), controlRouting.getLine());
				elevationControl.addData(L.polyline(e.route.coordinates).toGeoJSON(), controlRouting.getLine());
				//if (elevationControl._container.style.display === "none") elevationControl.show();
				map.addControl(elevationControl);
```
i got `Unsopperted GeoJSON feature geometry type:undefined` at `control.js:332:13`

the both 
```js
elevationControl.addData(L.GeoJSON.asFeature(e.route.coordinates), controlRouting.getLine());
```
or
```js
elevationControl.addData(L.polyline(e.route.coordinates).toGeoJSON(), controlRouting.getLine());
```
got this error.

**Comment by gegeweb** [comment]
Sorry!
I haven't reloaded!

This works:
```js
			.on('routeselected', function(e) {
				console.log(L.polyline(e.route.coordinates).toGeoJSON())
				if (elevationControl._map) elevationControl.clear();
				elevationControl.addData(L.polyline(e.route.coordinates).toGeoJSON(), controlRouting.getLine());
				map.addControl(elevationControl);
```
But now, event `mousemove`or `mouseout`on the original feature aren't fired.

And this:
```js
L.GeoJSON.asFeature(e.route.coordinates)
```
doesn't works.

**Comment by gegeweb** [comment]
Doesn't works as expected.
First time it is OK, but if y remove control (after clearing route, no data to display), the i got:
`i.getElement is not a function` at `control.js:517:22`

Everything was working well before this last commit on master and my little patch to test the existence of `this._layers`.

**Comment by gegeweb** [comment]
Trying to fix it by doing that:

```js
	_addLayer: function(layer) {
		// try to fix #65 when layer binded is already a Feature or Layer Group
		// This works but mousemove and mouseout event are always deleted from the
		// original layer
		if (layer) {
			if (typeof layer.getLayers === 'function') this._layers = layer;
			else this._layers.addLayer(layer)
		}
	},
```

It works for me (I don't know if there are side effects), but I don't understand why the `mousemove` and `mouseout` events are removed from the original layer.

**Comment by Raruto** [comment]
I'm still working on a general "restyling" of code, however I think that after this [commit](https://github.com/Raruto/leaflet-elevation/commit/212b56769d26f23162a5cd44a6edf32e539df596) should be ok.

**Comment by gegeweb** [comment]
> I'm still working on a general "restyling" of code, however I think that after this [commit](https://github.com/Raruto/leaflet-elevation/commit/212b56769d26f23162a5cd44a6edf32e539df596) should be ok.

Yes that's OK for the error.

But not for following mouse position. First point is always highlighted.

<img width="1440" alt="Capture d’écran 2020-06-17 à 17 17 50" src="https://user-images.githubusercontent.com/9108457/84916783-cc889780-b0be-11ea-9fe4-8f407dfad7e7.png">

**Comment by gegeweb** [comment]
So I hope you'll find a way to deal with layers that are already groups!

I've been looking for a solution, but I can't work out how to do it...

The old version works, so I'll come back later... I'll take care of the other evolutions of my application. ;)

**Comment by Raruto** [comment]
**Version [1.2.3](https://www.npmjs.com/package/@raruto/leaflet-elevation/v/1.2.3)** should fix it.

**Comment by gegeweb** [comment]
> **Version [1.2.3](https://www.npmjs.com/package/@raruto/leaflet-elevation/v/1.2.3)** should fix it.

Yes, works fine now. Thanks!
I've build from master.

Out of curiosity, what fixed the problem?

Otherwise I had found a solution, not bind the layer and fireing the events and call the functions `_mousemoveLayerHandler`and `_mouseoutHandler`on my side.

**Comment by Raruto** [comment]
I had tried to use a more efficient searching algorithm (i.e. latlng layer to chart point) , but I had forgotten that bisect can't be used on "unsorted" arrays (or at least not so easily..)

https://github.com/Raruto/leaflet-elevation/commit/82bb073f23b57dcb863c07eaf38e0bf289fc0841

**Comment by gegeweb** [comment]
I could have searched a long time then!
And my solution only worked because I had updated from the master. Before seeing the messages.

I close the issue.
