### ISSUE TITLE
SyntaxError: JSON.parse: unexpected character

### ISSUE THREAD

**Issue by pitcock** [Raruto/leaflet-elevation#66]
Hi,

using your example [leaflet-elevation_string-data.html](https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_string-data.html) with my geojson data gives me this error:
```js
SyntaxError: JSON.parse: unexpected character
```

I'm using a geojson string which is an automatically generated from a Garmin FIT file. Howerver there is sometimes an empty altitude value like:

```js
[11.74641,47.55261,]
```

The other values look like:

```js
[11.74652,47.55291,1020]
```

Is there a way to suppress the SyntaxError and ignore the missing altitude?

**Comment by Raruto** [comment]
Hi pitcock,
if you want to solve the problem programmatically I suggest you to take a look at the following library:

https://github.com/RyanMarcus/dirty-json

if instead it is a question of how to fix just a "single" file, try using this tool:

http://ryanmarcus.github.io/dirty-json/

_Have a nice day,
Raruto_

**Comment by pitcock** [comment]
Hi Raruto,

thank you very much for the links. I will test the programmatically solution.

I also found this thread:

https://github.com/MrMufflon/Leaflet.Elevation/issues/63#issue-192998443

Would this be a good addition for your solution?

**Comment by Raruto** [comment]
Currently points without a "z" value are already discarded

https://github.com/Raruto/leaflet-elevation/blob/1d512e5dcc2be5f43eb609227e49c132bdb09f38/src/altitude.js#L25

Instead, your problem is related to a malformed JSON structure:

https://github.com/Raruto/leaflet-elevation/blob/1d512e5dcc2be5f43eb609227e49c132bdb09f38/src/utils.js#L45

Since [`JSON.parse`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse) is a native function, so it could also be more difficult to solve (with just a few lines), but if you are good with regex replace you could also achieve it ...

**Comment by pitcock** [comment]
Hi Raruto,

thank you for the hint.

when I use this method

$array = str_replace( ',]', ',0]', $array );

the total length is correct and I get gaps in the graph (replace-01.png)

![replace-01](https://user-images.githubusercontent.com/28976674/86891421-1c2b1380-c0ff-11ea-8999-03e42459bfbe.png)


when I use this method

$array = str_replace( ',]', ',]', $array );

the total length is incorrect and I get no gaps in the graph (replace-02.png)

![replace-02](https://user-images.githubusercontent.com/28976674/86891478-336a0100-c0ff-11ea-870c-905f5f464b2c.png)

Is there a way to get the correct total length and no gaps?

**Comment by Raruto** [comment]
>when I use this method
>```php
>$array = str_replace( ',]', ',]', $array );
>```
>the total length is incorrect and I get no gaps in the graph

maybe you meant this:

```php
$array = str_replace( ',]', ']', $array );
```

> Is there a way to get the correct total length and no gaps?

First of all make sure you are using the [latest](https://unpkg.com/@raruto/leaflet-elevation) available version of this library, if you will still have problems please submit a demo file.

**Comment by pitcock** [comment]
Hi Raruto,

this was a type you are right, I tried 

$array = str_replace( ',]', ']', $array );

I'm using your latest library. Here is a demo file containing empty altitudes. [11.74641,47.55261,]

[data.txt](https://github.com/Raruto/leaflet-elevation/files/4889274/data.txt)

I tried

[11.74641,47.55261]

and

[11.74641,47.55261,0]

for the screenshots

**Comment by Raruto** [comment]
>this was a type you are right, I tried
>```php
>$array = str_replace( ',]', ']', $array );
>````

Your file lacks of many z values, but try this again with **version 1.3.1**

**NB** currently, all points (starting from the first one) where the z value is missing are discarded (this is just for the algorithm simplicity, anyway, if you have any suggestions pull requests are welcome)
