### ISSUE TITLE
POI in chart

### ISSUE THREAD

**Issue by fra-lab** [Raruto/leaflet-elevation#69]
Hello,
many compliments for this project. This is not a real issue, but only and information request. In your opinion is possible to overlay the clickable waypoints also in the altitude graph? 
Thank you!

**Comment by Raruto** [comment]
Hi fra-lab,

> In your opinion is possible to overlay the clickable waypoints also in the altitude graph?

Yes. I'll point out some of useful resources:

1. You can listen to the following event for hooking all the gpx markers

    https://github.com/Raruto/leaflet-elevation/blob/c361a6420334275fd1a235c06a1d14ab75f54643/src/utils.js#L99

2. You can adapt the following demo for drawing all your chart markers:

- https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_dynamic-runner.html

---

**For further info:**

- [leaflet-gpx/gpx.js](https://github.com/mpetazzoni/leaflet-gpx/blob/main/gpx.js/): source code of the **`L.GPX`** class (on which this library depends on)
- [leaflet-elevation/libs/extended-ui.js](https://github.com/Raruto/leaflet-elevation/blob/master/libs/extended-ui.js): just another example of how to customize the **`L.Control.Elevation`** class

---

_Greetings,
Raruto_
