### ISSUE TITLE
Snap to track (within buffer) to move cursor position

### ISSUE THREAD

**Issue by chrisleaman** [Raruto/leaflet-elevation#70]
Thanks for making such a useful extension! I have a quality of life suggestion. Would it be possible to add a buffer around the track in leaflet so when you're close enough to the line it "snaps" to the line?

For example, if the cursor is within say 10 pixels of the line I can move the position of the marker, rather than the cursor having to be exactly on the line. In the example, I basically want to move the marker when the cursor is close enough.

Thanks!

![iihAd9kxDm](https://user-images.githubusercontent.com/7591552/89486217-eb192e00-d7e5-11ea-8d95-7dfff153c99b.gif)

**Comment by Raruto** [comment]
Hi Chris,
you can use the [Leaflet.AlmostOver](http://makinacorpus.github.io/Leaflet.AlmostOver/) library to achieve that, take a look at the [leaflet-elevation_almost-over.html](https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_almost-over.html) demo for a more complete example.

_Have a nice day,
Raruto_

**Comment by chrisleaman** [comment]
Wonderful, thank you so much for the quick reply! The demo is really helpful 👍
