### ISSUE TITLE
Incorrect behaviour with not one map on page

### ISSUE THREAD

**Issue by ZhukDmitry** [Raruto/leaflet-elevation#71]
Hi.
I have some issues when display a few maps with elevation.
1 - if I display 2 maps with elevations for each of them, for example below the map, I got map 1 - 2 diagrams - map 2
2 - if I display each map with elevation on tabs, I got only one elevation

Thanks for your development

**Comment by Raruto** [comment]
The problem you exposed is due to the following lines:

https://github.com/Raruto/leaflet-elevation/blob/51dfc28d63a2fe01031307945059d68b2c7a63da/src/control.js#L377

to solve it try to do as follows:

```js
var controlElevation = L.control.elevation(
    detached: true,
    elevationDiv: "#elevation-div-track1", // unique name for map 1
);
var controlElevation = L.control.elevation(
    detached: true,
    elevationDiv: "#elevation-div-track2", // unique name for map 2
);
```

As always, pull requests are welcome ...

_Have a nice day,
Raruto_

**Comment by ZhukDmitry** [comment]
Thanks, it helped, but whenever I enter any div name, it generates new one own.
