### ISSUE TITLE
GpxGroup doesn't use options

### ISSUE THREAD

**Issue by marcin-gryszkalis** [Raruto/leaflet-elevation#73]
https://github.com/Raruto/leaflet-elevation/blob/464a5ed0aa98691e970d4c943b268897624864b9/libs/leaflet-gpxgroup.js#L203

the L.GPX constructor is called with static set of options instead of Options.gpxOptions (merged with polyline_options for color handling). This makes switching async to false impossible.

I need to turn off async because I'm not able to force the order of gpx tracks (the order is determined by gpx complexity -> duration of parsing).

**Comment by Raruto** [comment]
Hi marcin,

thanks for the report, could you also submit a resolutive pull? (I keep that library only as an example for others...)

_Thank you,
Raruto_

**Comment by Raruto** [comment]
From version **1.3.6** I added the async parameter:

https://github.com/Raruto/leaflet-elevation/blob/6ab2151f87836673f0e770986743627b7e5f238b/libs/leaflet-gpxgroup.js#L107

_Have a nice day,
Raruto_
