### ISSUE TITLE
Suggestion: speed graph

### ISSUE THREAD

**Issue by velocat** [Raruto/leaflet-elevation#79]
I created an additional hook to display the track speeds as an additional graph:
I can't create a pull request, would you like to add it here? ))

https://github.com/velocat/leaflet-elevation/blob/master/src/speed.js

![speed](https://user-images.githubusercontent.com/534853/95224958-f13a8380-0803-11eb-89dc-12e57697a1b1.PNG)

**Comment by velocat** [comment]
I also want to suggest changing the style of the cursor for the legend to pointer :)

**Comment by Raruto** [comment]
Hi velocat,
to create your own "[new pull request](https://github.com/velocat/leaflet-elevation/compare)" you can use the following [page](https://github.com/velocat/leaflet-elevation/pulls).

Be carefull to following line:

https://github.com/Raruto/leaflet-elevation/blob/fe8aff06e357574db6e496fdbb4a6a9fe62f7765/src/time.js#L37

**Comment by velocat** [comment]
I changed this by making a check if the time was already added. All in a pull request ))
