### ISSUE TITLE
Elevation chart tooltip Safari (Mac)

### ISSUE THREAD

**Issue by rallemann** [Raruto/leaflet-elevation#8]
Great plugin, thank you very much for that work! I'm actually implementing it in a new Wordpress theme for my website together with the latest version of Leaflet (1.5.1). 

Initially I had some JS errors that prevented the GPS-Track from being displayed at the map (console: ReferenceError: Can't find variable: that leaflet-elevation.js:802) but I found a workaround for it (loaded the same GPX-file again with gpx.js, not clean but working).

Question: is it possible to manually set the position for the elevation profile's tooltip? Or preventing it from following the profile? While Chrome & Firefox handle to show it even if it goes out of canvas (height), Safari cuts it. At the end of the profile, when the tooltip goes off-canvas, it's cut in all three browsers I tried. Thank you!

**Comment by Raruto** [comment]
> Initially I had some JS errors that prevented the GPS-Track from being displayed at the map (console: ReferenceError: Can't find variable: that leaflet-elevation.js:802) but I found a workaround for it (loaded the same GPX-file again with gpx.js, not clean but working).

I think that in version 0.1.1 this little bug  shouldn't be there anymore

> Question: is it possible to manually set the position for the elevation profile's tooltip? Or preventing it from following the profile? While Chrome & Firefox handle to show it even if it goes out of canvas (height), Safari cuts it. At the end of the profile, when the tooltip goes off-canvas, it's cut in all three browsers I tried. Thank you!

regarding the question of the label that comes out from the right margin of the chart, I think we should calculate when the cursor reaches the middle of the diagram and move it to the other side of the "height indicator" (eg. as it happens [here](https://devfarm.it/wp-gpx-maps-demo/)).

In particular, the following function is called each time the mouse hovers the elevation chart:

```javascript
  /*
   * Handles the moueseover the chart and displays distance and altitude level
   */
  _mousemoveHandler: function(d, i, ctx) {
    if (!this._data || this._data.length === 0) {
      return;
    }
    var coords = d3.mouse(this._background.node());
    var item = this._data[this._findItemForX(coords[0])];


    this._forceHidePositionMarker();
    this._showDiagramIndicator(item, coords[0]); // should handle tooltip appearance/position
    this._showPositionMarker(item);


    this._map.fireEvent("elechart_change", {
      data: item
    }, true);


  },

```
some good ideas on the necessary changes?

```javascript
  _showDiagramIndicator: function(item, xCoordinate) {
    var opts = this.options;
    this._focusG.style("visibility", "visible");
    this._mousefocus.attr('x1', xCoordinate)
      .attr('y1', 0)
      .attr('x2', xCoordinate)
      .attr('y2', this._height())
      .classed('hidden', false);

    var alt = item.altitude,
      dist = item.dist,
      ll = item.latlng,
      numY = opts.hoverNumber.formatter(alt, opts.hoverNumber.decimalsY),
      numX = opts.hoverNumber.formatter(dist, opts.hoverNumber.decimalsX);

    this._focuslabeltext
      .attr("x", xCoordinate)
      .attr("y", this._y(item.altitude))
      .style("font-weight", "700");

    this._focuslabelX
      .text(numY + (opts.imperial ? " ft" : " m"))
      .attr("x", xCoordinate + 10);
    this._focuslabelY
      .text(numX + (opts.imperial ? " mi" : " km"))
      .attr("x", xCoordinate + 10);

    var bbox = this._focuslabeltext.node().getBBox();
    var padding = 2;

    this._focuslabelrect
      .attr("x", bbox.x - padding)
      .attr("y", bbox.y - padding)
      .attr("width", bbox.width + (padding * 2))
      .attr("height", bbox.height + (padding * 2));

},
```

**Comment by rallemann** [comment]
Hello Raruto, thank you. I replaced the plugin files with the newest version and the mentioned JS bug is gone. I get a new one now: 

`leaflet-elevation.js?ver=0.1.1:803 Uncaught TypeError: Cannot read property 'fitBounds' of undefined
    at i.<anonymous> (leaflet-elevation.js?ver=0.1.1:803)
    at i.fire (leaflet.js?ver=1.5.1:5)
    at cb (gpx.js?ver=1.4.0:282)
    at XMLHttpRequest.req.onreadystatechange (gpx.js?ver=1.4.0:268)`

When I try to remove my double-call of the GPX file it breaks the map (it's then 1:1 your example code). With my first attempt I simply copied your code. As a result, the gpx track got parsed and the profile was shown. But the GPX track wasn't displayed. However, my little workaround is working, so no worries. (I simply called it another time the gpx.js way). Like so:

`var url = '<?php the_field('gps-upload'); ?>'; 
			new L.GPX(url, {
  				async: true,
  				marker_options: {}
				}).on('loaded', function(e) {
  						map.fitBounds(e.target.getBounds());
				}).addTo(map);`

As for the tooltip: the behaviour in the example you provided is great. Would be awesome to implement it. However, that goes way beyond my JS knowledge. No idea, I apologize.

**Comment by Raruto** [comment]
`Uncaught TypeError: Cannot read property 'fitBounds' of undefined`

Your log reports  that error on line 803:

```javascript
  addGPXFile: function(url) {
    if (!url) {
      throw "Invalid gpx url";
    }

    this.options.gpxOptions.polyline_options.color = this._getLineHexColor();

    this.gpx = new L.GPX(url, this.options.gpxOptions);

    this.gpx.on('loaded', function(e) {
       this._map.fitBounds(e.target.getBounds()); // Line 803: your map element is undefined..
    });
    this.gpx.once("addline", function(e) {
      this.addData(e.line, this.gpx);
      this._map.fireEvent("eledata_loaded", {
        data: null,
        layer: this.gpx
      }, true);
    }, this);

    this.gpx.addTo(this._map); // for the same reason the track it is not added/displayed on the map
},
```

---

version 0.1.2 should solve our overflow issues..
