### ISSUE TITLE
Some display bugs

### ISSUE THREAD

**Issue by velocat** [Raruto/leaflet-elevation#81]
1. On initial page load, if I hover over the track line for the first time, I get the wrong container formatting:

![Ele1](https://user-images.githubusercontent.com/534853/96073120-73831180-0eae-11eb-8795-53eb0c25f2d0.PNG)

It is enough to hover over a line or chart area a second time, and everything becomes normal

![Ele2](https://user-images.githubusercontent.com/534853/96073278-d4124e80-0eae-11eb-9898-5ea241bbe9e4.PNG)

This is not critical, but ugly.
Perhaps this is just my mistake, somewhere in my personal code, but then please tell me what the problem might be?

2.  Sometimes, if Ticks takes an integer value and is maximum, there is an overlap with the Label (in this case for the slope plot).
How could you fix this?
![Ele3](https://user-images.githubusercontent.com/534853/96073522-484cf200-0eaf-11eb-9ff4-80b858f5f2cb.PNG)

Maybe you should increase the top padding of the chart and place the labels above the charts?

PS thanks for the great scripts :)) As you can see, I want to bring everything to perfection)

**Comment by Raruto** [comment]
> On initial page load, if I hover over the track line for the first time, I get the wrong container formatting:
> It is enough to hover over a line or chart area a second time, and everything becomes normal
> Perhaps this is just my mistake, somewhere in my personal code, but then please tell me what the problem might be?

Hard to say, at most you can try to programmatically force a `redraw`.

> Sometimes, if Ticks takes an integer value and is maximum, there is an overlap with the Label (in this case for the slope plot).
How could you fix this?
> Maybe you should increase the top padding of the chart and place the labels above the charts?

Maybe, but I'm not a d3.js guru, have you tried searching about it on [stackoverflow](https://stackoverflow.com/tags/d3.js)?

**Comment by Raruto** [comment]
The first problem is due to the following lines (x values are missing at the first mouse over):

https://github.com/Raruto/leaflet-elevation/blob/fe8aff06e357574db6e496fdbb4a6a9fe62f7765/src/components.js#L264
https://github.com/Raruto/leaflet-elevation/blob/fe8aff06e357574db6e496fdbb4a6a9fe62f7765/src/components.js#L148

you can work around by doing this way:

```js
L.Control.Elevation.addInitHook(function() {
  this.once('elechart_change elechart_hover',function(e){
    if (this._chartEnabled) this._chart._showDiagramIndicator(e.data, e.xCoord);
    this._updateMarker(e.data);
  });
});
```

For the second problem you can start from editing this code snippet:

```js
d3.selectAll('.y.axis.right > text').attr('dx', '1em')
```
