### ISSUE TITLE
Calling clear() displays black polyline

### ISSUE THREAD

**Issue by topive** [Raruto/leaflet-elevation#83]
I'm creating a map where by clicking a polyline layer an elevation chart appears. Clicking again chart gets removed. The click event is tied to another layer not associated with the elevation data. Everything is working fine, but on the second click when clear() is called a black polyline appears displaying the actual elevation polyline. Basically I'm trying to display the elevation chart without displaying the elevation polyline on the map. Is that possible?

**Comment by Raruto** [comment]
Hi  topive,
from version **1.4.0** try to set the following option:

```js
 var controlElevation = L.control.elevation({
  polyline: false,
});
```
