### ISSUE TITLE
Question: how to use a local gpx file

### ISSUE THREAD

**Issue by alvaropp** [Raruto/leaflet-elevation#84]
Hi there,

I'm just trying to use a local .gpx file rather than an url, and I cannot figure out how (my JS knowledge is limited!).

Any pointers would be much appreciated 👍

**Comment by velocat** [comment]
Hi! The list of examples includes:

https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_upload-gpx.html

**Comment by Raruto** [comment]
Hi alvaro,
[here](https://github.com/Raruto/leaflet-elevation/issues/61) you will find some other examples.

Basing on your intentions, there will also be several other possible ways (e.g. you can simply use [xampp](https://en.wikipedia.org/wiki/XAMPP) to start a development server locally).

_Have a nice day,
Raruto_

**Comment by alvaropp** [comment]
Many thanks velocat and Raruto for your quick replies. I managed to get this working using the examples you provided 👍 

Thanks again for this nice library.
