### ISSUE TITLE
gpxGroup start and end icons

### ISSUE THREAD

**Issue by seanburles** [Raruto/leaflet-elevation#85]
Hi, I was wondering if it is possible / an example of adding start and end icons to the gpx tracks when using the gpxGroup class. 

Something similar to : http://mpetazzoni.github.io/leaflet-gpx/

but on a map like : https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_hoverable-tracks.html

I haven't had any luck so far.

**Comment by Raruto** [comment]
Hi Sean,
i updated that [example](https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_hoverable-tracks.html) to make it work with the latest latest release **[1.5.0](https://www.npmjs.com/package/@raruto/leaflet-elevation/v/1.5.0)**

Here it is a code sample:

```js
L.gpxGroup(tracks, {
  points: points,
  points_options: opts.points,
  elevation: true,
  elevation_options: opts.elevation,
  marker_options: {
    startIconUrl: 'pin-icon-start.png',
    endIconUrl: 'pin-icon-end.png',
    shadowUrl: 'pin-shadow.png',
  }
  legend: true,
  distanceMarkers: false,
});
```

_Happy devops,
Raruto_

**Comment by seanburles** [comment]
Awesome! Thank you so much Raruto. I got it working now.
