### ISSUE TITLE
Disable bounds fitting

### ISSUE THREAD

**Issue by topive** [Raruto/leaflet-elevation#87]
Is it possible to disable fitting the map to track bounds when using leaflet elevation? I'm building a webapp where the elevation is not showing at startup, but only when a route is clicked. Now when the route gets clicked, I get this zooming effect which is not desirable.

**Comment by Raruto** [comment]
Hi topive,
take a try with the following option (since: **v1.5.2**):

```js
autofitBounds: false
```

Later, if you may need them, you can use the following functions:

```js
controlElevation.getBounds();
controlElevation.fitBounds();
```


_Happy new Year,
Raruto_

**Comment by topive** [comment]
Works like charm, thanks!
