### ISSUE TITLE
Mousemove errors 

### ISSUE THREAD

**Issue by velocat** [Raruto/leaflet-elevation#88]
Hello Raruto :)
I connected the latest version to my project and I see errors:

**Firefox:**

```js
Uncaught TypeError: item is undefined
    _showDiagramIndicator chart.js:628
    _mousemoveHandler control.js:592
    fire leaflet.js:5
    _mousemoveHandler chart.js:541
    Tt d3.min.js:2
    St d3.min.js:2
    each d3.min.js:2
    on d3.min.js:2
    _appendFocusRect chart.js:270
    call d3.min.js:2
    _appendFocusable chart.js:238
    call d3.min.js:2
    initialize chart.js:39
    i leaflet.js:5
    _initChart control.js:477
    _d3LazyLoader control.js:241
    promise callback*onAdd control.js:239
    addTo control.js:44
```
   
 **GoogleChrome:**
```js
Uncaught TypeError: Cannot read property 'z' of undefined
    at i._showDiagramIndicator (chart.js:628)
    at i._mousemoveHandler (control.js:592)
    at i.fire (leaflet.js:5)
    at i._mousemoveHandler (chart.js:541)
    at SVGRectElement.<anonymous> (d3.min.js:2)
```

These errors pop up when you move the cursor over the elevation graph to the right and reach the end of it, but not yet outside the "elevation-div"
![ele](https://user-images.githubusercontent.com/534853/104817934-9a4a3e80-5835-11eb-83c5-7b57749179c5.JPG)

That is, in fact, the mousemove event continues to be called, but there is no more data in that area.
And this is strange, because in other areas (left, top, bottom) everything is ok

My set options:

```js
elevation_options = {
  width: 1130,
  height: 170,
  position: "bottomleft",
  elevationDiv: "#elevation-div",
  marker: 'position-marker',
  followMarker: false,
  polylineSegments: {
    color: "#00F"
  },
  collapsed: false,
  responsive: false,
  detached: true,
  autohide: false,
  slope: false, //"disabled",
  summary: false,
  legend: true,
  zFollow: 15
};
```

Although, perhaps these are mistakes on my part, then can you at least tell me what caused this?

**Comment by Raruto** [comment]
Hi velocat,
it is somehow related to the following element / inline rule:

```css
.elevation-control svg g.focus > rect {
 pointer-events: all; /* causes a 1px increase */
}
```

Toggling the `responsive: false` option allows you to check this bug.

I did not find out how to solve the css issue, but take a try to **v1.5.3** regarding the js error (see: https://github.com/Raruto/leaflet-elevation/commit/0d4ca24ea9a638442feecf2dd698a5c415f69b0e for more info).

_Have a nice Day,
Raruto_

**Comment by velocat** [comment]
> I did not find out how to solve the css issue, but take a try to **v1.5.3** regarding the js error (see: [0d4ca24](https://github.com/Raruto/leaflet-elevation/commit/0d4ca24ea9a638442feecf2dd698a5c415f69b0e) for more info).

It's great!
With this fix, everything is ok. Thank you for efficiency )))
