### ISSUE TITLE
Error in function "style"

### ISSUE THREAD

**Issue by velocat** [Raruto/leaflet-elevation#89]
If the container has not display property, then function _resizeChart () will throw an unknown value error for setProperty.
Fix:

```js
function style(targetNode, name, value) {
  if (typeof value === "undefined") return L.DomUtil.getStyle(targetNode, name);
  else return targetNode.style.setProperty(name, value||"");
}
```

**Comment by velocat** [comment]
Although, of course, it would be better to just check if the property display is there
```
_resizeChart: function _resizeChart() {
        // prevent displaying chart on resize if hidden
        if (style(this._container, "display") == "none") return;
```

**Comment by Raruto** [comment]
Hi velocat 
I'm not really sure about what you say.

That function is already invoked according to the following condition:

```js
if (typeof value !== "undefined") targetNode.style.setProperty(name, value);
```

and therefore the only plausible error should be: `targetNode` is undefined:

```js
if (style(this._container, "display") == "none") return; // "value" param is not specified
```

Are you sure the error is caused from that line? (a full example would help)

_Have a nice Day,
Raruto_
