### ISSUE TITLE
Bug hide indicator if collapse == true

### ISSUE THREAD

**Issue by serako** [Raruto/leaflet-elevation#9]
If you move out the elevation trace, the curve collapse but the indicator is visible.
Option autohideindication == true/ false is same

I resolve this on uncomment this on line 490 and pass true on force variable :
  _mouseoutHandler: function() {
    this._hidePositionMarker(true);
}, 

some reason to uncomment?

**Comment by Raruto** [comment]
I have moved / rewritten the code a bit, let me know if this could be good:
https://github.com/Raruto/leaflet-elevation/blob/4bc2aeaca0155259fb3470b816ebcbd77d6b7e3c/leaflet-elevation.js#L614

**Comment by serako** [comment]
Not OK.
The indicator not hide if i click out the elevation chart (the elevation chart hide, on this action).
But the indicator hide if you change the map zoom (when the elevation chart is hidden). That why it's not a hard bug!

**Comment by serako** [comment]
...wait, on other test, with other construction... it's OK

in this case i use. with just one trace
```
el.loadChart(map); // attach elevation chart element to map
el.loadData('/topos/traces/47528.gpx'); // url or plain gpx/geojson data
```
it's not OK on the file i send to you in precedent issue

**Comment by Raruto** [comment]
> it's not OK on the file i send to you in precedent issue

have you tried with version 0.2.5?
