### ISSUE TITLE
Events in Example hoverable-tracks

### ISSUE THREAD

**Issue by MartinvonBerg** [Raruto/leaflet-elevation#90]
Hi, 
Great work! Thank's for sharing. This is not an issue, simply some questions.
I'm also using the leaflet-gpxroup.js plugin from the example "..hoverable-tracks" and have this questions:

- May I use another event than 'plugins-loaded' in line 158 `map.on('plugins_loaded', function(e) {` to show the map with all routes? Background: I don't use the plugin-option. I load the *.js-Files "conventionally".
- How may I show the elevation chart of the first track in `tracks` to show directly without user interaction? At the moment one has to hover over a track or to click the legend to show the elevation chart. 
- leaflet-elevation does obviously not work with version 6++ of d3.js. You probably know that. Do you have a plan to update?
- The last one: You write about i18n. But how to translate the string "altitude" direcectly under the elevation chart? I don't want to fiddle the code of your javascript be "update-ready".

Thank you very much.
Best Regards
Martin

**Comment by Raruto** [comment]
Hi martin,

> May I use another event than 'plugins-loaded' in line 158 `map.on('plugins_loaded', function(e) {` to show the map with all routes? Background: I don't use the plugin-option. I load the *.js-Files "conventionally".

You can try:

- remove the `plugins_loaded` hook
- replace it with the `init` hook or try a few other events [here](https://github.com/Raruto/leaflet-ui/search?q=fire)

---

> How may I show the elevation chart of the first track in `tracks` to show directly without user interaction? At the moment one has to hover over a track or to click the legend to show the elevation chart.

[That](https://github.com/Raruto/leaflet-elevation/blob/2ce9f8a97bd356580b0cb279b0b332c1eea59752/libs/leaflet-gpxgroup.js) library is just the proof of a concept, feel free to edit it or propose some pulls.

Take a look at [this](https://github.com/Raruto/leaflet-elevation/issues/7#issuecomment-535144740) thread to understand how the **setSelection** could works.

---

> leaflet-elevation does obviously not work with version 6++ of d3.js. You probably know that. Do you have a plan to update?

I didn't know (it's a library that I use very little), anyway pull request well accepted.

---

> The last one: You write about i18n. But how to translate the string "altitude" direcectly under the elevation chart? I don't want to fiddle the code of your javascript be "update-ready".

I don't think I understand, can you point me to something?

---

_Have a nice day,
Raruto_

**Comment by MartinvonBerg** [comment]
Hi Raruto,  

Tank's for your answer. 

concerning the event, instead of "plugins_loaded": 

I tested the Events: "load, loaded, route_loaded, idle,
initHooks_called, plugins_loaded, initHooks_called": 

And this: map.whenReady( function() {...} 

Nothing happens. But, It works with a timeout: 

window.setTimeout( function() {... 

}, 1000 ); 

But, that is a really ugly solution. 
Any clue which event would be the correct one? I really don't understand
why the standard-events are not useable. 

--------------------------------------------------------------- 
Will check "set selection the next evenings. Thank you, for the link.  

--------------------------------------------------------------- 
d3.js: This is fun:  
I tested the code without d3.js (5.16.0): It works fine. 
WITH d3.js. latest 6.1.x : I doesn't work 

-------------------------------------------------------------- 
Translation: 
It is about this little "Altitude" at the bottom of the elevation chart,
see attached image. I searched in the code, whether there is an option,
but I'm too stupid to find it.  

Thank you very much. 

Best Regards 

Martin 

Am 2021-02-01 11:17, schrieb Raruto: 

> Hi martin, 
> 
>> May I use another event than 'plugins-loaded' in line 158 map.on('plugins_loaded', function(e) { to show the map with all routes? Background: I don't use the plugin-option. I load the *.js-Files "conventionally".
> 
> You can try: 
> 
> * remove the plugins_loaded hook
> * replace it with the init hook or try a few other events here [1]
> 
> I tested: 
> 
> -------------------------
> 
>> How may I show the elevation chart of the first track in tracks to show directly without user interaction? At the moment one has to hover over a track or to click the legend to show the elevation chart.
> 
> That [2] library is just the proof of a concept, feel free to edit it or propose some pulls. 
> 
> Take a look at this [3] thread to understand how the SETSELECTION could works. 
> -------------------------
> 
>> leaflet-elevation does obviously not work with version 6++ of d3.js. You probably know that. Do you have a plan to update?
> 
> I didn't know (it's a library that I use very little), anyway pull request well accepted. 
> -------------------------
> 
>> The last one: You write about i18n. But how to translate the string "altitude" direcectly under the elevation chart? I don't want to fiddle the code of your javascript be "update-ready".
> 
> I don't think I understand, can you point me to something? 
> -------------------------
> 
> Have a nice day,
> Raruto 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [4], or unsubscribe [5].

  

Links:
------
[1] https://github.com/Raruto/leaflet-ui/search?q=fire
[2]
https://github.com/Raruto/leaflet-elevation/blob/2ce9f8a97bd356580b0cb279b0b332c1eea59752/libs/leaflet-gpxgroup.js
[3]
https://github.com/Raruto/leaflet-elevation/issues/7#issuecomment-535144740
[4]
https://github.com/Raruto/leaflet-elevation/issues/90#issuecomment-770743454
[5]

**Comment by Raruto** [comment]
Hi Martin,

Did you try to just do this before? 

```js

var map = L.map('map', opts.map);
var routes;

/**
 * Unnecessary hook since you load your are including your javascript dependencies in the traditional way
 */
// map.on('plugins_loaded', function(e) {

    routes = L.gpxGroup(tracks, {

    ...

// });
```

> d3.js: This is fun:
> I tested the code without d3.js (5.16.0): It works fine.

You can set the [`lazyLoadJS`](https://github.com/Raruto/leaflet-elevation/blob/b0d9579f1aca93964ec956356442c260990815be/src/options.js#L37) option to false to avoid automatically including missing javascript dependencies (i.e. not detected in the global scope).

> Translation:
> It is about this little "Altitude" at the bottom of the elevation chart, see attached image. I searched in the code, whether there is an option, but I'm too stupid to find it.

Are you referring to the profile legend below the graph? (I don't see the any attached picture ...) 

![legend](https://user-images.githubusercontent.com/9614886/106511744-f3220400-64d0-11eb-9e6b-509292f33a9f.png)

**Comment by MartinvonBerg** [comment]
Hi Ratuto, 

Your question: Did you try to just do this before? 

Yes: 

var map = L.map('map', opts.map);
var routes;
... other code ... (control layer, zoom glas, markers....)

routes = L.gpxGroup(tracks, {.... 

--> throws the js errormessage: Uncaught TypeError: L.gpxGroup is not a
function 

----------------------- 
Working version: But horrible, won't work on slow machines / network 

var map = L.map('map', opts.map);
var routes;
... other code ... (control layer, zoom glas, markers....)

window.setTimeout( function() {  
    routes = L.gpxGroup(tracks, {.... 
     .... your example code.... 
    } 

}, 1000 ); 

----------------------- 
Not working version(s) 

map.on('plugins_loaded', function() {  // tested with: load, loaded,
route_loaded, idle, initHooks_called, plugins_loaded, initHooks_called 

    routes = L.gpxGroup(tracks, {.... 
     .... your example code 
    } 

}, 1000 ); 

--> The map is shown, but the route-layer is not shown. And no error
messages. The event 'plugins_loaded' is never fired. 
I tried many other events with no effect. My knowledge of JS is too low.
 

------------------------------------ 
----------------------------------- 
d3.js + autoload : Yes, d3.js 5.15.0 is autoloaded by the current
version of leaflet-elevation at unpkg.com 
If I change my Wordpress to :  

wp_enqueue_script('fm-script3',
"https://cdnjs.cloudflare.com/ajax/libs/d3/6.5.0/d3.min.js",
array('jquery'), '3.1.0', true);  
It works now!!! And I don't know why.  
I'm so sorry for bothering you with that! 
  ------------------------------------------------- 
Translation: 
Are you referring to the profile legend below the graph? (I don't see
the any attached picture ...) 
Yes!
It is probably line 58 in ./src/altitude.js: 

this.on("elechart_legend", function() { 
        this._altitudeLegend = this._chart._legend.append('g') 
            .call( 
                D3.LegendItem({ 
                    name: 'Altitude', 
                    width: this._width(), 
                    height: this._height(), 
                    margins: this.options.margins, 
                }) 
            ); 
    }); 
You are using the i18n of https://github.com/yohanboniface/Leaflet.i18n
?? 
So, the code could be: 

this.on("elechart_legend", function() { 
        this._altitudeLegend = this._chart._legend.append('g') 
            .call( 
                D3.LegendItem({ 
                    name: L._('Altitude'),  //<---------- make the
Legend name translatable 
                    width: this._width(), 
                    height: this._height(), 
                    margins: this.options.margins, 
                }) 
            ); 
    });   
 Best Regards 

Martin 

Am 2021-02-01 21:04, schrieb Raruto: 

> Hi Martin, 
> 
> Did you try to just do this before? 
> 
> var map = L.map('map', opts.map);
> var routes;
> 
> /**
> * Unnecessary hook since you load your are including your javascript dependencies in the traditional way
> */
> // map.on('plugins_loaded', function(e) {
> 
> routes = L.gpxGroup(tracks, {
> 
> ...
> 
> // });
> 
>> d3.js: This is fun:
>> I tested the code without d3.js (5.16.0): It works fine.
> 
> You can set the lazyLoadJS [1] option to false to avoid automatically including missing javascript dependencies (i.e. not detected in the global scope). 
> 
>> Translation:
>> It is about this little "Altitude" at the bottom of the elevation chart, see attached image. I searched in the code, whether there is an option, but I'm too stupid to find it.
> 
> Are you referring to the profile legend below the graph? (I don't see the any attached picture ...) 
> 
> [2] 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [3], or unsubscribe [4].

  

Links:
------
[1]
https://github.com/Raruto/leaflet-elevation/blob/b0d9579f1aca93964ec956356442c260990815be/src/options.js#L37
[2]
https://user-images.githubusercontent.com/9614886/106511744-f3220400-64d0-11eb-9e6b-509292f33a9f.png
[3]
https://github.com/Raruto/leaflet-elevation/issues/90#issuecomment-771121480
[4]

**Comment by Raruto** [comment]
> throws the js errormessage: Uncaught TypeError: L.gpxGroup is not a function

It means that you are missing the `L.gpxGroup` library, take a look at the previous version of that example to understand better:

 https://github.com/Raruto/leaflet-elevation/blob/8b95378ef93076792551cca0c1dc11ada06a3f1f/examples/leaflet-elevation_hoverable-tracks.html#L35-L42

---

> If I change my Wordpress to :
> ```js
> wp_enqueue_script('fm-script3', "https://cdnjs.cloudflare.com/ajax/libs/d3/6.5.0/d3.min.js", array('jquery'), '3.1.0', true);
>```
> It works now!!! And I don't know why. I'm so sorry for bothering you with that!

That is the correct behavior if you include d3.js before leaflet-elevation (ie. no `lazyLoading` of missing dependencies).

---

> You are using the i18n of https://github.com/yohanboniface/Leaflet.i18n ??
> It is probably line 58 in ./src/altitude.js:

Yes it should be that line, when I have a little more time I'll try to make them translatable:

- https://github.com/Raruto/leaflet-elevation/blob/a5a5b2f9b2abd417e1ae72f4253e3b455600edd5/src/acceleration.js#L60
- https://github.com/Raruto/leaflet-elevation/blob/a5a5b2f9b2abd417e1ae72f4253e3b455600edd5/src/altitude.js#L58
- https://github.com/Raruto/leaflet-elevation/blob/a5a5b2f9b2abd417e1ae72f4253e3b455600edd5/src/slope.js#L67
- https://github.com/Raruto/leaflet-elevation/blob/a5a5b2f9b2abd417e1ae72f4253e3b455600edd5/src/speed.js#L60

_Have a nice day,
Raruto_

**Comment by brigghius** [comment]
> > throws the js errormessage: Uncaught TypeError: L.gpxGroup is not a function
> 
> It means that you are missing the `L.gpxGroup` library, take a look at the previous version of that example to understand better:
> 
> https://github.com/Raruto/leaflet-elevation/blob/8b95378ef93076792551cca0c1dc11ada06a3f1f/examples/leaflet-elevation_hoverable-tracks.html#L35-L42
> 


i have the same problem (.gpxGroup is not a function), but i don't fix it adding the scripts in my index.html
![image](https://user-images.githubusercontent.com/49524691/203953928-22755c98-5b82-4048-80cb-95ffb61eb0b9.png)

![image](https://user-images.githubusercontent.com/49524691/203953193-749f7435-db78-40d2-93e2-cfd1288e3fa7.png)
without (L as any) i have an error

![image](https://user-images.githubusercontent.com/49524691/203953769-9cde4bd9-a95d-4a4c-b4a4-9395a5c580a8.png)

how can i fix it in my angular project? 
thanks

**Comment by hupe13** [comment]
gpx.js isn't needed anymore. See the actual [example](https://github.com/Raruto/leaflet-elevation/blob/master/examples/leaflet-elevation_hoverable-tracks.html) .

**Comment by brigghius** [comment]
> gpx.js isn't needed anymore.

I had seen the example, I started from that, but it still doesn't work :(
