### ISSUE TITLE
autoscroll with leaflet-gpxgroup.js (ref to issue #90)

### ISSUE THREAD

**Issue by MartinvonBerg** [Raruto/leaflet-elevation#96]
Hi,
I'm using your leaflet-gpxgroup.js for a WordPress-Plugin. Everything works fine now, except: 
There is an autoscroll-function on the map which I can't stop triggering. So, this is a help request, not an issue.

This autoscroll is not triggered on leaflet-elevation, only with  leaflet-gpxgroup.js.
For example, please check this page: https://www.mvb1.de/bildergalerie-wanderurlaub-madeira/

I tried to solve it with that code:

```js
$('#boxmap0').on('scroll touchmove mousewheel', function(e){
      e.preventDefault();
      e.stopPropagation();
      return false;
});
```
where `#boxmap0` is the id of the outer div.

Do you have any idea how to stop the scroll?
Any help welcome
Best Regards

Martin

**Comment by Raruto** [comment]
Hi Martin,

maybe are you referring to this?

https://github.com/Raruto/leaflet-elevation/blob/65bc8edc39b16f841b3ff7530460b5ecfdc5dc37/libs/leaflet-gpxgroup.js#L338-L340

**Comment by MartinvonBerg** [comment]
Hi, 

Great! I commented out and that's it. 

Thank you very much. 

Best Regards 

Martin 

Am 2021-03-07 01:48, schrieb Raruto: 

> Hi Martin, 
> 
> maybe are you referring to this? 
> 
> https://github.com/Raruto/leaflet-elevation/blob/65bc8edc39b16f841b3ff7530460b5ecfdc5dc37/libs/leaflet-gpxgroup.js#L338-L340 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

  

Links:
------
[1]
https://github.com/Raruto/leaflet-elevation/issues/96#issuecomment-792134193
[2]
