### ISSUE TITLE
Upgrading d3.js to v6.x

### ISSUE THREAD

**Issue by MartinvonBerg** [Raruto/leaflet-elevation#97]
Hi,
coming to back to my question on the latest version of d3.js.
According to your recommendation in issue #90 I changed the loading of scripts to:

```php
// Load local Styles
wp_enqueue_style('fm-style3', $plugin_url . 'css/leaflet.min.css');
wp_enqueue_style('fm-style4', $plugin_url . 'css/leaflet-elevation.min.css');
wp_enqueue_style('fm-style7', $plugin_url . 'css/leaflet-gesture-handling.min.css');
wp_enqueue_style('fm-style5', $plugin_url . 'css/Control.FullScreen.min.css');

// Load local Scripts
wp_enqueue_script('fm-script3',  $plugin_url . 'js/libs/d3.min.js', array('jquery'), '5.15.0', true); // does not work with d3 > version 6.0 !
wp_enqueue_script('fm-script2',  $plugin_url . 'js/libs/leaflet.min.js', array('jquery'), '1.7.1', true); 
wp_enqueue_script('fm-script4',  $plugin_url . 'js/libs/gpx.min.js', array('jquery'), '1.5.0', true); 
wp_enqueue_script('fm-script12', $plugin_url . 'js/libs/leaflet-gpxgroup.min.js', array('jquery'), '', true); 
wp_enqueue_script('fm-script5',  $plugin_url . 'js/libs/leaflet-elevation.min.js', array('jquery'), '1.5.3', true); 
wp_enqueue_script('fm-script8',  $plugin_url . 'js/libs/leaflet-gesture-handling.min.js', array('jquery'), '', true); 
wp_enqueue_script('fm-script10', $plugin_url . 'js/libs/Control.FullScreen.min.js', array('jquery'), '', true); 
wp_enqueue_script('fm-script11', $plugin_url . 'js/zoom-master/jquery.zoom.min.js', array('jquery'), '1.7.21', true); 
wp_enqueue_script('fm-script9',  $plugin_url . 'js/fotorama_multi.min.js', array('jquery'), '0.0.7', true);
```

and in my js-file im using `lazyLoadJS: false` according to your recommendation. (I also tried with 'true')

If I change the d3.js version to 6.5.0 I get error messages from chart.js at moving the vertical line on the elevation.
Everything works fine with d3 in V 5.15.0. 
According the the documentation in : https://observablehq.com/@d3/d3v6-migration-guide
it's a lot of work to migrate d3 from 5.x to 6.5.0. 
As it is Opensource you could expect me to provide a proposal code to upgrade but I fear I don't have the knowledge to do that.
So, it's not an issue just a 'update request for future if you have lots of time'

Best Regards

Martin

**Comment by Raruto** [comment]
Hi Martin,

> As it is Opensource you could expect me to provide a proposal code to upgrade but I fear I don't have the knowledge to do that.

And also help to write documentation, articles, tests or examples useful to others 😄

> So, it's not an issue just a 'update request for future if you have lots of time'

In version 1.6.0 there is this and other "temporal" improvements (literally).

If you're interested, I've updated these three examples to this latest release:

- [gpx demo](https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation.html)
- [geojson demo](https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_geojson-data.html)
- [kml demo](https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_kml-data.html)

---

**NB** in this release I have also replaced [**L.GPX**](https://github.com/mpetazzoni/leaflet-gpx) class in favor of the [@tmcw/togeojson](https://github.com/tmcw/togeojson) library, for those who are still interested in supporting it you can try to do like the following:

```html
<script src="https://unpkg.com/leaflet-gpx@1.5.1/gpx.js"></script>
<script src="https://unpkg.com/@raruto/leaflet-elevation@1.6.0/dist/leaflet-elevation.min.js"></script>
```

Refer to [MrMufflon/Leaflet.Elevation](https://github.com/MrMufflon/Leaflet.Elevation) for more info about the following.

```js
<script>
...
  var el = L.control.elevation();
  el.addTo(map);
  var g=new L.GPX("./mytrack.gpx", {async: true});
  g.on("addline",function(e){
  	el.addData(e.line);
  });
  g.addTo(map);
...
</script>
```

_Have nice Sunday,
Raruto_

**Comment by MartinvonBerg** [comment]
Thank you! Great! I'll try this next.
