### ISSUE TITLE
Undefined "map" variable in leaflet-gpxgroup.js

### ISSUE THREAD

**Issue by hupe13** [Raruto/leaflet-elevation#99]
There is an error in leaflet-gpxgroup.js, on [line 336](https://github.com/Raruto/leaflet-elevation/blob/master/libs/leaflet-gpxgroup.js#L336):

```js
 map.flyToBounds(e.layer.getBounds());
```
must be:

```js
 this._map.flyToBounds(e.layer.getBounds());
```

I have several gpx files with different structures. They all work with leaflet-elevation.min.js. With leaflet-gpxgroup.js not all of them work, the elevation chart is missing. I have used https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation.html and https://raruto.github.io/leaflet-elevation/examples/leaflet-elevation_hoverable-tracks.html as examples. I'm using Wordpress with the Plugin Leaflet Map.

**Comment by Raruto** [comment]
Hi hupe,

I updated that line as you say, is it ok? (I didn't quite understand if you are also reporting another error...)

_Have a nice day,
Raruto_

**Comment by hupe13** [comment]
I wrote about two problems, First you have fixed. Thank you very much for the update.
The second problem: I mean,  leaflet-gpxgroup.js does not show the elevation profile for every gpx file. But  leaflet-elevation.js does the job right with all gpx files. Should I prepare an example?

**Comment by Raruto** [comment]
Ok, also create a separate issue so we avoid messing with those who will read us later.
